colord, dbus-glib, dvdstyler, flightgear, gtk+2, ipset, kwebkitpart, kernel-custom, poppler, shared-mime-info, simgear, transmission, xorg-server

diff --git a/linux-tools/linux-tools.SlackBuild b/linux-tools/linux-tools.SlackBuild
--- a/linux-tools/linux-tools.SlackBuild
+++ b/linux-tools/linux-tools.SlackBuild
@@ -45,8 +45,12 @@ NAME=linux-tools
 PKG=${PKG:-${TMP}/package-${NAME}}
 
 # x.y.z / z=0 when not existent in tarball, eg. 3.4 will be 3.4.0
-VERSION=${VERSION:-3.7.9}
+VERSION=${VERSION:-3.8.0}
 SVER="$( echo ${VERSION} | cut -d . -f 1-2 )"
+if [ -z "$( echo ${VERSION} | cut -d . -f 3 )" ] ;then
+  echo "Missing sublevel in VERSION: ${VERSION}.?!"
+  exit 1
+fi
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
 else
@@ -189,6 +193,7 @@ export mandir=/usr/man
 export PERF_DEBUG=1
 export CFLAGS_OPTIMIZE="${SLKCFLAGS}"
 export LDFLAGS_OPTIMIZE="${LDFLAGS}"
+export NO_LIBUNWIND=1
 export HAVE_CPLUS_DEMANGLE=1
 export STRIP=/bin/true
 export NO_LIBUNWIND=1
