x86_64 batch #13

diff --git a/gnome/totem/totem.SlackBuild b/gnome/totem/totem.SlackBuild
--- a/gnome/totem/totem.SlackBuild
+++ b/gnome/totem/totem.SlackBuild
@@ -46,7 +46,7 @@ PKGF=${PKGF:-${TMP}/package-${NAME}}
 PKG=${PKG:-${PKGF}/${NAME}}
 PKG2=${PKG2:-${PKGF}/${NAME2}}
 
-VERSION=${VERSION:-2.26.2}
+VERSION=${VERSION:-2.26.3}
 SVER=$(echo ${VERSION} | cut -d . -f1-2)
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
@@ -78,12 +78,11 @@ SRCARCHIVE=${SRCDIR}.tar.bz2
 
 DL_TO=${DL_TO:-5}
 DL_OPTS=${DL_OPTS:-"--timeout=${DL_TO}"}
-DL_URL="http://ftp.gnome.org/pub/gnome/sources/${NAME}/${SVER}/${SRCARCHIVE}"
+GNOME_MIRROR=${GNOME_MIRROR:-http://ftp.gnome.org/pub/GNOME/sources}
+DL_URL="${GNOME_MIRROR}/${NAME}/${SVER}/${SRCARCHIVE}"
 
-# if source is not present, download in source rootdir if possible, or in /tmp
-if ! test -r ${SRCARCHIVE}; then
-  test -r ${CWD}/${SRCARCHIVE} || wget ${DL_OPTS} ${DL_URL} || exit 1
-fi
+# if source is not present, download in source rootdir if possible
+test -r ${CWD}/${SRCARCHIVE} || wget ${DL_OPTS} ${DL_URL} || exit 1
 
 if [ "${SB_NATIVE}" = "YES" ] ;then
   SLKCFLAGS="-O2 -march=native -mtune=native ${SB_ECFLAGS} -pipe"
@@ -97,20 +96,21 @@ else
                  ;;
   esac
 fi
-
-if [ -d ${PKGF} ]; then
-  # Clean up a previous build
-  rm -rf ${PKGF}
+if [ "${ARCH}" = "x86_64" ] ;then
+  LIBDIRSUFFIX="64"
+else
+  LIBDIRSUFFIX=""
 fi
-mkdir -p ${PKG} ${PKG2}
+
+if [ -d ${PKG} ]; then
+  # Clean up a previous build
+  rm -rf ${PKG}
+fi
+mkdir -p ${PKG}
 
 cd ${TMP}
 rm -rf ${SRCDIR}
-if $(file -L ${CWD}/${SRCARCHIVE} | grep -q ": bzip2"); then
-  tar -xjvf ${CWD}/${SRCARCHIVE} || exit 1
-elif $(file -L ${CWD}/${SRCARCHIVE} | grep -q ": gzip"); then
-  tar -xzvf ${CWD}/${SRCARCHIVE} || exit 1
-fi
+tar -xvf ${CWD}/${SRCARCHIVE} || exit 1
 cd ${SRCDIR} || exit 1
 
 # zcat ${CWD}/${NAME}.patch.gz | patch -p0 -E --backup --verbose || exit 1
@@ -118,13 +118,14 @@ zcat ${CWD}/${NAME}-use-pulsesink-volume.patch.gz | patch -p0 -E --backup --verb
 
 DBUS_FATAL_WARNINGS=0 /usr/bin/gst-inspect-0.10 --print-all &>/dev/null
 
-export MOZILLA_PLUGINDIR=/usr/lib/mozilla/plugins
+export MOZILLA_PLUGINDIR=/usr/lib${LIBDIRSUFFIX}/mozilla/plugins
 
 SB_CONFIGURE(){
 CFLAGS="${SLKCFLAGS}" \
 CXXFLAGS="${SLKCFLAGS}" \
 ./configure \
   --prefix=/usr \
+  --libdir=/usr/lib${LIBDIRSUFFIX} \
   --sysconfdir=/etc \
   --localstatedir=/var/lib \
   --infodir=/usr/info \
@@ -146,8 +147,8 @@ export GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1
 make install DESTDIR=${PKG} || exit 1
 
 # move the backend library away
-mv ${PKG}/usr/lib/libbaconvideowidget.so.0.0.0 \
-   ${PKG}/usr/lib/libbaconvideowidget-gstreamer.so.0.0.0 || exit 1
+mv ${PKG}/usr/lib${LIBDIRSUFFIX}/libbaconvideowidget.so.0.0.0 \
+   ${PKG}/usr/lib${LIBDIRSUFFIX}/libbaconvideowidget-gstreamer.so.0.0.0 || exit 1
 
 if [ "${SB_XINE}" = "YES" ] ;then
   make distclean
@@ -162,8 +163,8 @@ if [ "${SB_XINE}" = "YES" ] ;then
   make -j${NJOBS} || make || exit 1
   make install DESTDIR=${PKG} || exit 1
 
-mv ${PKG}/usr/lib/libbaconvideowidget.so.0.0.0 \
-   ${PKG}/usr/lib/libbaconvideowidget-xine.so.0.0.0 || exit 1
+mv ${PKG}/usr/lib${LIBDIRSUFFIX}/libbaconvideowidget.so.0.0.0 \
+   ${PKG}/usr/lib${LIBDIRSUFFIX}/libbaconvideowidget-xine.so.0.0.0 || exit 1
 
 fi
 
@@ -171,12 +172,12 @@ unset GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL
 
 # Restore the default backend
 ln -sf libbaconvideowidget-gstreamer.so.0.0.0 \
-       ${PKG}/usr/lib/libbaconvideowidget.so.0.0.0 || exit 1
+       ${PKG}/usr/lib${LIBDIRSUFFIX}/libbaconvideowidget.so.0.0.0 || exit 1
 
-rm -f ${PKG}/usr/lib/totem/plugins/*/*.{a,la} \
-      ${PKG}/usr/lib/mozilla/plugins/*.{a,la} \
-      ${PKG}/usr/lib/nautilus/extensions-2.0/*.{a,la} \
-      ${PKG}/usr/lib/libbaconvideowidget*.{a,la}
+rm -f ${PKG}/usr/lib*/totem/plugins/*/*.{a,la} \
+      ${PKG}/usr/lib*/mozilla/plugins/*.{a,la} \
+      ${PKG}/usr/lib*/nautilus/extensions-2.0/*.{a,la} \
+      ${PKG}/usr/lib*/libbaconvideowidget*.{a,la}
 
 zcat ${CWD}/${NAME}-bin-backend-ondemand.sh.gz > \
      ${PKG}/usr/bin/${NAME}-backend || exit 1
