ardour, dcraw, dnsmasq, enscript, exaile, fotoxx, gconfmm, gdm, gobject-introspection, imagemagick, libX11, libXext, libnemesi, linphone, lyx, mediastreaner, ortp, phoronix-test-suite, qmpdclient, qtcurve-qt4, scribus, sessreg, shell-fm, sudo, tracker, udev, vim, vim-gvim, virtualbox, whatmask, winetricks, xinput, xlsatoms, xlsclients

diff --git a/fonts/msttcorefonts/msttcorefonts.SlackBuild b/fonts/msttcorefonts/msttcorefonts.SlackBuild
--- a/fonts/msttcorefonts/msttcorefonts.SlackBuild
+++ b/fonts/msttcorefonts/msttcorefonts.SlackBuild
@@ -41,9 +41,9 @@ PNAME=corefonts
 NAME=msttcorefonts
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-3.0}
+VERSION=${VERSION:-3.1}
 ARCH=noarch
-BUILD=${BUILD:-2}
+BUILD=${BUILD:-1}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -60,20 +60,21 @@ echo "in the font package's document directory as 'eula.txt' or 'eula.htm'."
 read junk
 
 SRCDIR=${NAME}-${VERSION}
-SRCARCHIVE=PowerPointViewer.exe
+SRCARCHIVE2=PowerPointViewer.exe
+SRCARCHIVE3=tahoma32.exe
 
 DL_PROG=${DL_PROG:-wget}
 DL_TO=${DL_TO:-5}
-DL_URL="http://www.microsoft.com/downloads/details.aspx?familyid=048DC840-14E1-467D-8DCA-19D2A8FD7485&displaylang=en"
-# if source is not present, download in source rootdir if possible, or in /tmp
-if [ ! -r ${CWD}/${SRCARCHIVE} ;then 
-  echo "Download ${SRCARCHIVE} in ${DL_URL}" && exit 1
-fi
+SF_MIRROR=${SF_MIRROR:-http://prdownloads.sourceforge.net}
+DL_URL="${SF_MIRROR}/corefonts"
 
-# this is the sourceforge mirrorlist as of 2006-04-30. If someone spots changes
-# over at sourceforge, feel free to email me and I'll update the list
-mirrors="easynews+heanet+superb-west+internap+switch+ufpr+surfnet+umn+kent+mesh+superb-east+jaist"
-mirror_count=12
+DL_URL2="http://www.microsoft.com/downloads/details.aspx?familyid=048DC840-14E1-467D-8DCA-19D2A8FD7485&displaylang=en"
+DL_URL3="http://download.microsoft.com/download/office97pro/fonts/1/w95/en-us/${SRCARCHIVE3}"
+# if source is not present, download in source rootdir if possible, or in /tmp
+if [ ! -r ${CWD}/${SRCARCHIVE2} ] ;then 
+  echo "Download ${SRCARCHIVE2} in ${DL_URL2}" && exit 1
+fi
+test -r ${CWD}/${SRCARCHIVE3} || ${DL_PROG} ${DL_OPTS} ${DL_URL3} || exit 1
 
 andale32_md5="cbdc2fdd7d2ed0832795e86a8b9ee19a  andale32.exe"
 arial32_md5="9637df0e91703179f0723ec095a36cb5  arial32.exe"
@@ -86,26 +87,18 @@ times32_md5="ed39c8ef91b9fb80f76f702568291bd5  times32.exe"
 trebuc32_md5="0d7ea16cac6261f8513a061fbfcdb2b5  trebuc32.exe"
 webdin32_md5="230a1d13a365b22815f502eb24d9149b  webdin32.exe"
 verdan32_md5="12d2a75f8156e10607be1eaa8e8ef120  verdan32.exe"
-wd97vwr32_md5="efa72d3ed0120a07326ce02f051e9b42  wd97vwr32.exe"
+#wd97vwr32_md5="efa72d3ed0120a07326ce02f051e9b42  wd97vwr32.exe"
 
-download_files="andale32.exe arial32.exe arialb32.exe comic32.exe courie32.exe georgi32.exe impact32.exe times32.exe trebuc32.exe webdin32.exe verdan32.exe wd97vwr32.exe"
+download_files="andale32.exe arial32.exe arialb32.exe comic32.exe courie32.exe georgi32.exe impact32.exe times32.exe trebuc32.exe webdin32.exe verdan32.exe"
 
 failures=0
-
-function set_mirror {
-  local r m
-  r=$(expr $RANDOM % $mirror_count + 1)
-  m=$(echo $mirrors |cut -d+ -f$r)
-  mirror="http://${m}.dl.sourceforge.net/sourceforge/corefonts/"
-
-}
 
 function check_file {
   matches=
   if [ ! -r $1 ]
   then
     echo "$1 does not exist"
-    eturn
+    return
   fi
   local variable_name=$(basename $1 .exe)_md5
   local stored_checksum
@@ -121,33 +114,28 @@ function check_file {
 }
 
 function download {
-  wget --timeout=${DL_TO} -O "$2" ${1}${2}
+  wget ${DL_OPTS} -O "$1" ${DL_URL}/${1}
 }
 
-set_mirror
 for f in ${download_files}
 do
   check_file ${f}
   while [ ! ${matches} ]
   do
-    download ${mirror} ${f}
+    download ${f}
     check_file $f
     if [ ! ${matches} ]
     then
-      echo "failed to download ${mirror}${f}"
+      echo "failed to download ${DL_URL}/${f}"
       failures=$(expr $failures + 1)
       if [ ${failures} -gt 5 ]
       then
         echo "failed to download too many times."
         exit 1
       fi
-      set_mirror
     fi
   done
 done
-
-# Decompress fonts
-font_files="andale32.exe arial32.exe arialb32.exe comic32.exe courie32.exe georgi32.exe impact32.exe times32.exe trebuc32.exe webdin32.exe verdan32.exe"
 
 if [ -d ${PKG} ]; then
   # Clean up a previous build
@@ -160,7 +148,7 @@ rm -rf ${SRCDIR}
 mkdir -p ${SRCDIR}
 cd ${SRCDIR} || exit 1
 
-font_files="andale32.exe arial32.exe arialb32.exe comic32.exe courie32.exe georgi32.exe impact32.exe times32.exe trebuc32.exe webdin32.exe verdan32.exe"
+font_files="andale32.exe arial32.exe arialb32.exe comic32.exe courie32.exe georgi32.exe impact32.exe times32.exe trebuc32.exe webdin32.exe verdan32.exe ${SRCARCHIVE3}"
 
 mkdir cab-contents
 mkdir fonts
@@ -175,13 +163,13 @@ do
   rm -f cab-contents/*
 done || exit 1
 
-cabextract --lowercase --directory=cab-contents ${CWD}/wd97vwr32.exe || exit 1
-cabextract --lowercase --directory=cab-contents cab-contents/viewer1.cab || exit 1
-cp cab-contents/*.ttf fonts/ || exit 1
-rm -f cab-contents/*
+#cabextract --lowercase --directory=cab-contents ${CWD}/wd97vwr32.exe || exit 1
+#cabextract --lowercase --directory=cab-contents cab-contents/viewer1.cab || exit 1
+#cp cab-contents/*.ttf fonts/ || exit 1
+#rm -f cab-contents/*
 
-cabextract --lowercase -F eula.txt ${CWD}/${SRCARCHIVE} || exit 1
-cabextract --lowercase --directory=cab-contents -F ppviewer.cab ${CWD}/${SRCARCHIVE} || exit 1
+cabextract --lowercase -F eula.txt ${CWD}/${SRCARCHIVE2} || exit 1
+cabextract --lowercase --directory=cab-contents -F ppviewer.cab ${CWD}/${SRCARCHIVE2} || exit 1
 for i in cab-contents/*.cab ; do
   cabextract --lowercase --directory=cab-contents ${i} || exit 1
 done
@@ -215,7 +203,7 @@ cat > ${PKG}/install/doinst.sh <<EOF
 #!/bin/sh
 # Update the X font indexes:
 if [ -x /usr/bin/mkfontdir -o -x /usr/X11R6/bin/mkfontdir ]; then
-  ( cd ${TTFDIR}
+  ( cd /${TTFDIR#\/}
     mkfontscale .
     mkfontdir .
   )
