cclive, cegui, coreutils, enblend, ffmpeg, hplip, iotop, jhead, kde-telepathy, kernel-custom, libquvi-scripts, libvpx, manaplus, mplayer*, nss, pv, qx11grab, squid, tbb, wayland, weston, wine, xfce4-datetime-plugin

diff --git a/libreoffice/libreoffice.SlackBuild b/libreoffice/libreoffice.SlackBuild
--- a/libreoffice/libreoffice.SlackBuild
+++ b/libreoffice/libreoffice.SlackBuild
@@ -54,7 +54,7 @@ else
   ARCH=x86
   PARCH="x86"
 fi
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -70,7 +70,7 @@ SB_CAIRO=${SB_CAIRO:-YES}
 # Set to YES to use system nspr/nss
 SB_NSS=${SB_NSS:-YES}
 # Set to YES to use system python
-SB_PY=${SB_PY:-YES}
+SB_PY=${SB_PY:-NO}
 # Set to YES to use system libxml2
 SB_XML=${SB_XML:-NO}
 
@@ -80,7 +80,7 @@ SB_XML=${SB_XML:-NO}
 # According to Fred Emmott, this is *highly* desirable on 64 bit systems
 SB_JAVA=${SB_JAVA:-NO}
 
-PYABI=$(python -c 'import sys; sys.stdout.write(sys.version[:3])')
+PYABI=$(python3 -c 'import sys; sys.stdout.write(sys.version[:3])')
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
@@ -152,34 +152,62 @@ rm -f ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/share/fonts/truetype/{DejaVu,Gen,Lib
 find ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME} \
   | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs chmod 755 2> /dev/null
 
+xtcsoname(){
+  objdump -p "${1}" | grep SONAME | awk '{print $2}'
+}
+
+missing(){
+  if ! [ -e "$1" ] ;then
+    echo "File $1 is missing!"
+    exit 5
+  fi
+}
+
 if [ "${SB_GCC}" = "YES" ] ; then
   ( cd ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/ure/lib
-    rm -f libgcc_s.so.*
-    rm -f libstdc++.so.*
-  )
+    for file in libgcc_s.so* libstdc++.so* ;do
+      SONAME=$(xtcsoname ${file})
+      missing /usr/lib${LIBDIRSUFFIX}/${SONAME}
+      rm -fv ${file}
+    done
+  ) || exit $?
 fi
 if [ "${SB_CAIRO}" = "YES" ] ; then
   ( cd ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/program || exit 1
-    rm -f libpixman-*.so.*
-    rm -f libcairo.so.*
-  )
+    for file in libpixman-*.so* libcairo.so* ;do
+      SONAME=$(xtcsoname ${file})
+      missing /usr/lib${LIBDIRSUFFIX}/${SONAME}
+      rm -fv ${file}
+    done
+  ) || exit $?
 fi
 
 if [ "${SB_NSS}" = "YES" ] ; then
   ( cd ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/program || exit 1
-    rm -f libnspr4.so libnspr4.so libplc4.so libplds4.so
-    rm -f libnss3.so libnssckbi.so libnssdbm3.so libnssutil3.so
-    rm -f libfreebl3.so libsoftokn3.so libssl3.so libsmime3.so
-  )
+    for file in \
+      libnspr4.so libnspr4.so libplc4.so libplds4.so \
+      libnss3.so libnssckbi.so libnssdbm3.so libnssutil3.so \
+      libfreebl3.so libsoftokn3.so libssl3.so libsmime3.so
+    do
+      missing /usr/lib${LIBDIRSUFFIX}/${file}
+      rm -fv ${file}
+    done
+  ) || exit $?
 fi
+
+abs2rel(){
+  perl -e 'use File::Spec; print File::Spec->abs2rel($ARGV[0], $ARGV[1])' "$1" "$2"
+}
+
 if [ "${SB_PY}" = "YES" ] ; then
   ( cd ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/program || exit 1
     LPYVER=$(echo python-core-* | cut -d- -f3 )
-    LPYABI=$(echo ${LPYVER} | cut -d. -f1-2)
-    if [ "${PYABI//.}" -eq "26" ] &&  [ "${PYABI//.}" -lt "30" ] ;then
-      ln -sf /usr/bin/python${PYABI} \
-        ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/program/python 
-      rm -rf python.bin libpython${LPYABI}.so.* python-core-${LPYVER}
+    LPYABI=$(echo ${LPYVER} | cut -d. -f1-2)m
+    if [ "${PYABI//.}" -eq "33" ] &&  [ "${PYABI//.}" -lt "34" ] && [ -x /usr/bin/python${PYABI}m ] ;then
+      reldir=$(abs2rel /usr/bin /usr/lib${LIBDIRSUFFIX}/${NAME}/program)
+      ln -sf ${reldir}/python${PYABI}m \
+        ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/program/python
+      rm -rf python.bin libpython*.so* python-core-${LPYVER}
       sed -i \
         -e "/^PYUNO_LOADER_PYTHONHOME=/s|\$ORIGIN/python-core-${LPYVER}|/usr|g" \
         -e "/^PYUNO_LOADER_PYTHONPATH=/s|\$ORIGIN/python-core-${LPYVER}/lib|/usr/lib${LIBDIRSUFFIX}/python${PYABI}|g" \
@@ -189,11 +217,19 @@ if [ "${SB_PY}" = "YES" ] ; then
 fi
 if [ "${SB_XML}" = "YES" ] ; then
   ( cd ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/ure/lib
-    rm -f libxml2.so.*
-  )
+    for file in libxml2.so* ;do
+      SONAME=$(xtcsoname ${file})
+      missing /usr/lib${LIBDIRSUFFIX}/${SONAME}
+      rm -fv ${file}
+    done
+  ) || exit $?
   ( cd ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/program
-    rm -f libxslt.so.*
-  )
+    for file in libxslt.so* ;do
+      SONAME=$(xtcsoname ${file})
+      missing /usr/lib${LIBDIRSUFFIX}/${SONAME}
+      rm -fv ${file}
+    done
+  ) || exit $?
 fi
 
 rm -f ${PKG}/usr/bin/* || exit 1
@@ -277,7 +313,9 @@ SB_DFI \
   ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/share/xdg/calc.desktop || exit 1
 
 SB_DFI \
-  --remove-category="-MandrivaLinux-Office-Drawing" \
+  --remove-category="Office" \
+  --remove-category="Flowchart" \
+  --remove-category="X-MandrivaLinux-Office-Drawing" \
   ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/share/xdg/draw.desktop || exit 1
 
 SB_DFI \
