autogen, billiards, bind, bison, dhcp, digikam, dotnew, firefox, fluxbox-chinfo-menu, gnutls, kernel-custom, libatasmart, libbsd, mozilla-firetray, pdf2djvu, plplot, postgresql, systemd, techne, transset-df-> transset, xulrunner

diff --git a/fluxbox-chinfo-menu/fluxbox-chinfo-menu/bin/fluxbox-chinfo-menu b/fluxbox-chinfo-menu/fluxbox-chinfo-menu/bin/fluxbox-chinfo-menu
--- a/fluxbox-chinfo-menu/fluxbox-chinfo-menu/bin/fluxbox-chinfo-menu
+++ b/fluxbox-chinfo-menu/fluxbox-chinfo-menu/bin/fluxbox-chinfo-menu
@@ -4,7 +4,7 @@
 # Menu script by Phantom X <megaphantomx@bol.com.br>
 # Suggested usage: $ fluxbox-chinfo-menu -a
 #--
-# Copyright 2010 Phantom X, Goiania, Brazil.
+# Copyright 2010-2012 Phantom X, Goiania, Brazil.
 # Portions of code based on perl script by Arnaud Abélard <arny@arny.org>
 # Backgrounds menu code adapted from fluxbox-generate_menu by:
 # Dung N. Lam <dnlam@users.sourceforge.net> and Han Boetes <han@mijncomputer.nl>
@@ -23,6 +23,21 @@
 #       along with this program; if not, write to the Free Software
 #       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 #       MA 02110-1301, USA.
+
+# Translations only work with utf8 locales
+if [ ! $(echo ${LANG} | grep -i \\.utf8) ] && [ ! $(echo ${LANG} | grep -i \\.utf-8) ]; then
+  LANG=C
+fi
+
+# For gettext internationalization
+export TEXTDOMAIN="fluxbox-chinfo-menu"
+export TEXTDOMAINDIR="/usr/share/locale"
+if [ -x /usr/bin/gettext.sh ] ;then
+  . /usr/bin/gettext.sh
+else
+  echo "Missing /usr/bin/gettext.sh"
+  exit 1
+fi
 
 tmp=$(mktemp -d)
 
@@ -53,15 +68,7 @@ FB_USERMENU="${FB_USERDIR}/${FB_USERMENUNAME}"
 FB_BGMENU="${FB_USERDIR}/${FB_BGMENUNAME}"
 FB_BACKGROUND_DIRS="${FB_USERDIR}/backgrounds/:/usr/share/fluxbox/backgrounds/"
 
-unset FB_MENUTITLE FB_TERM FB_FILE FB_BROWSER FB_MAIL FB_LANG
-
-[ "${LANG}" ] && FB_LANG="$(echo ${LANG} | cut -d. -f1)"
-
-if [ -r "${FB_CHINFO_FILES}/fluxbox-chinfo-${FB_LANG}" ] ;then
-  source "${FB_CHINFO_FILES}/fluxbox-chinfo-${FB_LANG}"
-else
-  source "${FB_CHINFO_FILES}/fluxbox-chinfo-en"
-fi
+unset FB_MENUTITLE FB_TERM FB_FILE FB_BROWSER FB_MAIL
 
 mkdir -p "${FB_USERDIR}"
 
@@ -73,18 +80,19 @@ else
   source "${FB_CHINFO_USERCONFIG}"
 fi
 
-txt() {
-  cat <<EOF
-${FBI_USAGE} : $0 <${FBI_OPT}>
-<${FBI_OPT}> ${FBI_OPTC}:
-  -a|--all         ${FBI_TA}
-  -b|--bgmenu      ${FBI_TB}
-  -m|--mainmenu    ${FBI_TM}
-  -s|--submenu     ${FBI_TS}
-  -h|--help        ${FBI_TH}
+fcmcommand="$0"
 
-${FBI_TI} ${FB_CHINFO_USERCONFIG}.
-EOF
+txt() {
+eval_gettext 'Usage : ${fcmcommand} <parameter>
+<parameter> can be:
+  -a|--all         Generate all menus
+  -b|--bgmenu      Generate only background menu
+  -m|--mainmenu    Generate only main menu
+  -s|--submenu     Generate only sub menus
+  -h|--help        This message
+
+Run without any parameters to only generate ${FB_CHINFO_USERCONFIG}.'
+echo
 }
 
 # Remove unwanted strings on desktop Exec commands
@@ -99,7 +107,7 @@ submenu(){
   # KDE xdg menu
   if [ "${FB_SUBMENU1NAME}" != "none" ] && [ -d /etc/kde/xdg/menus ] ;then
     [ -f "${FB_SUBMENU1}" ] && mv -f "${FB_SUBMENU1}" "${FB_SUBMENU1}.old"
-    echo "${FBI_GENING} ${FB_SUBMENU1}..."
+    eval_gettext 'Generating ${FB_SUBMENU1}...' ;echo
     export XDG_CONFIG_DIRS=/etc/kde/xdg:/etc/xdg
     if [ -f /etc/kde/xdg/menus/kde4-applications.menu ] ;then
       export XDG_MENU_PREFIX="kde4-"
@@ -117,7 +125,7 @@ submenu(){
   # GNOME xdg menu
   if [ "${FB_SUBMENU2NAME}" != "none" ] && [ -d /etc/gnome/xdg/menus ] ;then
     [ -f "${FB_SUBMENU2}" ] && cp -f "${FB_SUBMENU2}" "${FB_SUBMENU2}.old"
-    echo "${FBI_GENING} ${FB_SUBMENU2}..."
+    eval_gettext 'Generating ${FB_SUBMENU2}...' ; echo
     export XDG_CONFIG_DIRS=/etc/gnome/xdg:/etc/xdg
     [ -f /etc/gnome/xdg/menus/gnome-applications.menu ] && export XDG_MENU_PREFIX="gnome-"
     /usr/bin/python "${FB_CHINFO_XDG}" > "${tmp}/${FB_SUBMENU2NAME}" || exit 1
@@ -129,7 +137,7 @@ submenu(){
   # LXDE xdg menu
   if [ "${FB_SUBMENU2NAME}" != "none" ] && [ -f /etc/xdg/menus/lxde-applications.menu ] ;then
     [ -f "${FB_SUBMENU3}" ] && cp -f "${FB_SUBMENU3}" "${FB_SUBMENU3}.old"
-    echo "${FBI_GENING} ${FB_SUBMENU3}..."
+    eval_gettext 'Generating ${FB_SUBMENU3}...' ;echo
     export XDG_CONFIG_DIRS="/etc/xdg"
     export XDG_MENU_PREFIX="lxde-"
     /usr/bin/python "${FB_CHINFO_XDG}" > "${tmp}/${FB_SUBMENU3NAME}" || exit 1
@@ -164,13 +172,13 @@ addbackground(){
 bgmenu(){
   [ "${FB_BGMENU}" = "none" ] && return 1
   [ -f "${FB_BGMENU}" ] && mv -f "${FB_BGMENU}" "${FB_BGMENU}.old"
-  echo "${FBI_GENING} ${FB_BGMENU}..."
+  eval_gettext 'Generating ${FB_BGMENU}...';echo
   FB_BGMENU_TMP="${tmp}/${FB_BGMENUNAME}"
   IFS=: # set delimetor for find
   NUMBER_OF_BACKGROUNDS=$(find ${FB_BACKGROUND_DIRS} -follow -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.xpm' -o -iname '*.bmp' -o -name '*.gif' -o -iname '*.tiff' \) 2> /dev/null|wc -l)
   if [ "${NUMBER_OF_BACKGROUNDS}" -gt 0 ]; then
-    echo "	[submenu] (${FBI_BGMENU}) {${FBI_BGMENUTITLE}}" >> "${FB_BGMENU_TMP}"
-    echo "		[exec] (${FBI_RANDOMBG}) {fbsetbg -r ${USERFLUXDIR}/backgrounds}" >> "${FB_BGMENU_TMP}"
+    echo "	[submenu] ($(eval_gettext 'Backgrounds')) {$(eval_gettext 'Set the Background')}" >> "${FB_BGMENU_TMP}"
+    echo "		[exec] ($(eval_gettext 'Random Background')) {fbsetbg -r ${USERFLUXDIR}/backgrounds}" >> "${FB_BGMENU_TMP}"
     if [ "${NUMBER_OF_BACKGROUNDS}" -gt 30 ]; then
       menucounter=1 ; counter=1
       if [ "$(echo -n ${menucounter} | wc -c)" -eq 1 ] ;then
@@ -179,7 +187,7 @@ bgmenu(){
       else
         rmenucounter=${menucounter}
       fi
-      echo "		[submenu] (${FBI_BGMENU}${rmenucounter}) {${FBI_BGMENUTITLE}}" >> "${FB_BGMENU_TMP}"
+      echo "		[submenu] ($(eval_gettext 'Backgrounds ${rmenucounter}')) {$(eval_gettext 'Set the Background')}" >> "${FB_BGMENU_TMP}"
       find ${FB_BACKGROUND_DIRS} -follow -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.xpm' -o -iname '*.bmp' -o -name '*.gif' -o -iname '*.tiff' \) 2> /dev/null | sort | while read i; do
         counter=$(expr $counter + 1)
         if [ ${counter} -eq 30 ]; then
@@ -192,7 +200,7 @@ bgmenu(){
             rmenucounter=${menucounter}
           fi
           echo '		[end]' >> "${FB_BGMENU_TMP}"
-          echo "		[submenu] (${BACKGROUNDMENU}${rmenucounter}) {${FBI_BGMENUTITLE}}" >> "${FB_BGMENU_TMP}"
+          echo "		[submenu] (${BACKGROUNDMENU}${rmenucounter}) {$(eval_gettext 'Set the Background')}" >> "${FB_BGMENU_TMP}"
         fi
         addbackground "$i"
       done
@@ -205,22 +213,22 @@ bgmenu(){
     echo '	[end]' >> "${FB_BGMENU_TMP}"
     cp -f "${FB_BGMENU_TMP}" "${FB_BGMENU}"
   else
-    echo "${FBI_BGWARN}:
-    ${FB_BACKGROUND_DIRS}" >&2
+    eval_gettext 'Warning: None background found in:' ;echo
+    echo "${FB_BACKGROUND_DIRS}" >&2
   fi
 }
 
 mainmenu(){
   [ -f "${FB_MAINMENU}" ] && cp -f "${FB_MAINMENU}" "${FB_MAINMENU}.old"
-  echo "${FBI_GENING} ${FB_MAINMENU}..."
+  eval_gettext 'Generating ${FB_MAINMENU}...' ; echo
 
   FB_MAINMENU_TMP="${tmp}/${FB_MAINMENUNAME}"
 
   echo "[begin] (${FB_MENUTITLE})" > "${FB_MAINMENU_TMP}"
-  [ "${FB_TERM}" ] && find_exec "" "${FBI_TERM}" "${FB_TERM}"
-  [ "${FB_FILE}" ] && find_exec "" "${FBI_FILE}" "${FB_FILE}"
-  [ "${FB_BROWSER}" ] && find_exec "" "${FBI_BROWSER}" "${FB_BROWSER}"
-  [ "${FB_MAIL}" ] && find_exec "" "${FBI_MAIL}" "${FB_MAIL}"
+  [ "${FB_TERM}" ] && find_exec "" "$(eval_gettext 'Terminal')" "${FB_TERM}"
+  [ "${FB_FILE}" ] && find_exec "" "$(eval_gettext 'File Manager')" "${FB_FILE}"
+  [ "${FB_BROWSER}" ] && find_exec "" "$(eval_gettext 'Web Browser')" "${FB_BROWSER}"
+  [ "${FB_MAIL}" ] && find_exec "" "$(eval_gettext 'Email Reader')" "${FB_MAIL}"
   echo '[separator]' >> "${FB_MAINMENU_TMP}"
   [ -f "${FB_SUBMENU1}" ] && echo "	[include] (${FB_SUBMENU1})" >> "${FB_MAINMENU_TMP}"
   [ -f "${FB_SUBMENU2}" ] && echo "	[include] (${FB_SUBMENU2})" >> "${FB_MAINMENU_TMP}"
@@ -231,43 +239,43 @@ mainmenu(){
     echo "[separator]" >> "${FB_MAINMENU_TMP}"
   fi
   cat >> "${FB_MAINMENU_TMP}" <<EOF
-[submenu] (${FBI_SETTINGSMENU})
-	[config] (${FBI_CONFIGURE})
-	[submenu] (${FBI_SYSTEMSTYLES}) {${FBI_STYLEMENUTITLE}}
+[submenu] ("$(eval_gettext 'Fluxbox Menu')")
+	[config] ("$(eval_gettext 'Configure')")
+	[submenu] ("$(eval_gettext 'System Styles')") {"$(eval_gettext 'Choose a style...')"}
 		[stylesdir] (/usr/share/fluxbox/styles)
 	[end]
-	[submenu] (${FBI_USERSTYLES}) {${FBI_STYLEMENUTITLE}}
+	[submenu] ("$(eval_gettext 'User Styles')") {"$(eval_gettext 'Choose a style...')"}
 		[stylesdir] (~/.fluxbox/styles)
 	[end]
 EOF
 
  [ -f "${FB_BGMENU}" ] && echo "	[include] (${FB_BGMENU})" >> "${FB_MAINMENU_TMP}"
-  echo "	[workspaces] (${FBI_WORKSPACEMENU})" >> "${FB_MAINMENU_TMP}"
-  echo "	[submenu] (${FBI_TOOLS})" >> "${FB_MAINMENU_TMP}"
+  echo "	[workspaces] ($(eval_gettext 'Workspace List'))" >> "${FB_MAINMENU_TMP}"
+  echo "	[submenu] ($(eval_gettext 'Tools'))" >> "${FB_MAINMENU_TMP}"
   find_exec "		" "Fluxconf" "fluxconf"
   find_exec "		" "Fluxkeys" "fluxkeys"
   find_exec "		" "Fluxmenu" "fluxmenu"
-  find_exec "		" "${FBI_GTKSTYLE}" "lxappearance"
+  find_exec "		" "$(eval_gettext 'GTK+ appearence')" "lxappearance"
   if which "zenity" &>/dev/null ;then
-    find_exec "		" "${FBI_WINDOWNAME}" "zenity --info --text=\"\$(xprop WM_CLASS|cut -d \\\" -f 2)\" --title=\"${FBI_WINDOWNAME}\""
-    find_exec "		" "${FBI_WINDOWINFO}" "zenity --info --text=\"\$(xwininfo)\" --title=\"${FBI_WINDOWINFO}\""
+    find_exec "		" "$(eval_gettext 'Window name')" "zenity --info --text=\"\$(xprop WM_CLASS|cut -d \\\" -f 2)\" --title=\"$(eval_gettext 'Window name')\""
+    find_exec "		" "$(eval_gettext 'Window info')" "zenity --info --text=\"\$(xwininfo)\" --title=\"$(eval_gettext 'Window info')\""
   elif which "Xdialog" &>/dev/null ;then
-    find_exec "		" "${FBI_WINDOWNAME}" "Xdialog --title \"${FBI_WINDOWNAME}\" --infobox \"\$(xprop WM_CLASS|cut -d \\\" -f 2)\" 5 20 0"
-    find_exec "		" "${FBI_WINDOWINFO}" "Xdialog --title \"${FBI_WINDOWINFO}\" --infobox \"\$(xwininfo)\" 40 100 0"
+    find_exec "		" "$(eval_gettext 'Window name')" "Xdialog --title \"$(eval_gettext 'Window name')\" --infobox \"\$(xprop WM_CLASS|cut -d \\\" -f 2)\" 5 20 0"
+    find_exec "		" "$(eval_gettext 'Window info')" "Xdialog --title \"$(eval_gettext 'Window info')\" --infobox \"\$(xwininfo)\" 40 100 0"
   elif which "xmessage" &>/dev/null ;then
-    find_exec "		" "${FBI_WINDOWNAME}" "xprop WM_CLASS|cut -d \\\" -f 2 | xmessage -file - -center"
-    find_exec "		" "${FBI_WINDOWINFO}" "xwininfo | xmessage -file - -center"
+    find_exec "		" "$(eval_gettext 'Window name')" "xprop WM_CLASS|cut -d \\\" -f 2 | xmessage -file - -center"
+    find_exec "		" "$(eval_gettext 'Window info')" "xwininfo | xmessage -file - -center"
   fi
-  find_exec "		" "${FBI_SCREENSHOT}" "import \${TMP}/fluxbox-screenshot-$(whoami).png && display -resize 50% \${TMP}/fluxbox-screenshot-$(whoami).png"
+  find_exec "		" "$(eval_gettext 'Screenshot')" "import \${TMP}/fluxbox-screenshot-$(whoami).png && display -resize 50% \${TMP}/fluxbox-screenshot-$(whoami).png"
    cat >> "${FB_MAINMENU_TMP}" <<EOF
-		[submenu] (${FBI_REGEN_MENU})
-			[exec] (${FBI_REGEN_AMENU}) {fluxbox-chinfo-menu -a}
-			[exec] (${FBI_REGEN_MMENU}) {fluxbox-chinfo-menu -m}
-			[exec] (${FBI_REGEN_SMENU}) {fluxbox-chinfo-menu -s}
-			[exec] (${FBI_REGEN_BMENU}) {fluxbox-chinfo-menu -b}
+		[submenu] ($(eval_gettext 'Regenerate menus'))
+			[exec] ($(eval_gettext 'All')) {fluxbox-chinfo-menu -a}
+			[exec] ($(eval_gettext 'Only main menu')) {fluxbox-chinfo-menu -m}
+			[exec] ($(eval_gettext 'Only submenus')) {fluxbox-chinfo-menu -s}
+			[exec] ($(eval_gettext 'Only backgrounds menu')) {fluxbox-chinfo-menu -b}
 		[end]
 	[end]
-	[submenu] (${FBI_WINDOWMANAGERS})
+	[submenu] ($(eval_gettext 'Window Managers'))
 EOF
 
   for wm in beryl blackbox compiz enlightenment evilwm fvwm fvwm2 icewm ion metacity mwm openbox pekwm sawfish twm waimea wmaker wmii ; do
@@ -280,36 +288,36 @@ EOF
 
 cat >> "${FB_MAINMENU_TMP}" <<EOF
 	[end]
-	[commanddialog] (${FBI_FLUXBOXCOMMAND})
+	[commanddialog] ($(eval_gettext 'Fluxbox Command'))
 	[separator]
-	[reconfig] (${FBI_RELOADITEM})
-	[restart] (${FBI_RESTARTITEM})
+	[reconfig] ($(eval_gettext 'Reload config'))
+	[restart] ($(eval_gettext 'Restart Fluxbox'))
 [end]
 [separator]
 EOF
 
-  find_exec "" "${FBI_RUNCOMM}" "fbrun -title '${FBI_RUNCOMM}' ${FB_FBRUNOPTIONS}"
+  find_exec "" "$(eval_gettext 'Run...')" "fbrun -title '$(eval_gettext 'Run...')' ${FB_FBRUNOPTIONS}"
   echo "[separator]" >> "${FB_MAINMENU_TMP}"
   if which "kfind" &>/dev/null || which "khelpcenter" &>/dev/null \
     || which "gnome-search-tool" &>/dev/null || which "yelp" &>/dev/null ;then
-    echo "	[submenu] (${FBI_HELPSEARCH})" >> "${FB_MAINMENU_TMP}"
-    find_exec "		" "[KDE] ${FBI_SEARCH}" "kfind"
-    find_exec "		" "[KDE] ${FBI_HELP}" "khelpcenter"
-    find_exec "		" "[GNOME] ${FBI_SEARCH}" "gnome-search-tool"
-    find_exec "		" "[GNOME] ${FBI_HELP}" "yelp"
+    echo "	[submenu] ($(eval_gettext 'Help & Search'))" >> "${FB_MAINMENU_TMP}"
+    find_exec "		" "[KDE] $(eval_gettext 'Search for files...')" "kfind"
+    find_exec "		" "[KDE] $(eval_gettext 'Help')" "khelpcenter"
+    find_exec "		" "[GNOME] $(eval_gettext 'Search for files...')" "gnome-search-tool"
+    find_exec "		" "[GNOME] $(eval_gettext 'Help')" "yelp"
     echo "	[end]" >> "${FB_MAINMENU_TMP}"
     echo "[separator]" >> "${FB_MAINMENU_TMP}"
   fi
-  find_exec "" "${FBI_DISPLAYCOMMAND}" "fluxbox-dm-helper --new"
+  find_exec "" "$(eval_gettext 'Open New Session')" "fluxbox-dm-helper --new"
   echo "[separator]" >> "${FB_MAINMENU_TMP}"
   
-  find_exec "" "${FBI_LOCKSCREEN} [xlock]" "xlock"
-  find_exec "" "${FBI_LOCKSCREEN} [xscreensaver]" "xscreensaver-command -lock"
+  find_exec "" "$(eval_gettext 'Lock screen') [xlock]" "xlock"
+  find_exec "" "$(eval_gettext 'Lock screen') [xscreensaver]" "xscreensaver-command -lock"
   echo "[separator]" >> "${FB_MAINMENU_TMP}"
-  echo "[exit] (${FBI_EXITITEM})" >> "${FB_MAINMENU_TMP}"
+  echo "[exit] ($(eval_gettext 'Logout'))" >> "${FB_MAINMENU_TMP}"
   echo "[separator]" >> "${FB_MAINMENU_TMP}"
-  find_exec  "" "${FBI_REBOOTITEM}" "fluxbox-dm-helper --fluxbox --reboot"
-  find_exec  "" "${FBI_SHUTDITEM}" "fluxbox-dm-helper --fluxbox --shutdown"
+  find_exec  "" "$(eval_gettext 'Reboot')" "fluxbox-dm-helper --fluxbox --reboot"
+  find_exec  "" "$(eval_gettext 'Shutdown')" "fluxbox-dm-helper --fluxbox --shutdown"
   echo "[end]" >> "${FB_MAINMENU_TMP}"
   cp -f "${FB_MAINMENU_TMP}" "${FB_MAINMENU}"
 }
diff --git a/fluxbox-chinfo-menu/fluxbox-chinfo-menu/bin/fluxbox-dm-helper b/fluxbox-chinfo-menu/fluxbox-chinfo-menu/bin/fluxbox-dm-helper
--- a/fluxbox-chinfo-menu/fluxbox-chinfo-menu/bin/fluxbox-dm-helper
+++ b/fluxbox-chinfo-menu/fluxbox-chinfo-menu/bin/fluxbox-dm-helper
@@ -2,7 +2,7 @@
 #-- Helper script for partial desktop managers with fluxbox--
 # Build script by Phantom X <megaphantomx@bol.com.br>
 #--
-# Copyright 2008 Phantom X, Goiania, Brazil.
+# Copyright 2008-2012 Phantom X, Goiania, Brazil.
 #
 # Redistribution and use of this script, with or without modification, is
 # permitted provided that the following conditions are met:
@@ -21,8 +21,23 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+# Translations only work with utf8 locales
+if [ ! $(echo ${LANG} | grep -i \\.utf8) ] && [ ! $(echo ${LANG} | grep -i \\.utf-8) ]; then
+  LANG=C
+fi
+
+# For gettext internationalization
+export TEXTDOMAIN="fluxbox-chinfo-menu"
+export TEXTDOMAINDIR="/usr/share/locale"
+if [ -x /usr/bin/gettext.sh ] ;then
+  . /usr/bin/gettext.sh
+else
+  echo "Missing /usr/bin/gettext.sh"
+  exit 1
+fi
+
 if [ -z "${DISPLAY}" ] ; then
-  echo "This script needs a working display." || exit 1
+  eval_gettext "This script needs a working display." ;echo || exit 1
 fi
 
 KDMCTLBIN=/usr/bin/kdmctl
@@ -38,22 +53,24 @@ KDESUBIN=/usr/bin/kdesu
 
 unset FLUXEXIT
 
+fdhcommand="$0"
+
 txt() {
-cat <<EOF
-Script for control GDM/KDM in menus. 
-Uso : $0 <option>
+eval_gettext 'Script to control GDM/KDM in menus.
+Usage : ${fdhcommand} <option>
 f|-f|--fluxbox     Exits fluxbox after some options.
 n|-n|--new         Open a reserved display
 r|-r|--reboot      Reboot
 s|-s|--shutdown    Shutdown
 h|-h|--help        This message
 
-Reboot/Shutdown options execute xterm with su, if no gdm/kdm found.
-EOF
+Reboot/Shutdown options execute xterm with su, if no gdm/kdm found.'
+echo
 }
 
 errortxt() {
-  ETEXT="GDM/KDM/$(basename ${XTERMBIN}) is not properly installed."
+  XTERMBASE="$(basename ${XTERMBIN})"
+  EMSG="$(eval_gettext 'GDM/KDM/${XTERMBASE} is not properly installed.')"
   if [ "${KDE_FULL_SESSION}" = "true" ] && [ -x "${KDIALOGBIN}" ] ; then
     "${KDIALOGBIN}" --sorry "${ETEXT}"
   elif [ -x "${ZENITYBIN}" ] ;then
@@ -61,12 +78,13 @@ errortxt() {
   elif [ -x "${XMESSAGEBIN}" ] ;then
     "${XMESSAGEBIN}" -default okay -center "${ETEXT}"
   else
-    echo "${ETEXT}"
+    echo "${EMSG}"
   fi
   exit 1
 }
 
 rebootopt() {
+  REBOOTMSG="$(eval_gettext 'Insert root password to reboot:')"
   if [ -x "${KDMCTLBIN}" ] && [ "$(kdmctl caps | grep ok)" ] && [ "$(kdmctl caps | grep 'shutdown ask')" ] ;then
     "${KDMCTLBIN}" shutdown reboot ask &>/dev/null
     [ "${FLUXEXIT}" = "1" ] && fluxbox-remote exit
@@ -76,15 +94,16 @@ rebootopt() {
   elif [ "${KDE_FULL_SESSION}" = "true" ] && [ -x "${KDESUBIN}" ] ; then
     "${KDESUBIN}" "${SHUTCOM} -t 5 -r now"
   elif [ -x "${GKSUBIN}" ] ;then
-    "${GKSUBIN}" -m 'Insert root password to reboot' "${SHUTCOM} -t 5 -r now"
+    "${GKSUBIN}" -m "${REBOOTMSG}" "${SHUTCOM} -t 5 -r now"
   elif [ -x "${XTERMBIN}" ] ;then
-    "${XTERMBIN}" -geometry 50x2 -e "echo 'Insert root password to reboot:' && su -c \"${SHUTCOM} -t 5 -r now\""
+    "${XTERMBIN}" -geometry 50x2 -e "echo \"${REBOOTMSG}\" && su -c \"${SHUTCOM} -t 5 -r now\""
   else
     errortxt
   fi
 }
 
 haltopt() {
+  HALTMSG="$(eval_gettext 'Insert root password to shutdown:')"
   if [ -x "${KDMCTLBIN}" ] && [ "$(kdmctl caps | grep ok)" ] && [ "$(kdmctl caps | grep 'shutdown ask')" ] ;then
     "${KDMCTLBIN}" shutdown halt ask &>/dev/null 
     [ "${FLUXEXIT}" = "1" ] && fluxbox-remote exit
@@ -94,16 +113,16 @@ haltopt() {
   elif [ "${KDE_FULL_SESSION}" = "true" ] && [ -x "${KDESUBIN}" ] ; then
     "${KDESUBIN}" "${SHUTCOM} -t 5 -h now"
   elif [ -x "${GKSUBIN}" ] ;then
-    "${GKSUBIN}" -m 'Insert root password to shutdown:' "${SHUTCOM} -t 5 -h now"
+    "${GKSUBIN}" -m "${HALTMSG}" "${SHUTCOM} -t 5 -h now"
   elif [ -x "${XTERMBIN}" ] ;then
-    "${XTERMBIN}" -geometry 50x2 -e "echo 'Insert root password to shutdown:' && su -c \"${SHUTCOM} -t 5 -h now\""
+    "${XTERMBIN}" -geometry 50x2 -e "echo \"${HALTMSG}\" && su -c \"${SHUTCOM} -t 5 -h now\""
   else
     errortxt
   fi
 }
 
 reserveopt() {
-  RESTEXT="GDM/KDM do not running or do not have reserved displays configured."
+  RESMSG="$(eval_gettext 'GDM/KDM do not running or do not have reserved displays configured.')"
   if [ "$(kdmctl caps | grep ok)" ] ;then
     "${KDMCTLBIN}" reserve &>/dev/null
   elif ps -C gdm &>/dev/null && [ -x "${GDMFLEXIBIN}" ] ;then
@@ -115,7 +134,7 @@ reserveopt() {
   elif [ -x "${XMESSAGEBIN}" ] ;then
     "${XMESSAGEBIN}" -default okay -center "${RESTEXT}"
   else
-    echo "${RESTEXT}"
+    echo "${RESMSG}"
   fi
 }
 
diff --git a/postgresql/postgresql-setup b/postgresql/postgresql-setup
--- a/postgresql/postgresql-setup
+++ b/postgresql/postgresql-setup
@@ -17,20 +17,27 @@ then
     SERVICE_NAME=postgresql
 fi
 
-if [ -f "/etc/systemd/system/${SERVICE_NAME}.service" ]
+# this parsing technique fails for PGDATA pathnames containing spaces,
+# but there's not much I can do about it given systemctl's output format...
+PGDATA=`systemctl show -p Environment "${SERVICE_NAME}.service" |
+  sed 's/^Environment=//' | tr ' ' '\n' |
+  sed -n 's/^PGDATA=//p' | tail -n 1`
+
+if [ x"$PGDATA" = x ]
 then
-    SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
-elif [ -f "/lib/systemd/system/${SERVICE_NAME}.service" ]
-then
-    SERVICE_FILE="/lib/systemd/system/${SERVICE_NAME}.service"
-else
-    echo "Could not find systemd unit file ${SERVICE_NAME}.service"
+    echo "failed to find PGDATA setting in ${SERVICE_NAME}.service"
     exit 1
 fi
 
-# Get port number and data directory from the service file
-PGPORT=`sed -n 's/Environment=PGPORT=//p' "${SERVICE_FILE}"`
-PGDATA=`sed -n 's/Environment=PGDATA=//p' "${SERVICE_FILE}"`
+PGPORT=`systemctl show -p Environment "${SERVICE_NAME}.service" |
+  sed 's/^Environment=//' | tr ' ' '\n' |
+  sed -n 's/^PGPORT=//p' | tail -n 1`
+
+if [ x"$PGPORT" = x ]
+then
+    echo "failed to find PGPORT setting in ${SERVICE_NAME}.service"
+    exit 1
+fi
 
 # Log file for initdb
 PGLOG=/var/lib/pgsql/initdb.log
