automake, clementine, ffmpegthumbnailer, filezilla, fox, geany-themes, hdparm, kernel-custom, lapack, lightspark, mesa, mikmod, rednotebook, rtmpdump, telepathy-{gabble,idle,salut}, vlgothic-fonts, youtube-dl

diff --git a/icu/icu-compat32.SlackBuild b/icu/icu-compat32.SlackBuild
--- a/icu/icu-compat32.SlackBuild
+++ b/icu/icu-compat32.SlackBuild
@@ -53,13 +53,16 @@ else
 fi
 SLKTARGET32=${SLKTARGET32:-i486}
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${PNAME}
 PKGDEST=${PKGDEST:-${CWD}}
 PKGFORMAT=${PKGFORMAT:-txz}
 PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH32}-${BUILD}${PACKAGER_ID}
+
+# Set to YES to enable C++11 support client side
+SB_CXX11=${SB_CXX11:-NO}
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
@@ -127,6 +130,30 @@ for variable in CFLAGS CPPFLAGS CXXFLAGS FFLAGS LDFLAGS; do
     || exit 1
 done
 
+unset UCHARFLAGS
+if [ "${SB_CXX11}" = "YES" ]; then
+  if [ "${CXX}" = "g++" ]; then
+    GCCVER="$(gcc --version | head -n1 | awk '{print $3}' | cut -d. --output-delimiter="" -f1-2)"
+    if [ "${GCCVER}" -eq "47" ] ;then
+      # Store ABI flags in CXXFLAGS in icu-config and icu-*.pc files for API consumers.
+      sed -e "/^CXXFLAGS =/s/ *$/ -std=gnu++11 -DUCHAR_TYPE=char16_t/" \
+        -i source/config/icu.pc.in source/config/Makefile.inc.in || exit 1
+    else
+      echo "GCC >=4.7 required for support for C++11."
+      exit 1
+    fi
+  else 
+    # Store ABI flags in CXXFLAGS in icu-config and icu-*.pc files for API consumers.
+    sed -e "/^CXXFLAGS =/s/ *$/ -std=c++11 -DUCHAR_TYPE=char16_t/" \
+      -i source/config/icu.pc.in source/config/Makefile.inc.in || exit 1
+  fi
+  # Set type of UChar in C++ mode to char16_t.
+  UCHARFLAGS="-DUCHAR_TYPE=char16_t"
+  # Hardcode type of UChar in C++ mode in installed headers.
+  sed -e "/^ typedef UCHAR_TYPE UChar;$/a #elif defined(__cplusplus)\n typedef char16_t UChar;" \
+    -i source/common/unicode/umachine.h || exit 1
+fi
+
 ( cd source
 
 if [ "${SB_AUTOGEN}" = "YES" ] ;then
@@ -134,7 +161,7 @@ if [ "${SB_AUTOGEN}" = "YES" ] ;then
 fi
 
 CFLAGS="${SLKCFLAGS} -fno-strict-aliasing" \
-CXXFLAGS="${SLKCFLAGS} -fno-strict-aliasing" \
+CXXFLAGS="${SLKCFLAGS} -fno-strict-aliasing ${UCHARFLAGS}" \
 ./configure \
   --prefix=/usr \
   --bindir=/usr/bin \
@@ -159,7 +186,7 @@ sed -i 's|^LIBS =.*|LIBS = -nostdlib -L../../lib -licutu -licuuc -lc|' tools/cte
 sed -i 's|^LIBS =.*|LIBS = -nostdlib -L../../lib -licui18n -licuuc -lpthread -lc|' tools/toolutil/Makefile
 
 # -j(X>1) may "break" man pages as of 3.2, b.f.u #2357
-make || exit 1
+make VERBOSE=1 || exit 1
 
 ) || exit 1
 
diff --git a/icu/icu.SlackBuild b/icu/icu.SlackBuild
--- a/icu/icu.SlackBuild
+++ b/icu/icu.SlackBuild
@@ -56,13 +56,16 @@ else
   SLKTARGET=${SLKTARGET:-i486}
 fi
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
 PKGDEST=${PKGDEST:-${CWD}}
 PKGFORMAT=${PKGFORMAT:-txz}
 PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
+
+# Set to YES to enable C++11 support client side
+SB_CXX11=${SB_CXX11:-NO}
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
@@ -139,6 +142,30 @@ done
 export CC="gcc"
 export CXX="g++"
 
+unset UCHARFLAGS
+if [ "${SB_CXX11}" = "YES" ]; then
+  if [ "${CXX}" = "g++" ]; then
+    GCCVER="$(gcc --version | head -n1 | awk '{print $3}' | cut -d. --output-delimiter="" -f1-2)"
+    if [ "${GCCVER}" -eq "47" ] ;then
+      # Store ABI flags in CXXFLAGS in icu-config and icu-*.pc files for API consumers.
+      sed -e "/^CXXFLAGS =/s/ *$/ -std=gnu++11 -DUCHAR_TYPE=char16_t/" \
+        -i source/config/icu.pc.in source/config/Makefile.inc.in || exit 1
+    else
+      echo "GCC >=4.7 required for support for C++11."
+      exit 1
+    fi
+  else 
+    # Store ABI flags in CXXFLAGS in icu-config and icu-*.pc files for API consumers.
+    sed -e "/^CXXFLAGS =/s/ *$/ -std=c++11 -DUCHAR_TYPE=char16_t/" \
+      -i source/config/icu.pc.in source/config/Makefile.inc.in || exit 1
+  fi
+  # Set type of UChar in C++ mode to char16_t.
+  UCHARFLAGS="-DUCHAR_TYPE=char16_t"
+  # Hardcode type of UChar in C++ mode in installed headers.
+  sed -e "/^ typedef UCHAR_TYPE UChar;$/a #elif defined(__cplusplus)\n typedef char16_t UChar;" \
+    -i source/common/unicode/umachine.h || exit 1
+fi
+
 ( cd source
 
 if [ "${SB_AUTOGEN}" = "YES" ] ;then
@@ -146,7 +173,7 @@ if [ "${SB_AUTOGEN}" = "YES" ] ;then
 fi
 
 CFLAGS="${SLKCFLAGS} -fno-strict-aliasing" \
-CXXFLAGS="${SLKCFLAGS} -fno-strict-aliasing" \
+CXXFLAGS="${SLKCFLAGS} -fno-strict-aliasing ${UCHARFLAGS}" \
 ./configure \
   --prefix=/usr \
   --bindir=/usr/bin \
@@ -170,7 +197,7 @@ sed -i 's|^LIBS =.*|LIBS = -nostdlib -L../../lib -licutu -licuuc -lc|' tools/cte
 sed -i 's|^LIBS =.*|LIBS = -nostdlib -L../../lib -licui18n -licuuc -lpthread -lc|' tools/toolutil/Makefile
 
 # -j(X>1) may "break" man pages as of 3.2, b.f.u #2357
-make || exit 1
+make VERBOSE=1 || exit 1
 #make doc || exit 1
 
 ) || exit 1
