crda, dbus-glib, dcraw, devdeng, dialog, dolphin-emu, getmail, gmime, gutenprint, help2man, iproute2, libclc, libevdev, libmbim, llvm, mesa, net-snmp, openssh, openssl, pinentrym ppsspp, python-pillow, qt-creator, qt5ct, quassel, rednotebook, slrn, strace, wpa_supplicant, zoneinfo

diff --git a/crda/setregdomain b/crda/setregdomain
--- a/crda/setregdomain
+++ b/crda/setregdomain
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright 2009-2010 Red Hat, Inc.  All rights reserved.
+# Copyright 2009-2014 Red Hat, Inc.  All rights reserved.
 #
 # Permission to use, copy, modify, and/or distribute this software for any
 # purpose with or without fee is hereby granted, provided that the above
@@ -15,8 +15,10 @@
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 #
 
-REGDOMAIN=/etc/default/regdomain
+REGDOMAIN=/etc/sysconfig/regdomain
 LOCALTIME=/etc/localtime
+
+LOGGER="/usr/bin/logger -t crda"
 
 getcountry() {
 	while read c a z r
@@ -35,32 +37,33 @@ then
 	. $REGDOMAIN
 	if [ -n "$COUNTRY" ]
 	then
-		/sbin/iw reg set $COUNTRY
+		/usr/sbin/iw reg set $COUNTRY
 		exit
 	fi
 fi
 
-if [ -f $TZ ]
+if [ -f "$LOCALTIME" ]
 then
-	ZONE=$(readlink $LOCALTIME)
+	ZONE=$(readlink -f $LOCALTIME)
 	ZONE=${ZONE#/usr/share/zoneinfo/}
 else
-	echo "Timezone information not found!  Unable to set regulatory domain."
-	exit
+	$LOGGER -s "Timezone information not found!  Unable to set regulatory domain."
+	exit 1
 fi
 
-if [ -z "$ZONE" ]
+if [ -z "$ZONE" -o "$ZONE" = "$LOCALTIME" ]
 then
-	echo "Timezone information not set!  Unable to set regulatory domain."
-	exit
+	$LOGGER -s "Could not determine timezone!  Unable to set regulatory domain."
+	exit 1
 fi
 
 COUNTRY=$(getcountry)
 
 if [ -z "$COUNTRY" ]
 then
-	echo "Could not determine country!  Unable to set regulatory domain."
-	exit
+	$LOGGER -s "Could not determine country!  Unable to set regulatory domain."
+	exit 1
 fi
 
+$LOGGER "setting regulatory domain to $COUNTRY based on timezone ($ZONE)"
 /usr/sbin/iw reg set $COUNTRY
