calligra, chmsee, cifs-utils, curl, enet, firefox, gparted, kmozillahelper, logrotate, nss, openldap-client, psi-i18n, pyopenssl, qbittorrent, rsyslog, seamonkey, util-linux, whois, xulrunner

diff --git a/bullet/bullet.SlackBuild b/bullet/bullet.SlackBuild
--- a/bullet/bullet.SlackBuild
+++ b/bullet/bullet.SlackBuild
@@ -3,7 +3,7 @@
 # Build script by Phantom X <megaphantomx at bol.com.br>
 # Suggested usage: $ bullet.SlackBuild 2>&1 | tee build.log
 #--
-# Copyright 2008, 2009, 2010, 2011 Phantom X, Goiania, Brazil.
+# Copyright 2008-2012 Phantom X, Goiania, Brazil.
 # Copyright 2006 Martijn Dekker, Groningen, Netherlands.
 # All rights reserved.
 #
@@ -116,6 +116,18 @@ chmod -R u+w,go+r-w,a-s .
 if [ -r ${CWD}/apply-patches.sh ]; then
   . ${CWD}/apply-patches.sh || exit 1
 fi
+
+# Fail when this is fixed
+grep -vq '^prefix=' bullet.pc.cmake || exit 1
+mv bullet.pc.cmake bullet.pc.cmake.orig
+cat > bullet.pc.cmake <<EOF
+prefix=/usr
+exec_prefix=/usr
+libdir=/usr/lib${LIBDIRSUFFIX}
+includedir=/usr/include
+
+EOF
+cat bullet.pc.cmake.orig >> bullet.pc.cmake
 
 export CFLAGS="${SLKCFLAGS}"
 export CXXFLAGS="${SLKCFLAGS}"
