atool, dhcp, feh, ffmpeg, firefox, foobillardplus, icecat, kbuild, ktorrent, libktorrent, mplayer*, pcre, virtualbox, wget, xulrunner

diff --git a/icecat/icecat.sh.in b/icecat/icecat.sh.in
--- a/icecat/icecat.sh.in
+++ b/icecat/icecat.sh.in
@@ -48,29 +48,22 @@ case ${MOZ_ARCH} in
     ;;
 esac
 
-if [ ! -x ${MOZ_LIB_DIR}/icecat-ICECAT_VERSION/icecat ]; then
-    if [ ! -x ${SECONDARY_LIB_DIR}/icecat-ICECAT_VERSION/icecat ]; then
-	echo "Error: ${MOZ_LIB_DIR}/icecat-ICECAT_VERSION/icecat not found"
-	if [ -d ${SECONDARY_LIB_DIR} ]; then
-	    echo "       ${SECONDARY_LIB_DIR}/icecat-ICECAT_VERSION/icecat not found"
-	fi
-	exit 1
+MOZ_ICECAT_FILE="icecat"
+
+if [ ! -r ${MOZ_LIB_DIR}/icecat-ICECAT_VERSION/${MOZ_ICECAT_FILE} ]; then
+  if [ ! -r ${SECONDARY_LIB_DIR}/icecat-ICECAT_VERSION/${MOZ_ICECAT_FILE} ]; then
+    echo "Error: ${MOZ_LIB_DIR}/icecat-ICECAT_VERSION/${MOZ_ICECAT_FILE} not found"
+    if [ -d ${SECONDARY_LIB_DIR} ]; then
+      echo "       ${SECONDARY_LIB_DIR}/icecat-ICECAT_VERSION/${MOZ_ICECAT_FILE} not found"
     fi
-    MOZ_LIB_DIR="${SECONDARY_LIB_DIR}"
+    exit 1
+  fi
+  MOZ_LIB_DIR="${SECONDARY_LIB_DIR}"
 fi
 MOZ_DIST_BIN="${MOZ_LIB_DIR}/icecat-ICECAT_VERSION"
 MOZ_EXTENSIONS_DIR="${MOZ_DIST_BIN}/extensions"
-MOZ_PROGRAM="${MOZ_DIST_BIN}/icecat"
-MOZ_LAUCHER="${MOZ_DIST_BIN}/run-icecat.sh"
- 
-##
-## Set MOZ_GRE_CONF
-##
-MOZ_GRE_CONF=/etc/gre.d/gre.conf
-if [ "${MOZ_LIB_DIR}" == "/usr/lib64" ]; then
-  MOZ_GRE_CONF=/etc/gre.d/gre64.conf
-fi
-export MOZ_GRE_CONF
+MOZ_PROGRAM="${MOZ_DIST_BIN}/${MOZ_ICECAT_FILE}"
+MOZ_LAUNCHER="${MOZ_DIST_BIN}/run-icecat.sh"
 
 ##
 ## Set MOZILLA_FIVE_HOME
@@ -180,7 +173,7 @@ done
 debugging=0
 if [ ${debugging} = 1 ]
 then
-  echo ${MOZ_LAUCHER} ${script_args} ${MOZ_PROGRAM} ${MOZARGS} "$@"
+  echo ${MOZ_LAUNCHER} ${script_args} ${MOZ_PROGRAM} ${MOZARGS} "$@"
 fi
 
-exec ${MOZ_LAUCHER} ${script_args} ${MOZ_PROGRAM} ${MOZARGS} "$@"
+exec ${MOZ_LAUNCHER} ${script_args} ${MOZ_PROGRAM} ${MOZARGS} "$@"
