exif, gst-plugins-good, kacst-fonts-ttf, libexif, nvidia-cg-toolkit, patch, xinit

diff --git a/nvidia-cg-toolkit/nvidia-cg-toolkit.SlackBuild b/nvidia-cg-toolkit/nvidia-cg-toolkit.SlackBuild
--- a/nvidia-cg-toolkit/nvidia-cg-toolkit.SlackBuild
+++ b/nvidia-cg-toolkit/nvidia-cg-toolkit.SlackBuild
@@ -41,9 +41,25 @@ PNAME=Cg
 NAME=nvidia-cg-toolkit
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-2.2}
-SVER=$(echo ${VERSION} | cut -d. -f1-2)
-CGDATE=${CGDATE:-April2009}
+VERSION=${VERSION:-2.2-2009.10}
+SVER=$(echo ${VERSION} | cut -d- -f1)
+CGDATE=$(echo ${VERSION} | cut -d- -f2)
+YEAR=$(echo ${CGDATE} | cut -d. -f1)
+MONTH=$(echo ${CGDATE} | cut -d. -f2)
+case ${MONTH} in
+  01) RMONTH=January ;;
+  02) RMONTH=February ;;
+  03) RMONTH=March ;;
+  04) RMONTH=April ;;
+  05) RMONTH=May ;;
+  06) RMONTH=June ;;
+  07) RMONTH=July ;;
+  08) RMONTH=August ;;
+  09) RMONTH=September ;;
+  10) RMONTH=October ;;
+  11) RMONTH=November ;;
+  12) RMONTH=December ;;
+esac
 # x86 or x86_64
 ARCH=${ARCH:-x86}
 if [ "${ARCH}" = "x86_64" ] ;then
@@ -68,7 +84,7 @@ PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
-SRCDIR=${PNAME}-${SVER}_${CGDATE}_${DARCH}
+SRCDIR=${PNAME}-${SVER}_${RMONTH}${YEAR}_${DARCH}
 SRCARCHIVE=${SRCDIR}.tgz
 
 DL_TO=${DL_TO:-5}
@@ -122,6 +138,36 @@ cat > ${PKG}/etc/profile.d/cgc.csh <<'EOF'
 setenv CG_COMPILER_EXE /usr/bin/cgc
 EOF
 chmod 0755 ${PKG}/etc/profile.d/cgc.* || exit 1
+
+if [ "${ARCH}" = "x86_64" ] ;then
+  mv ${PKG}/usr/bin/cgc ${PKG}/usr/bin/cgc-64 || exit 1
+
+cat > ${PKG}/usr/bin/cgc <<EOF
+#!/bin/sh
+# Wrapper for multilib
+# If want use 32 bit version, run as "linux32 cgc"
+
+host="\$(uname -m)"
+
+case "\${host}" in
+  x86_64|s390x)
+    export CG_COMPILER_EXE=/usr/bin/cgc-64
+    exec /usr/bin/cgc-64 "\$@"
+    ;;
+  i[3-6]86|athlon|s390|*)
+    if [ -x /usr/bin/cgc-32 ] ;then
+      export CG_COMPILER_EXE=/usr/bin/cgc-32
+      exec /usr/bin/cgc-32 "\$@"
+    else
+      echo 'Command /usr/bin/cgc-32 not found!'
+      exit 1
+    fi
+    ;;
+esac
+
+EOF
+chmod 0755 ${PKG}/usr/bin/cgc || exit 1
+fi
 
 # Add a documentation directory:
 mkdir -p ${DOCDIR}/html
