gmp4, gmp, kde 4.4.0, kernel-custom

diff --git a/kde/KDE.SlackBuild b/kde/KDE.SlackBuild
--- a/kde/KDE.SlackBuild
+++ b/kde/KDE.SlackBuild
@@ -1,156 +1,81 @@
 #!/bin/sh
+
 # Build (and install) all KDE packages.
 # Written for Slackware by volkerdi@slackware.com.
+# Modified for KDE4 by Robby Workman <rworkman@slackware.com>
 
-# Recommended:  install CUPS first if you want KDE to support it.
-# We use an annoying delay to encourage CUPS adoption.  ;-)
-if [ ! -r /var/log/packages/cups-* ]; then
-  echo "Don't want CUPS support, huh?"
-  sleep 10
-fi
-
-# These are also prerequisites (located in the L series)
-# pcre
-# libxml2
-# libxslt
+# kdeaccessibility builds plugins for epos, festival, flite, freetts, and
+# hadifix, so they should work with kde if any of those are installed later
 
 # Set the config option variables if they are not already set:
-if [ -r ./KDE.options ]; then
-  . ./KDE.options
-fi
+[ -r ./KDE.options ] && . ./KDE.options
 
 # This avoids compiling a version number into KDE's .la files:
-QTDIR=/usr/lib/qt
-export QTDIR
+QTDIR=/usr/lib${LIBDIRSUFFIX}/qt ; export QTDIR
 
-if [ -d kdebase ]; then
-. ./kdebase/profile.d/kde.sh
+# Get the kde environment variables
+[ -d kdebase ] && eval $(sed -e "s#/lib#/lib${LIBDIRSUFFIX}#" ./kdebase/profile.d/kde.sh)
+
+KDEMODS=" \
+  kdelibs \
+  kdelibs-experimental \
+  kdepimlibs \
+  kdebase \
+  kdebase-workspace \
+  kdebase-runtime \
+  kdesdk \
+  kdevplatform \
+  kdegraphics \
+  kdebindings \
+  kdebase-workspace \
+  kdeaccessibility \
+  kdeutils \
+  kdemultimedia \
+  kdenetwork \
+  kopete-cryptography \
+  oxygen-icons \
+  kdeadmin \
+  kdeartwork \
+  kdegames \
+  kdetoys \
+  kdepim \
+  kdepim-runtime \
+  kdeedu \
+  kdewebdev \
+  kdeplasma-addons \
+  kdevelop \
+  konq-plugins \
+  guidance-power-manager \
+  ktorrent \
+  skanlite \
+  koffice \
+  kaudiocreator \
+  amarok"
+
+# Allow for specification of individual packages to be built:
+if [ -z "$1" ]; then
+  MODQUEUE=$KDEMODS
+else
+  MODQUEUE=$*
 fi
 
-# This is now found in the L series:
-#( cd arts
-#  ./arts.SlackBuild
-#  installpkg /tmp/arts-*.tgz
-#)
+# Yes, we know kdebase-workspace is built twice.  kdebase needs the
+#   plasma bits from it, and then we build it again for good measure...
+for module in \
+  $MODQUEUE ;
+do
+  cd $module
+  ./$module.SlackBuild
+  if [ $? = 0 ]; then
+    # Yes, I will build with the fresh packages installed:
+    upgradepkg --install-new --reinstall /tmp/${module}-*.txz
+    # Keep MIME database current:
+    /usr/bin/update-mime-database /usr/share/mime 1> /dev/null 2> /dev/null &
+    rm -rf /tmp/package-${module} /tmp/${module}-$VERSION
+  else
+    echo "${module} failed to build."
+    exit 1
+  fi
+  cd - ;
+done
 
-( cd kdelibs
-  ./kdelibs.SlackBuild
-  installpkg /tmp/kdelibs-*.tgz
-)
-
-( cd kdnssd-avahi
-  ./kdnssd-avahi.SlackBuild
-  installpkg /tmp/kdnssd-avahi-*.tgz
-)
-
-( cd kdebase
-  ./kdebase.SlackBuild
-  installpkg /tmp/kdebase-*.tgz
-)
-
-( cd pykde
-  ./pykde.SlackBuild
-  installpkg /tmp/pykde-*.tgz
-)
-
-( cd kdebindings
-  ./kdebindings.SlackBuild
-  installpkg /tmp/kdebindings-*.tgz
-)
-
-( cd kdeaccessibility
-  ./kdeaccessibility.SlackBuild
-  installpkg /tmp/kdeaccessibility-*.tgz
-)
-
-( cd kdeutils
-  ./kdeutils.SlackBuild
-  installpkg /tmp/kdeutils-*.tgz
-)
-
-( cd kdemultimedia
-  ./kdemultimedia.SlackBuild
-  installpkg /tmp/kdemultimedia-*.tgz
-)
-
-( cd kdenetwork
-  ./kdenetwork.SlackBuild
-  installpkg /tmp/kdenetwork-*.tgz
-)
-
-( cd kdeadmin
-  ./kdeadmin.SlackBuild
-  installpkg /tmp/kdeadmin-*.tgz
-)
-
-( cd kdeartwork
-  ./kdeartwork.SlackBuild
-  installpkg /tmp/kdeartwork-*.tgz
-)
-
-( cd kdegames
-  ./kdegames.SlackBuild
-  installpkg /tmp/kdegames-*.tgz
-)
-
-( cd kdetoys
-  ./kdetoys.SlackBuild
-  installpkg /tmp/kdetoys-*.tgz
-)
-
-( cd kdegraphics
-  ./kdegraphics.SlackBuild
-  installpkg /tmp/kdegraphics-*.tgz
-)
-
-( cd kdeedu
-  ./kdeedu.SlackBuild
-  installpkg /tmp/kdeedu-*.tgz
-)
-
-( cd kdepim
-  ./kdepim.SlackBuild
-  installpkg /tmp/kdepim-*.tgz
-)
-
-( cd kdeaddons
-  ./kdeaddons.SlackBuild
-  installpkg /tmp/kdeaddons-*.tgz
-)
-
-( cd kdesdk
-  ./kdesdk.SlackBuild
-  installpkg /tmp/kdesdk-*.tgz
-)
-
-( cd kdevelop
-  ./kdevelop.SlackBuild
-  installpkg /tmp/kdevelop-*.tgz
-)
-
-( cd kdewebdev
-  ./kdewebdev.SlackBuild
-  installpkg /tmp/kdewebdev-*.tgz
-)
-
-
-# Usually the optional packages are manually built:
-exit 0
-
-
-( cd amarok
-  ./amarok.SlackBuild
-  installpkg /tmp/amarok-*.tgz
-)
-
-( cd k3b
-  ./k3b.SlackBuild
-  installpkg /tmp/k3b-*.tgz
-)
-
-( cd koffice
-  ./koffice.SlackBuild
-  installpkg /tmp/koffice-*.tgz
-)
-
-# Done!
