clementine, depfinder, firefox, grep, gnome-disk-utility, imagemagick, libchamplain, nasm, openssl, qbittorrent, roxterm, spamassassin, stunnel, system-config-printer, tmpwatch, vim, xulrunner, youtube-dl

diff --git a/worldofgoo/worldofgoo.SlackBuild b/worldofgoo/worldofgoo.SlackBuild
--- a/worldofgoo/worldofgoo.SlackBuild
+++ b/worldofgoo/worldofgoo.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/sh
-#-- tmpwatch for Slackware --
+#-- worldofgoo for Slackware --
 # Build script by Phantom X <megaphantomx@bol.com.br>
-# Suggested usage: $ tmpwatch.SlackBuild 2>&1 | tee build.log
+# Suggested usage: $ worldofgoo.SlackBuild 2>&1 | tee build.log
 #--
 # Copyright 2008, 2009, 2010 Phantom X, Goiania, Brazil.
 # Copyright 2006 Martijn Dekker, Groningen, Netherlands.
@@ -23,13 +23,10 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# https://fedorahosted.org/tmpwatch/
+# http://2dboy.com/
 
 PACKAGER_ID=${PACKAGER_ID:-$USER}
 PACKAGER=${PACKAGER:-$USER@$HOSTNAME}
-
-# Set YES for native build with gcc >= 4.2
-SB_NATIVE=${SB_NATIVE:-NO}
 
 # Set to YES to replicate slackbuild and patches
 SB_REP=${SB_REP:-YES}
@@ -40,15 +37,13 @@ if [ ! -d ${TMP} ]; then
   mkdir -p ${TMP}
 fi
 
-NAME=tmpwatch
+PNAME=WorldOfGoo
+NAME=worldofgoo
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-2.10}
-if [ "${SB_NATIVE}" = "YES" ] ;then
-  ARCH=${ARCH:-$(uname -m)}
-else
-  ARCH=${ARCH:-i686}
-fi
+VERSION=${VERSION:-1.41}
+# x86 or x86_64
+ARCH=${ARCH:-x86}
 if [ "${ARCH}" = "x86_64" ] ;then
   SLKTARGET=${SLKTARGET:-x86_64}
 else
@@ -63,30 +58,31 @@ PKGDEST=${PKGDEST:-${CWD}}
 PKGFORMAT=${PKGFORMAT:-txz}
 PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
 
+# Set to YES to use libraries from system
+# Set to NO on every problem before contact upstream support
+SB_SYSLIBS=${SB_SYSLIBS:-YES}
+
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
-SRCDIR=${NAME}-${VERSION}
-SRCARCHIVE=${SRCDIR}.tar.bz2
+SRCDIR=${PNAME}
+SRCARCHIVE=${SRCDIR}Setup.${VERSION}.tar.gz
 
 DL_PROG=${DL_PROG:-wget}
 DL_TO=${DL_TO:-5}
 DL_OPTS=${DL_OPTS:-"--timeout=${DL_TO}"}
-DL_URL="https://fedorahosted.org/releases/$(echo ${NAME} | sed -e 's/\(.\).*/\1/')/$(echo ${NAME} | sed -e 's/.\(.\).*/\1/')/${NAME}/${SRCARCHIVE}"
+DL_URL="http://2dboy.com/"
 
 # if source is not present, download in source rootdir if possible
-test -r ${CWD}/${SRCARCHIVE} || ${DL_PROG} --no-check-certificate ${DL_OPTS} ${DL_URL} || exit 1
+if ! test -r ${SRCARCHIVE}; then
+  echo "Download ${SRCARCHIVE} from ${DL_URL}" && exit 1
+fi
 
-if [ "${SB_NATIVE}" = "YES" ] ;then
-  SLKCFLAGS="-O2 -march=native -mtune=native ${SB_ECFLAGS} -pipe"
+if [ "${ARCH}" = "x86_64" ] ;then
+  LIBDIRSUFFIX="64"
+  BINSUFFIX="64"
 else
-  case "${ARCH}" in
-    i[3-6]86)    SLKCFLAGS="-O2 -march=${ARCH} -mtune=i686"
-                 ;;
-    s390)        SLKCFLAGS="-O2"
-                 ;;
-    x86_64)      SLKCFLAGS="-O2 -fPIC"
-                 ;;
-  esac
+  LIBDIRSUFFIX=""
+  BINSUFFIX="32"
 fi
 
 if [ -d ${PKG} ]; then
@@ -104,35 +100,99 @@ chmod -R u+w,go+r-w,a-s .
 
 # zcat ${CWD}/${NAME}.patch.gz | patch -p0 -E --backup --verbose || exit 1
 
-CFLAGS="${SLKCFLAGS}" \
-CXXFLAGS="${SLKCFLAGS}" \
-./configure \
-  --prefix=/usr \
-  --libdir=/usr/lib${LIBDIRSUFFIX} \
-  --sysconfdir=/etc \
-  --localstatedir=/var/lib \
-  --infodir=/usr/info \
-  --mandir=/usr/man \
-  --docdir=/usr/doc/${NAME}-${VERSION} \
-  --build=${SLKTARGET}-${SLKDTARGET}-linux || exit 1
+sed -i -e '/fullscreen/s|true|false|g' properties/config.txt || exit 1
 
-make -j${NJOBS} || make || exit 1
-make install DESTDIR=${PKG} || exit 1
+sed -i -e "s|/opt/|/usr/lib${LIBDIRSUFFIX}/${PNAME}|g" linux-issues.txt || exit 1
+
+mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}/${PNAME}
+install -pm0755 ${PNAME}.bin${BINSUFFIX} \
+  ${PKG}/usr/lib${LIBDIRSUFFIX}/${PNAME}/${PNAME} || exit 1
+if [ -x /usr/bin/execstack ] ;then
+  execstack -c ${PKG}/usr/lib${LIBDIRSUFFIX}/${PNAME}/${PNAME} || exit 1
+fi
+
+cp -R properties res ${PKG}/usr/lib${LIBDIRSUFFIX}/${PNAME}/ || exit 1
 
 mkdir -p ${PKG}/usr/bin
-ln -s ../sbin/tmpwatch ${PKG}/usr/bin/tmpwatch || exit 1
-   
-mkdir -p ${PKG}/etc/cron.daily
-zcat ${CWD}/${NAME}.daily.gz > ${PKG}/etc/cron.daily/${NAME}.new || exit 1
-chmod 0755 ${PKG}/etc/cron.daily/${NAME}.new
+cat > ${PKG}/usr/bin/${PNAME} <<EOF
+#!/bin/sh
 
-find ${PKG} | xargs file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+BINDIR=/usr/_LIBDIR_/${PNAME}
+EOF
+cat >> ${PKG}/usr/bin/${PNAME} <<'EOF'
+cd ${BINDIR} || exit 1
+export LD_LIBRARY_PATH=${BINDIR}/libs:"${LD_LIBRARY_PATH}"
+
+trap cleanup ERR
+cleanup() {
+  set +e
+  echo ""
+  echo "It looks like World of Goo crashed! If you need support, please include the"
+  echo "contents of the log file in your problem report."
+  
+  LOGPATH="${HOME}/.WorldOfGoo/WorldOfGoo.log"
+  if [ -f "${LOGPATH}" ]
+  then
+    echo "The log file is stored at: ${LOGPATH}"
+  
+    echo "" >> ${LOGPATH}
+    echo "Libraries used:" >> ${LOGPATH}
+    ldd ${BINDIR}/WorldOfGoo >> ${LOGPATH} 2>&1
+  
+    echo "" >> ${LOGPATH}
+    GLXINFO=$(which glxinfo)
+    if [ -z "${GLXINFO}" ]
+    then
+      echo "glxinfo not found!" >> ${LOGPATH}
+    else
+      echo "Output of glxinfo:" >>${LOGPATH}
+      glxinfo >>${LOGPATH} 2>&1
+    fi
+    
+  else
+    echo "Unfortunately, no log file has been created!"
+  fi
+}
+
+./WorldOfGoo "$@"
+EOF
+sed -i -e "s|_LIBDIR_|lib${LIBDIRSUFFIX}|g" ${PKG}/usr/bin/${PNAME} || exit 1
+chmod 0755 ${PKG}/usr/bin/${PNAME} || exit 1
+
+if [ "${SB_SYSLIBS}" = "YES" ] ;then
+  sed -i -e '/^export LD_LIBRARY_PATH=/d' ${PKG}/usr/bin/${PNAME} || exit 1
+else
+  mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}/${PNAME}/libs
+  install -pm0755 libs${BINSUFFIX}/*.so.* \
+    ${PKG}/usr/lib${LIBDIRSUFFIX}/${PNAME}/libs/ || exit 1
+  cp libs${BINSUFFIX}/{COPYING,README}* .
+fi
+
+mkdir -p ${PKG}/usr/share/applications
+cat >> ${PKG}/usr/share/applications/${PNAME}.desktop <<EOF
+[Desktop Entry]
+Name=World of Goo
+Comment=A physics based puzzle/construction game
+Icon=${PNAME}
+Exec=${PNAME}
+Type=Application
+Terminal=false
+Categories=Game;LogicGame;
+EOF
+
+for res in 16 22 32 48 64 128 ;do
+  dir=${PKG}/usr/share/icons/hicolor/${res}x${res}/apps
+  mkdir -p ${dir}
+  install -pm0644 icons/${res}x${res}.png ${dir}/${PNAME}.png || exit 1
+done
+mkdir -p ${PKG}/usr/share/icons/hicolor/scalable/apps
+install -pm0644 icons/scalable.svg \
+  ${PKG}/usr/share/icons/hicolor/scalable/apps/${PNAME}.svg || exit 1
 
 # Add a documentation directory:
 mkdir -p ${DOCDIR}
 cp -a \
-  ChangeLog NEWS README ${CWD}/ChangeLog.SB \
+  COPYING* *.txt readme.html ${CWD}/ChangeLog.SB \
   ${DOCDIR}/
 find ${DOCDIR}/ -type d -print0 | xargs -0 chmod 0755
 find ${DOCDIR}/ -type f -print0 | xargs -0 chmod 0644
@@ -162,28 +222,6 @@ mkdir -p ${PKG}/install
 cat ${CWD}/slack-desc > ${PKG}/install/slack-desc
 cat ${CWD}/slack-required > ${PKG}/install/slack-required
 
-cat > ${PKG}/install/doinst.sh <<EOF
-#!/bin/sh
-config() {
-  NEW="\$1"
-  OLD="\$(dirname \$NEW)/\$(basename \$NEW .new)"
-  # If there's no config file by that name, mv it over:
-  if [ ! -r \$OLD ]; then
-    mv \$NEW \$OLD
-  elif [ "\$(cat \$OLD | md5sum)" = "\$(cat \$NEW | md5sum)" ]; then
-    # toss the redundant copy
-    rm \$NEW
-  fi
-  # Otherwise, we leave the .new copy for the admin to consider...
-}
-## List of conf files to check.  The conf files in your package should end in .new
-EOF
-
-( cd ${PKG}
-  find etc/ -name *.new -exec echo config {} ';' | sort >> ${PKG}/install/doinst.sh
-  echo >> ${PKG}/install/doinst.sh
-)
-
 sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
        ${PKG}/install/slack-desc
 
@@ -191,7 +229,7 @@ if [ "${SB_REP}" = "YES" ] ;then
   # Replicate slackbuild and patches
   mkdir -p ${SBDIR}
   install -m0644 ${CWD}/slack-desc ${CWD}/slack-required ${CWD}/ChangeLog.SB \
-                 ${CWD}/${NAME}.daily.gz ${SBDIR}/
+                 ${SBDIR}/
   install -m0755 ${CWD}/${NAME}.SlackBuild \
                  ${SBDIR}/${NAME}.SlackBuild
 fi
