fvwm, xfce, xfce4-{clipman,datetime,mount,verve,wmdock}-plugin

diff --git a/xfce/xfce.SlackBuild b/xfce/xfce.SlackBuild
--- a/xfce/xfce.SlackBuild
+++ b/xfce/xfce.SlackBuild
@@ -51,15 +51,15 @@ if [ ! -d ${TMPD} ]; then
 fi
 PKG=${PKG:-${TMPD}/package-${NAME}}
 
-PKGVER=${PKGVER:-4.4.3}
-VERSION=${VERSION:-4.4.3}
+PKGVER=${PKGVER:-4.6.0}
+VERSION=${VERSION:-4.6.0}
+VERSIONO=${VERSIONO:-4.6.0}
+GXEVER=${GXEVER:-2.6.0}
+THUVER=${THUVER:-1.0.0}
+EXOVER=${EXOVER:-0.3.100}
+MPVER=${MPVER:-0.2.16}
+TERMVER=${TERMVER:-0.2.10}
 SLKDIST=${SLKDIST:-Slackware}
-VERSIONO=${VERSIONO:-4.4.0.1}
-GXEVER=${GXEVER:-2.4.3}
-THUVER=${THUVER:-0.9.3}
-EXOVER=${EXOVER:-0.3.4}
-MPVER=${MPVER:-0.2.14}
-TERMVER=${TERMVER:-0.2.8.3}
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
 else
@@ -67,7 +67,7 @@ else
 fi
 SLKTARGET=${SLKTARGET:-i486}
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-2}
+BUILD=${BUILD:-1}
 NJOBS=${NJOBS:-2}
 DOCDIR=${PKG}/usr/doc
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -76,6 +76,10 @@ PKGNAME=${NAME}-$(echo ${PKGVER} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
 
 # Set to YES to enable hal support
 SB_HAL=${SB_HAL:-NO}
+# Set to YES to enable some gnome things support
+SB_GNOME=${SB_GNOME:-NO}
+# Set to YES to run pulseaudio on start
+SB_PA=${SB_PA:-NO}
 # Set to YES to enable support for slack-artwork
 SB_SLKART=${SB_SLKART:-NO}
 
@@ -113,77 +117,104 @@ mkdir -p ${PKG}
 mkdir -p ${PKG}/usr/man ${PKG}/usr/share ${PKG}/usr/doc
 ( cd ${PKG}/usr/share ; ln -sf ../man . ; ln -sf ../doc . )
 
+SRCDIRS="
+libxfce4util-${VERSION} \
+libxfce4menu-${VERSION} \
+xfconf-${VERSION} \
+libxfcegui4-${VERSION} \
+exo-${EXOVER} \
+xfce4-panel-${VERSION} \
+gtk-xfce-engine-${GXEVER} \
+Thunar-${THUVER} \
+xfce-utils-${VERSION} \
+xfce4-appfinder-${VERSION} \
+xfce4-dev-tools-${VERSIONO} \
+xfce4-mixer-${VERSION} \
+xfce4-session-${VERSION} \
+xfce4-settings-${VERSION} \
+xfdesktop-${VERSION} \
+xfprint-${VERSION} \
+xfwm4-${VERSION} \
+xfwm4-themes-${VERSION} \
+mousepad-${MPVER} \
+orage-${VERSION} \
+Terminal-${TERMVER} \
+"
+
+mkdir -p ${CWD}/src
+# if source is not present, download in source rootdir if possible, or in /tmp
+for BASENAME in ${SRCDIRS} ;do
+  file=${BASENAME}.tar.bz2
+  test -r ${CWD}/src/${file} || wget -P ${CWD}/src ${DL_OPTS} ${DL_URL}/${file} || exit 1
+  test -r ${CWD}/src/${file}.md5 || wget -P ${CWD}/src ${DL_OPTS} ${DL_URL}/${file}.md5 || exit 1
+  ( cd src || exit 1
+    if [ "$(md5sum ${file} )" != "$(head -n1 ${file}.md5)" ] ;then
+      echo "md5 error with ${file}. Delete it and try again."
+      exit 1
+    fi
+  ) || exit 1
+done
+
+cd ${TMPD} || exit 1
+
+# Untar and test patches before
+for BASENAME in ${SRCDIRS} ;do
+  ( file=${BASENAME}.tar.bz2
+    rm -rf ${BASENAME}
+    tar -xjf ${CWD}/src/${file} || exit 1
+
+    cd ${BASENAME} || exit 1
+    chmod -R u+w,go+r-w,a-s .
+    if [ -r ${CWD}/apply-patches.sh ]; then
+      . ${CWD}/apply-patches.sh || exit 1
+    fi
+  ) || exit 1
+done
+
 if [ "${SB_HAL}" = "YES" ] ;then
   SB_HALOPTS="hal"
 else
   SB_HALOPTS="none"
 fi
 
-for file in \
-libxfce4util-${VERSION}.tar.bz2 \
-libxfcegui4-${VERSION}.tar.bz2 \
-libxfce4mcs-${VERSION}.tar.bz2 \
-xfce-mcs-manager-${VERSION}.tar.bz2 \
-xfce4-panel-${VERSION}.tar.bz2 \
-gtk-xfce-engine-${GXEVER}.tar.bz2 \
-exo-${EXOVER}.tar.bz2 \
-Thunar-${THUVER}.tar.bz2 \
-xfce-mcs-plugins-${VERSION}.tar.bz2 \
-xfce-utils-${VERSION}.tar.bz2 \
-xfce4-appfinder-${VERSION}.tar.bz2 \
-xfce4-dev-tools-${VERSIONO}.tar.bz2 \
-xfce4-icon-theme-${VERSION}.tar.bz2 \
-xfce4-mixer-${VERSION}.tar.bz2 \
-xfce4-session-${VERSION}.tar.bz2 \
-xfdesktop-${VERSION}.tar.bz2 \
-xfprint-${VERSION}.tar.bz2 \
-xfwm4-${VERSION}.tar.bz2 \
-xfwm4-themes-${VERSION}.tar.bz2 \
-mousepad-${MPVER}.tar.bz2 \
-orage-${VERSION}.tar.bz2 \
-Terminal-${TERMVER}.tar.bz2 \
-; do
-  ( # if source is not present, download in source rootdir if possible, or in /tmp
-    mkdir -p ${CWD}/src
-    test -r ${CWD}/src/${file} || wget -P ${CWD}/src ${DL_OPTS} ${DL_URL}/${file} || exit 1
-    BASENAME=$(basename ${file} .tar.bz2)
-    cd ${TMPD} || exit 1
+[ "{SB_GNOME}" = "YES" ] || SB_GNOMEOPTS='--disable-gnome-thumbnailers'
+
+for BASENAME in ${SRCDIRS} ;do
+  ( file=${BASENAME}.tar.bz2
     echo "+===========================+"
     echo "| ${BASENAME} |"
     echo "+===========================+"
-    rm -rf ${BASENAME}
-    tar -xjf ${CWD}/src/${file} || exit 1
     
     cd ${BASENAME} || exit 1
 
     SB_EXNJOBS=${NJOBS}
+
+    if [ "${BASENAME}" = "Thunar-${THUVER}" ]; then
+      SB_EXTRAOPT="--with-volume-manager=${SB_HALOPTS} ${SB_GNOMEOPTS}"
+    fi
+    if [ "${BASENAME}" = "xfce-utils-${VERSION}" ] && [ -f "${CWD}/${SLKDIST}" ] ; then
+      mkdir -p ${PKG}/usr/share/xfce4
+      cat ${CWD}/${SLKDIST} > ./${SLKDIST}
+      cat ${CWD}/${SLKDIST} > ${PKG}/usr/share/xfce4/${SLKDIST}
+      SB_EXTRAOPT="--with-vendor-info=${SLKDIST}"
+    fi
     
-    if [ -r ${CWD}/apply-patches.sh ]; then
-      . ${CWD}/apply-patches.sh || exit 1
-    fi
-
-    if [ "${file}" = "xfdesktop-${VERSION}.tar.bz2" ]; then
-      # Fix for wine directory.
-      sed -i -e 's|WINE|wine|g;
-                /<category name="Wine"/s|$|\n\t<category name="X-Wine" replace="Wine" toplevel="true" builtin-icon="wine" />|g' \
-                modules/menu/xfce-registered-categories.xml*
-    fi
-    if [ "${file}" = "Thunar-${THUVER}.tar.bz2" ]; then
-      SB_EXTRAOPT="--with-volume-manager=${SB_HALOPTS} --disable-gnome-thumbnailers"
-    fi
-    if [ "${file}" = "xfce4-mixer-${VERSION}.tar.bz2" ]; then
-      SB_EXTRAOPT="--with-sound=alsa"
-      SB_EXNJOBS=1
-    fi
-
     chmod -R u+w,go+r-w,a-s .
 
+    export PATH=${PATH}:${PKG}/usr/bin
     export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PKG}/usr/lib
+
+    # Dynamic cppflags
+    for di in ${PKG}/usr/include/* ${PKG}/usr/include/xfce4/* ; do
+      if [ -d ${di} ] ;then
+        XFECPPFLAGS="-I${di} ${XFECPPFLAGS}"
+      fi
+    done
 
     CFLAGS="${SLKCFLAGS}" \
     CXXFLAGS="${SLKCFLAGS}" \
-    LDFLAGS="-L${PKG}/usr/lib ${LDFLAGS} " \
-    CPPFLAGS="-I${PKG}/usr/include -I${PKG}/usr/include/xfce4 -I${PKG}/usr/include/exo-0.3 -I${PKG}/usr/include/thunar-vfs-1 -I${PKG}/usr/include/thunarx-1 ${CPPFLAGS}" \
+    LDFLAGS="-L${PKG}/usr/lib ${LDFLAGS}" \
+    CPPFLAGS="-I${PKG}/usr/include ${XFECPPFLAGS} ${CPPFLAGS}" \
     PKG_CONFIG_PATH="${PKG}/usr/lib/pkgconfig" \
     ./configure \
       --prefix=/usr \
@@ -215,20 +246,16 @@ done
 
 if [ "${SB_SLKART}" = "YES" ] ;then
   rm -f ${PKG}/etc/xfce/xdg/xfce4/panel/xfce4-menu-5.rc
-  rm -f ${PKG}/etc/xfce/xdg/xfce4-session/xfce4-session.rc
-  rm -f ${PKG}/etc/xfce/xdg/xfce4-session/xfce4-splash.rc
-  rm -f ${PKG}/etc/xfce/xdg/xfce4/mcs_settings/desktop.xml
-  rm -f ${PKG}/etc/xfce/xdg/xfce4/mcs_settings/gtk.xml
+  rm -f ${PKG}/etc/xfce/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
+  rm -f ${PKG}/etc/xfce/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml
+  rm -f ${PKG}/etc/xfce/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
 fi
 
 ( cd ${PKG}/etc/xfce/xdg/xfce4
-  for f in panel/* mcs_settings/* xfce4-session/* ;do
+  for f in panel/* xfconf/xfce-perchannel-xml/* ;do
     mv ${f} ${f}.new
   done
 )
-
-sed -i -e '/^Hidden=/s|=.*|=true|g' \
-           ${PKG}/etc/xfce/xdg/autostart/xfce4-tips-autostart.desktop || exit 1
 
 SB_DFI(){
 desktop-file-install --delete-original --vendor="" \
@@ -249,6 +276,7 @@ SB_DFI \
   --add-only-show-in="XFCE" \
   ${PKG}/usr/share/applications/xfcalendar.desktop || exit 1
 
+rm -f ${PKG}/usr/share/xsessions/xfce.desktop
 mkdir -p ${PKG}/usr/share/xsessions
 zcat ${CWD}/xfce4.desktop.gz > \
      ${PKG}/usr/share/xsessions/xfce4.desktop || exit 1
@@ -330,7 +358,8 @@ sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
 if [ "${SB_REP}" = "YES" ] ;then
   mkdir -p ${SBDIR}/{patches,profile.d}
   install -m0644 ${CWD}/slack-desc ${CWD}/slack-required ${CWD}/ChangeLog.SB \
-                 ${CWD}/apply-patches.sh ${CWD}/*.desktop.gz ${SBDIR}/
+                 ${CWD}/apply-patches.sh ${CWD}/*.desktop.gz ${CWD}/${SLKDIST} \
+                 ${SBDIR}/
   install -m0755 ${CWD}/${NAME}.SlackBuild \
                  ${SBDIR}/${NAME}.SlackBuild
   install -m0644 ${CWD}/patches/* \
