attica, automake, e16, qimageblitz, eet, eina, flash-player, gflash-player, google-gadgets, iptables, libcapseo, libcaptury, libisoburn, libssh, openbox. qedje, qzion, shared-desktop-ontologies, stunnel, xfce4-clipman-plugin, xfce4-power-manager

diff --git a/gnome/gnome-session/gnome-session.SlackBuild b/gnome/gnome-session/gnome-session.SlackBuild
--- a/gnome/gnome-session/gnome-session.SlackBuild
+++ b/gnome/gnome-session/gnome-session.SlackBuild
@@ -56,7 +56,7 @@ else
   SLKTARGET=${SLKTARGET:-i486}
 fi
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-3}
+BUILD=${BUILD:-4}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/gnome/${NAME}
@@ -163,19 +163,45 @@ mkdir -p ${PKG}/usr/share/gnome/autostart
 mkdir -p ${PKG}/usr/libexec
 mv ${PKG}/usr/bin/gnome-session \
    ${PKG}/usr/libexec/gnome-session || exit 1
-echo '#!/bin/sh' > ${PKG}/usr/bin/gnome-session
 
 cat > ${PKG}/usr/bin/gnome-session <<'EOF'
 #!/bin/sh
+
+if [ -f ~/.gnomerc ]; then 
+ source ~/.gnomerc
+else
+ source /etc/gnome/gnomerc
+fi
+
+# clean up old sockets if any
+[ -x /usr/bin/linc-cleanup-sockets ] && /usr/bin/linc-cleanup-sockets 2> /dev/null > /dev/null
+
+exec /usr/libexec/gnome-session $
+EOF
+chmod 0755 ${PKG}/usr/bin/gnome-session || exit 1
+
+mkdir -p ${PKG}/etc/gnome
+cat > ${PKG}/etc/gnome/gnomerc.new <<'EOF'
+#!/bin/sh
+
 unset CANBERRA_DRIVER
 unset CANBERRA_DEVICE
 unset SDL_AUDIODRIVER
 unset AUDIODEV
-export XDG_CONFIG_DIRS=${GNOME_XDG_CONFIG_DIRS}
 
-exec /usr/libexec/gnome-session $*
+if  [ -z "${XDG_CONFIG_DIRS}" ]; then
+  XDG_CONFIG_DIRS="/etc/gnome/xdg:/etc/xdg"
+else
+  XDG_CONFIG_DIRS="/etc/gnome/xdg:/etc/xdg:${XDG_CONFIG_DIRS}"
+fi
+export XDG_CONFIG_DIRS
+
+if [ -z "${XDG_MENU_PREFIX}" ] ; then
+  XDG_MENU_PREFIX="gnome-"
+  export XDG_MENU_PREFIX
+fi
+
 EOF
-chmod 0755 ${PKG}/usr/bin/gnome-session
 
 mkdir -p ${PKG}/etc/X11/xinit
 zcat ${CWD}/xinitrc.gnome.gz > \
@@ -242,8 +268,25 @@ if [ -x usr/bin/gconftool-2 ]; then
   \${CHROOT} /usr/bin/gconftool-2 --makefile-install-rule \\
              etc/gconf/schemas/${NAME}.schemas &> /dev/null
 fi
-
+config() {
+  NEW="\$1"
+  OLD="\$(dirname \$NEW)/\$(basename \$NEW .new)"
+  # If there's no config file by that name, mv it over:
+  if [ ! -r \$OLD ]; then
+    mv \$NEW \$OLD
+  elif [ "\$(cat \$OLD | md5sum)" = "\$(cat \$NEW | md5sum)" ]; then
+    # toss the redundant copy
+    rm \$NEW
+  fi
+  # Otherwise, we leave the .new copy for the admin to consider...
+}
+## List of conf files to check.  The conf files in your package should end in .new
 EOF
+
+( cd ${PKG}
+  find etc/ -name *.new -exec echo config {} ';' | sort >> ${PKG}/install/doinst.sh
+  echo >> ${PKG}/install/doinst.sh
+)
 
 sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
        ${PKG}/install/slack-desc
