binutils, checksec, crypto-policies, flash-player, dejavu-fonts-ttf, gcc, gkrellm-cpupower, gkrellm-freq, glibc, gmp, grep, less, libjpeg-turbo, libpng, libtiff, links, lksctp-tool, make, mpfr, nasm, ncurses, openssl, steam, tar, telegram, unicde-ucd, zoneinfo

diff --git a/grep/grep.SlackBuild b/grep/grep.SlackBuild
--- a/grep/grep.SlackBuild
+++ b/grep/grep.SlackBuild
@@ -3,7 +3,7 @@
 # Build script by Phantom X <megaphantomx at bol.com.br>
 # Suggested usage: $ grep.SlackBuild 2>&1 | tee build.log
 #--
-# Copyright 2008-2015 Phantom X, Goiania, Brazil.
+# Copyright 2008-2016 Phantom X, Goiania, Brazil.
 # Copyright 2006 Martijn Dekker, Groningen, Netherlands.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -43,8 +43,8 @@ fi
 NAME=grep
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-2.21}
-PVER=${PVER:-2.21-2}
+VERSION=${VERSION:-2.27}
+PVER=${PVER:-2.27-1}
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
 else
@@ -56,7 +56,7 @@ else
   SLKTARGET=${SLKTARGET:-i586}
 fi
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-2}
+BUILD=${BUILD:-1}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -84,6 +84,8 @@ for file in ${SRCARCHIVE} ${SSRCARCHIVE} ;do
   test -r ${CWD}/${file} || ${DL_PROG} ${DL_OPTS} ${DL_URL}/${file} || exit 1
 done
 test -r ${CWD}/${PSRCARCHIVE} || ${DL_PROG} ${DL_OPTS} ${PDL_URL} || exit 1
+
+[ "$1" = "--dlsrc" ] && exit 0
 
 if [ "${SB_NATIVE}" = "YES" ] ;then
   SLKCFLAGS="-O2 -march=native -mtune=native -pipe"
@@ -168,31 +170,24 @@ mkdir -p ${PKG}/usr/bin
   ln -sf ../../bin/rgrep .
 )
 
+### Fedora
 mkdir -p ${PKG}/etc/profile.d
 cat > ${PKG}/etc/profile.d/colorgrep.sh.new <<'EOF'
 # color-grep initialization
 
-# Skip the rest for noninteractive shells.
-[ -z "$PS1" ] && return
-
-if [ -r /etc/GREP_COLORS ]; then
-  grep -qi "^COLOR.*none" /etc/GREP_COLORS >/dev/null 2>/dev/null && return
-fi
+/usr/libexec/grepconf.sh -c || return
 
 alias grep='grep --color=auto' 2>/dev/null
 alias egrep='egrep --color=auto' 2>/dev/null
+alias fgrep='fgrep --color=auto' 2>/dev/null
 EOF
 
 cat > ${PKG}/etc/profile.d/colorgrep.csh.new <<'EOF'
 # color-grep initialization
 
-if ( -r /etc/GREP_COLORS ) then
-    set color_none=`sed -n '/^COLOR.*none/Ip' < /etc/GREP_COLORS`
-    if ( "$color_none" != '' ) then
-        unset color_none
-        exit
-    endif
-    unset color_none
+/usr/libexec/grepconf.sh -c
+if ( $status == 1 ) then
+    exit
 endif
 
 alias grep 'grep --color=auto'
@@ -201,6 +196,24 @@ alias fgrep 'fgrep --color=auto'
 EOF
 
 chmod 0755 ${PKG}/etc/profile.d/colorgrep.*
+
+mkdir -p ${PKG}/usr/libexec
+cat > ${PKG}/usr/libexec/grepconf.sh <<'EOF'
+#!/bin/sh
+
+case "$1" in
+  -c | --interactive-color)
+    ! grep -qsi "^COLOR.*none" /etc/GREP_COLORS
+    ;;
+  *)
+    echo >&2 "Invalid / no option passed, so far only -c | --interactive-color is supported."
+    exit 1
+    ;;
+esac
+EOF
+chmod 0755 ${PKG}/usr/libexec/grepconf.sh || exit 1
+
+install -pm 0644 ${CWD}/GREP_COLORS ${PKG}/etc/GREP_COLORS.new || exit 1
 
 # Add a documentation directory:
 mkdir -p ${DOCDIR}
@@ -295,16 +308,17 @@ if [ "${SB_REP}" = "YES" ] ;then
   # Replicate slackbuild and patches
   mkdir -p ${SBDIR}/patches
   install -m0644 ${CWD}/slack-desc ${CWD}/slack-required ${CWD}/ChangeLog.SB \
-                 ${CWD}/apply-patches.sh ${SBDIR}/
+    ${CWD}/apply-patches.sh GREP_COLORS ${SBDIR}/
   install -m0755 ${CWD}/${NAME}.SlackBuild \
-                 ${SBDIR}/${NAME}.SlackBuild
+    ${SBDIR}/${NAME}.SlackBuild
   install -m0644 ${CWD}/patches/*.* \
-                 ${SBDIR}/patches/
+    ${SBDIR}/patches/
   rmdir ${SBDIR}/patches
 fi
 
 # Build package:
 set +o xtrace        # no longer print commands upon execution
+set -e
 
 ROOTCOMMANDS="set -o errexit -o xtrace ; cd ${PKG} ;
   /bin/chown --recursive root:root .  ;"
@@ -319,8 +333,8 @@ elif test "$(type -t fakeroot)" = 'file'; then
   echo -e "\e[1mEntering fakeroot environment.\e[0m"
   echo ${ROOTCOMMANDS} | fakeroot
 else
-  echo -e "\e[1mPlease enter your root password.\e[0m (Consider installing fakeroot.)"
-  /bin/su -c "${ROOTCOMMANDS}"
+  echo -e "\e[1mPlease preferably install fakeroot or run as root.\e[0m"
+  exit 5
 fi
 
 # Clean up the extra stuff:
