gimp-dds-plugin, gmp, KDE SC, libsidplayfp, pam, patchelf, pinfo, sane, sddm, sudo, tcl-pgtc, unrar, util-linux, webkitgtk*
Initial pam support, login and desktop managers working.

diff --git a/networkmanager/networkmanager.SlackBuild b/networkmanager/networkmanager.SlackBuild
--- a/networkmanager/networkmanager.SlackBuild
+++ b/networkmanager/networkmanager.SlackBuild
@@ -47,7 +47,7 @@ PNAME=NetworkManager
 NAME=networkmanager
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-0.9.8.4}
+VERSION=${VERSION:-0.9.8.6}
 PPPDVER=${PPPDVER:-2.4.5}
 SVER=$(echo ${VERSION} | cut -d . -f1-2)
 if [ "${SB_NATIVE}" = "YES" ] ;then
@@ -61,7 +61,7 @@ else
   SLKTARGET=${SLKTARGET:-i486}
 fi
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -71,6 +71,8 @@ PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
 
 # Set to YES to build with nss instead gnutls
 SB_NSS=${SB_NSS:-YES}
+# Set to YES to enable systemd session support instead consolekit/needs pam
+SB_SYSTEMD=${SB_SYSTEMD:-YES}
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
@@ -132,10 +134,16 @@ if [ -r ${CWD}/apply-patches.sh ]; then
   . ${CWD}/apply-patches.sh || exit 1
 fi
 
+if ! [ -d /usr/lib${LIBDIRSUFFIX}/pppd/${PPPDVER} ] ;then
+  echo "Missing /usr/lib${LIBDIRSUFFIX}/pppd/${PPPDVER}"
+  echo "Check PPPDVER or ppp installed and try again"
+fi
+
 sed -i -e '/^Alias=/aAlias=network.service' data/${PNAME}.service.in || exit 1
 
-unset SB_NSSOPTS
+unset SB_NSSOPTS SB_SYSTEMDOPTS
 [ "${SB_NSS}" = "YES" ] || SB_NSSOPTS=gnutls
+[ "${SB_SYSTEMD}" = "YES" ] && SB_SYSTEMDOPTS=systemd
 
 CFLAGS="${SLKCFLAGS}" \
 CXXFLAGS="${SLKCFLAGS}" \
@@ -163,8 +171,8 @@ CXXFLAGS="${SLKCFLAGS}" \
   --enable-more-warnings=no \
   --with-system-ca-path=${SB_CABDIR} \
   --with-dist-version=${BUILD}${PACKAGER_ID} \
-  --with-session-tracking=consolekit \
-  --with-suspend-resume=upower \
+  --with-session-tracking=${SB_SYSTEMDOPTS:-consolekit} \
+  --with-suspend-resume=${SB_SYSTEMDOPTS:-upower} \
   --with-systemdsystemunitdir=/lib/systemd/system \
   --build=${SLKTARGET}-${SLKDTARGET}-linux || exit $?
 
