x86_64 batch #13

diff --git a/gtk-vnc/gtk-vnc.SlackBuild b/gtk-vnc/gtk-vnc.SlackBuild
--- a/gtk-vnc/gtk-vnc.SlackBuild
+++ b/gtk-vnc/gtk-vnc.SlackBuild
@@ -47,6 +47,7 @@ PKG=${PKGF}/${NAME}
 PKG2=${PKGF}/${NAME2}
 
 VERSION=${VERSION:-0.3.8}
+SVER=$(echo ${VERSION} | cut -d . -f1-2)
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
 else
@@ -58,7 +59,7 @@ else
   SLKTARGET=${SLKTARGET:-i486}
 fi
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 NJOBS=${NJOBS:-2}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -74,13 +75,11 @@ SRCARCHIVE=${SRCDIR}.tar.gz
 
 DL_TO=${DL_TO:-5}
 DL_OPTS=${DL_OPTS:-"--timeout=${DL_TO}"}
-SF_MIRROR=${SF_MIRROR:-http://prdownloads.sourceforge.net}
-DL_URL="${SF_MIRROR}/${NAME}/${SRCARCHIVE}"
+GNOME_MIRROR=${GNOME_MIRROR:-http://ftp.gnome.org/pub/GNOME/sources}
+DL_URL="${GNOME_MIRROR}/${NAME}/${SVER}/${SRCARCHIVE}"
 
-# if source is not present, download in source rootdir if possible, or in /tmp
-if ! test -r ${SRCARCHIVE}; then
-  test -r ${CWD}/${SRCARCHIVE} || wget ${DL_OPTS} ${DL_URL} || exit 1
-fi
+# if source is not present, download in source rootdir if possible
+test -r ${CWD}/${SRCARCHIVE} || wget ${DL_OPTS} ${DL_URL} || exit 1
 
 if [ "${SB_NATIVE}" = "YES" ] ;then
   SLKCFLAGS="-O2 -march=native -mtune=native ${SB_ECFLAGS} -pipe"
@@ -94,53 +93,64 @@ else
                  ;;
   esac
 fi
-
-if [ -d ${PKGF} ]; then
-  # Clean up a previous build
-  rm -rf ${PKGF}
+if [ "${ARCH}" = "x86_64" ] ;then
+  LIBDIRSUFFIX="64"
+else
+  LIBDIRSUFFIX=""
 fi
-mkdir -p ${PKG} ${PKG2}
+
+if [ -d ${PKG} ]; then
+  # Clean up a previous build
+  rm -rf ${PKG}
+fi
+mkdir -p ${PKG}
 
 cd ${TMP}
 rm -rf ${SRCDIR}
-if $(file -L ${CWD}/${SRCARCHIVE} | grep -q ": bzip2"); then
-  tar -xjvf ${CWD}/${SRCARCHIVE} || exit 1
-elif $(file -L ${CWD}/${SRCARCHIVE} | grep -q ": gzip"); then
-  tar -xzvf ${CWD}/${SRCARCHIVE} || exit 1
-fi
+tar -xvf ${CWD}/${SRCARCHIVE} || exit 1
 cd ${SRCDIR} || exit 1
 
 chmod -R u+w,go+r-w,a-s .
 
 # zcat ${CWD}/${NAME}.patch.gz | patch -p0 -E --backup --verbose || exit 1
+if [ -r ${CWD}/apply-patches.sh ]; then
+  . ${CWD}/apply-patches.sh || exit 1
+fi
+
+libtoolize --copy --force || exit 1
+aclocal -I gnulib/m4 || exit 1
+autoheader || exit 1
+automake --add-missing --copy || exit 1
+autoconf || exit 1
 
 CFLAGS="${SLKCFLAGS}" \
 CXXFLAGS="${SLKCFLAGS}" \
 ./configure \
   --prefix=/usr \
+  --libdir=/usr/lib${LIBDIRSUFFIX} \
   --sysconfdir=/etc \
   --localstatedir=/var/lib \
   --infodir=/usr/info \
   --mandir=/usr/man \
   --disable-static \
   --with-python \
-  --enable-plugin=yes \
+  --enable-plugin=no \
   --build=${SLKTARGET}-${SLKDTARGET}-linux || exit 1
 
 make -j${NJOBS} || make || exit 1
 make install DESTDIR=${PKG} || exit 1
 
-rm -f ${PKG}/usr/lib/*.{a,la}
-rm -f ${PKG}/usr/lib/python*/site-packages/*.{a,la}
-rm -f ${PKG}/usr/lib/mozilla/plugins/*.{a,la}
+rm -f ${PKG}/usr/lib*/*.{a,la}
+rm -f ${PKG}/usr/lib*/python*/site-packages/*.{a,la}
+rm -f ${PKG}/usr/lib*/mozilla/plugins/*.{a,la}
 
 find ${PKG} | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 
-if [ -d ${PKG}/usr/lib/mozilla ] ;then
-  mkdir -p ${PKG2}/usr/lib
-  mv ${PKG}/usr/lib/mozilla \
-     ${PKG2}/usr/lib/ || exit 1
+if [ -d ${PKG}/usr/lib${LIBDIRSUFFIX}/mozilla ] ;then
+  mkdir -p ${PKG2}/usr/lib${LIBDIRSUFFIX}
+  mv ${PKG}/usr/lib${LIBDIRSUFFIX}/mozilla \
+     ${PKG2}/usr/lib${LIBDIRSUFFIX}/ || exit 1
 fi
 
 # Add a documentation directory:
@@ -184,11 +194,13 @@ sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
 
 if [ "${SB_REP}" = "YES" ] ;then
   # Replicate slackbuild and patches
-  mkdir -p ${SBDIR}
+  mkdir -p ${SBDIR}/patches
   install -m0644 ${CWD}/slack-desc ${CWD}/slack-required ${CWD}/ChangeLog.SB \
-                 ${CWD}/${NAME}-*.patch.gz ${SBDIR}/
+                 ${CWD}/apply-patches.sh ${SBDIR}/
   install -m0755 ${CWD}/${NAME}.SlackBuild \
                  ${SBDIR}/${NAME}.SlackBuild
+  install -m0644 ${CWD}/patches/*.gz \
+                 ${SBDIR}/patches/
 fi
 
 # Build package:
