Updates for the future

diff --git a/fakeroot/fakeroot.SlackBuild b/fakeroot/fakeroot.SlackBuild
--- a/fakeroot/fakeroot.SlackBuild
+++ b/fakeroot/fakeroot.SlackBuild
@@ -3,7 +3,7 @@
 # Build script by Phantom X <megaphantomx at bol.com.br>
 # Suggested usage: $ fakeroot.SlackBuild 2>&1 | tee build.log
 #--
-# Copyright 2008-2015 Phantom X, Goiania, Brazil.
+# Copyright 2008-2016 Phantom X, Goiania, Brazil.
 # Copyright 2006 Martijn Dekker, Groningen, Netherlands.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -235,8 +235,8 @@ elif test "$(type -t ${PKG}/usr/bin/fakeroot-sysv)" = 'file'; then
   echo -e "\e[1mEntering fakeroot environment.\e[0m"
   echo ${ROOTCOMMANDS} | ${PKG}/usr/bin/fakeroot-sysv --lib ${PKG}/usr/lib${LIBDIRSUFFIX}/libfakeroot/libfakeroot-sysv.so --faked ${PKG}/usr/bin/faked-sysv
 else
-  echo -e "\e[1mPlease enter your root password.\e[0m (Consider installing fakeroot.)"
-  /bin/su -c "${ROOTCOMMANDS}"
+  echo -e "Packaging failed."
+  exit 5
 fi
 
 # Clean up the extra stuff:
