Some fixes in samples.

diff --git a/fakeroot/fakeroot.SlackBuild b/fakeroot/fakeroot.SlackBuild
--- a/fakeroot/fakeroot.SlackBuild
+++ b/fakeroot/fakeroot.SlackBuild
@@ -235,7 +235,8 @@ elif test "$(type -t ${PKG}/usr/bin/fakeroot-sysv)" = 'file'; then
   echo -e "\e[1mEntering fakeroot environment.\e[0m"
   echo ${ROOTCOMMANDS} | ${PKG}/usr/bin/fakeroot-sysv --lib ${PKG}/usr/lib${LIBDIRSUFFIX}/libfakeroot/libfakeroot-sysv.so --faked ${PKG}/usr/bin/faked-sysv
 else
-  echo -e "Packaging failed."
+  echo -e "\e[1mPackaging failed.\e[0m"
+  exit 5
   exit 5
 fi
 
