bluez, fluxbox-chinfo-menu, fontforge, git, graphite2, kernel-custom, libindi, libfm-extra, mesa, pkg-config, qastools, unrar, volti, xdgmenumaker, xz

diff --git a/lxde/libfm/libfm.SlackBuild b/lxde/libfm/libfm.SlackBuild
--- a/lxde/libfm/libfm.SlackBuild
+++ b/lxde/libfm/libfm.SlackBuild
@@ -3,7 +3,7 @@
 # Build script by Phantom X <megaphantomx at bol.com.br>
 # Suggested usage: $ libfm.SlackBuild 2>&1 | tee build.log
 #--
-# Copyright 2008-2014 Phantom X, Goiania, Brazil.
+# Copyright 2008-2015 Phantom X, Goiania, Brazil.
 # Copyright 2006 Martijn Dekker, Groningen, Netherlands.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -62,7 +62,7 @@ else
   SLKTARGET=${SLKTARGET:-i586}
 fi
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/lxde/${NAME}
@@ -78,6 +78,11 @@ SB_BROWSERD=${SB_BROWSERD:-mozilla-firefox}
 SB_MAILD=${SB_MAILD:-mozilla-thunderbird}
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
+
+if [ "$(pkg-config --modversion libfm-extra)" != "${VERSION}" ] ;then
+  echo "libfm-extra = ${VERSION} must be installed!"
+  exit 1
+fi
 
 SRCDIR=${NAME}-${VERSION}
 SRCARCHIVE=${SRCDIR}.tar.xz
@@ -158,6 +163,7 @@ CXXFLAGS="${SLKCFLAGS}" \
   --mandir=/usr/man \
   --docdir=/usr/doc/${NAME}-${VERSION} \
   --disable-silent-rules \
+  --disable-dependency-tracking \
   --disable-static \
   --with-gtk=3 \
   --enable-udisks \
@@ -173,12 +179,21 @@ rmdir -p ${PKG}/usr/lib*/gio/modules
 
 rm -f ${PKG}/usr/lib*/pkgconfig/libfm-gtk.pc
 
-for file in ${PKG}/etc/xdg/*/*.conf ;do
-  mv ${file} ${file}.new || exit 1
+# libfm-extra cleanup
+rm -f ${PKG}/usr/include/libfm
+rm -f ${PKG}/usr/lib*/libfm-extra.*
+rm -f ${PKG}/usr/lib*/pkgconfig/libfm-extra.pc
+
+for i in fm-extra fm-version fm-xml-file ;do
+  rm -fv ${PKG}/usr/include/libfm*/${i}.h || exit 1
 done
 
 find ${PKG} | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+
+for file in ${PKG}/etc/xdg/*/*.conf ;do
+  mv ${file} ${file}.new || exit 1
+done
 
 # Add a documentation directory:
 mkdir -p ${DOCDIR}
@@ -213,7 +228,7 @@ fi
 
 mkdir -p ${PKG}/install
 cat ${CWD}/slack-desc > ${PKG}/install/slack-desc
-cat ${CWD}/slack-required > ${PKG}/install/slack-required
+sed "s|_VER_|${VERSION}|g" ${CWD}/slack-required > ${PKG}/install/slack-required
 
 cat > ${PKG}/install/doinst.sh <<EOF
 #!/bin/sh
