acpid, avidemux, bind, blender, calligra, dosfstools, ffmpeg, gstreamer-vaapi, gupnp, gupnp-{av,dlna}, iotop, iptables, kdevelop, kdevplatform, kdevelop-php, lftp, mc, nettle, nspr, nss, obexftp, openobex, pcre, procps, python, qt-creator, xine-lib, libva-vdpau-driver, libxcb, xkeyboard-config

diff --git a/bind/patches/bind-9.9.1-P2-multlib-conflict.patch b/bind/patches/bind-9.9.1-P2-multlib-conflict.patch
--- a/bind/patches/bind-9.9.1-P2-multlib-conflict.patch
+++ b/bind/patches/bind-9.9.1-P2-multlib-conflict.patch
@@ -1,7 +1,7 @@
-diff -up bind-9.9.1-P2/config.h.in.multlib-conflict bind-9.9.1-P2/config.h.in
---- bind-9.9.1-P2/config.h.in.multlib-conflict	2012-08-01 14:07:40.300605215 +0200
-+++ bind-9.9.1-P2/config.h.in	2012-08-01 14:08:06.449526607 +0200
-@@ -400,7 +400,7 @@ int sigwait(const unsigned int *set, int
+diff -up bind-9.9.3rc2/config.h.in.multlib-conflict bind-9.9.3rc2/config.h.in
+--- bind-9.9.3rc2/config.h.in.multlib-conflict	2013-04-30 08:38:46.000000000 +0200
++++ bind-9.9.3rc2/config.h.in	2013-05-13 12:10:22.514870894 +0200
+@@ -416,7 +416,7 @@ int sigwait(const unsigned int *set, int
  #undef PORT_NONBLOCK
  
  /* The size of `void *', as computed by sizeof. */
@@ -10,10 +10,10 @@ diff -up bind-9.9.1-P2/config.h.in.multlib-conflict bind-9.9.1-P2/config.h.in
  
  /* Define to 1 if you have the ANSI C header files. */
  #undef STDC_HEADERS
-diff -up bind-9.9.1-P2/configure.in.multlib-conflict bind-9.9.1-P2/configure.in
---- bind-9.9.1-P2/configure.in.multlib-conflict	2012-08-01 13:25:04.871278041 +0200
-+++ bind-9.9.1-P2/configure.in	2012-08-01 13:25:08.705266546 +0200
-@@ -2102,7 +2102,9 @@ int getnameinfo(const struct sockaddr *,
+diff -up bind-9.9.3rc2/configure.in.multlib-conflict bind-9.9.3rc2/configure.in
+--- bind-9.9.3rc2/configure.in.multlib-conflict	2013-05-13 12:10:22.481870901 +0200
++++ bind-9.9.3rc2/configure.in	2013-05-13 12:10:22.515870894 +0200
+@@ -2251,7 +2251,9 @@ int getnameinfo(const struct sockaddr *,
                  size_t, char *, size_t, int);],
  [ return (0);],
  	[AC_MSG_RESULT(size_t for buflen; int for flags)
@@ -24,15 +24,14 @@ diff -up bind-9.9.1-P2/configure.in.multlib-conflict bind-9.9.1-P2/configure.in
  	 AC_DEFINE(IRS_GETNAMEINFO_FLAGS_T, int)],
  [AC_MSG_RESULT(not match any subspecies; assume standard definition)
  AC_DEFINE(IRS_GETNAMEINFO_BUFLEN_T, socklen_t)
-diff -up bind-9.9.1-P2/isc-config.sh.in.multlib-conflict bind-9.9.1-P2/isc-config.sh.in
---- bind-9.9.1-P2/isc-config.sh.in.multlib-conflict	2012-08-01 10:30:18.414494493 +0200
-+++ bind-9.9.1-P2/isc-config.sh.in	2012-08-01 14:12:11.696789273 +0200
-@@ -20,8 +20,19 @@
- prefix=@prefix@
+diff -up bind-9.9.3rc2/isc-config.sh.in.multlib-conflict bind-9.9.3rc2/isc-config.sh.in
+--- bind-9.9.3rc2/isc-config.sh.in.multlib-conflict	2013-04-30 08:38:46.000000000 +0200
++++ bind-9.9.3rc2/isc-config.sh.in	2013-05-13 12:26:40.258698745 +0200
+@@ -21,7 +21,18 @@ prefix=@prefix@
  exec_prefix=@exec_prefix@
  exec_prefix_set=
--libdir=@libdir@
  includedir=@includedir@
+-libdir=@libdir@
 +arch=$(uname -m)
 +
 +case $arch in
@@ -48,20 +47,20 @@ diff -up bind-9.9.1-P2/isc-config.sh.in.multlib-conflict bind-9.9.1-P2/isc-confi
  
  usage()
  {
-@@ -124,6 +135,16 @@ if test x"$echo_cflags" = x"true"; then
- 	echo $includes
- fi
- if test x"$echo_libs" = x"true"; then
-+	if [ ! -x $libdir/libisc.so ] ; then
-+		if [ ! -x $sec_libdir/libisc.so ] ; then
-+			echo "Error: ISC libs not found in $libdir"
-+			if [ -d $sec_libdir ] ; then
-+				echo "Error: ISC libs not found in $sec_libdir"
+@@ -133,6 +144,16 @@ if test x"$echo_libs" = x"true"; then
+ 	if test x"${exec_prefix_set}" = x"true"; then
+ 		includes="-L${exec_prefix}/lib"
+ 	else
++		if [ ! -x $libdir/libisc.so ] ; then
++			if [ ! -x $sec_libdir/libisc.so ] ; then
++				echo "Error: ISC libs not found in $libdir"
++				if [ -d $sec_libdir ] ; then
++					echo "Error: ISC libs not found in $sec_libdir"
++				fi
++				exit 1
 +			fi
-+			exit 1
++			libdir=$sec_libdir
 +		fi
-+		libdir=$sec_libdir
-+	fi
- 	libs="-L${libdir}"
+ 		libs="-L${libdir}"
+ 	fi
  	if test x"$liblwres" = x"true" ; then
- 		libs="$libs -llwres"
