consolekit, gdbm, gmime, leafpad, imagemagick, lbreakout2, lmarbles, ltris, nautilus-actions, vte

diff --git a/libtool/libtool.SlackBuild b/libtool/libtool.SlackBuild
--- a/libtool/libtool.SlackBuild
+++ b/libtool/libtool.SlackBuild
@@ -55,7 +55,7 @@ else
   SLKTARGET=${SLKTARGET:-i486}
 fi
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-5}
+BUILD=${BUILD:-6}
 NJOBS=${NJOBS:-2}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -113,6 +113,8 @@ if [ -r ${CWD}/apply-patches.sh ]; then
   . ${CWD}/apply-patches.sh || exit 1
 fi
 
+export CONFIG_SHELL=/bin/bash
+
 CC=gcc \
 LTCC=gcc \
 CXX=g++ \
@@ -133,6 +135,34 @@ make install DESTDIR=${PKG} || exit 1
 
 find ${PKG} | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+
+if [ "${ARCH}" = "x86_64" ] ;then
+  mv ${PKG}/usr/bin/${NAME} ${PKG}/usr/bin/${NAME}-64 || exit 1
+
+cat > ${PKG}/usr/bin/${NAME} <<EOF
+#!/bin/sh
+# Wrapper for multilib
+# If want use 32 bit version, run as "linux32 ${NAME}"
+
+host="\$(uname -m)"
+
+case "\${host}" in
+  x86_64|s390x)
+    exec /usr/bin/${NAME}-64 "\$@"
+    ;;
+  i[3-6]86|athlon|s390|*)
+    if [ -x /usr/bin/${NAME}-32 ] ;then
+      exec /usr/bin/${NAME}-32 "\$@"
+    else
+      echo 'Command /usr/bin/${NAME}-32 not found!'
+      exit 1
+    fi
+    ;;
+esac
+
+EOF
+chmod 0755 ${PKG}/usr/bin/${NAME} || exit 1
+fi
 
 # Add a documentation directory:
 mkdir -p ${DOCDIR}
