dos2unix, filezilla, gnuchess, harfbuzz, oxygen-fonts, screen, synergy, system-config-language, tack

diff --git a/synergy/synergy.SlackBuild b/synergy/synergy.SlackBuild
--- a/synergy/synergy.SlackBuild
+++ b/synergy/synergy.SlackBuild
@@ -40,7 +40,7 @@ TMP=${TMP:-/tmp}
 NAME=synergy
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-1.7.3}
+VERSION=${VERSION:-1.7.4}
 RVER=$(echo ${VERSION} | cut -d- -f1)
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
@@ -53,7 +53,7 @@ else
   SLKTARGET=${SLKTARGET:-i486}
 fi
 SLKDIST=${SLKDIST:-Slackware}
-BUILD=${BUILD:-2}
+BUILD=${BUILD:-1}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -109,9 +109,9 @@ fi
 # Set the config option variables if they are not already set:
 [ -r ../qt4.options ] && source ../qt4.options
 
-_qt4_prefix=${_qt4_prefix:-/usr/lib${LIBDIRSUFFIX}/qt4}
-_qt4_bindir=${_qt4_bindir:-${_qt4_prefix}/bin}
-_qt4_qmake=${_qt4_qmake:-${_qt4_bindir}/qmake}
+_qt5_prefix=${_qt5_prefix:-/usr/lib${LIBDIRSUFFIX}/qt5}
+_qt5_bindir=${_qt5_bindir:-${_qt5_prefix}/bin}
+_qt5_qmake=${_qt5_qmake:-${_qt5_bindir}/qmake}
 
 if [ ! -d ${TMP} ]; then
   mkdir -p ${TMP}
@@ -123,8 +123,8 @@ fi
 mkdir -p ${PKG}
 
 unset QTDIR QTINC QTLIB
-export QTDIR=$(${_qt4_qmake} -query QT_INSTALL_PREFIX)
-PATH="$(${_qt4_qmake} -query QT_INSTALL_BINS)${PATH:+:${PATH}}" ; export PATH
+export QTDIR=$(${_qt5_qmake} -query QT_INSTALL_PREFIX)
+PATH="$(${_qt5_qmake} -query QT_INSTALL_BINS)${PATH:+:${PATH}}" ; export PATH
 
 cd ${TMP}
 rm -rf ${SRCDIR}
@@ -172,24 +172,73 @@ mkdir -p build
 
 ) || exit $?
 
-mkdir -p ${PKG}/usr/bin
-install -pm0755 bin/${NAME}{c,d,s} bin/u${NAME} bin/syntool ${PKG}/usr/bin/ || exit $?
-
-mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}
-install -pm0755 bin/plugins/libns.so ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/ || exit $?
+mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/plugins
+install -pm0755 bin/${NAME}{c,d,s} bin/u${NAME} bin/syntool ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/ || exit $?
+install -pm0755 bin/plugins/libns.so ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/plugins/ || exit $?
 
 if [ "${SB_GUI}" = "YES" ] ;then
   ( cd src/gui
-    ${_qt4_qmake} gui.pro PREFIX=/usr || exit $?
+    ${_qt5_qmake} gui.pro PREFIX=/usr || exit $?
     make -j${NJOBS} || make
   ) || exit $?
 
-  install -pm0755 bin/${NAME} ${PKG}/usr/bin/ || exit $?
+  install -pm0755 bin/${NAME} ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/ || exit $?
 
 fi
 
 find ${PKG} | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+
+mkdir -p ${PKG}/usr/bin
+cat > ${PKG}/usr/bin/${NAME} <<'EOF'
+#!/bin/sh
+
+set -e
+
+SYN_BIN="$(basename $0)"
+SYN_BIN="${SYN_BIN##/*/}"
+
+SYN_ARCH=$(uname -m)
+case ${SYN_ARCH} in
+  x86_64 | ia64 | s390 )
+    LIB_DIR="/usr/lib64"
+    SECONDARY_LIB_DIR="/usr/lib"
+    ;;
+  * )
+    LIB_DIR="/usr/lib"
+    SECONDARY_LIB_DIR="/usr/lib64"
+    ;;
+esac
+if [ ! -x ${LIB_DIR}/synergy/synergy ]; then
+  if [ ! -x ${SECONDARY_LIB_DIR}/synergy/synergy ]; then
+    echo "Error: ${LIB_DIR}/synergy/synergy not found"
+    if [ -d ${SECONDARY_LIB_DIR} ]; then
+      echo "       ${SECONDARY_LIB_DIR}/synergy/synergy not found"
+    fi
+    exit 1
+  fi
+  LIB_DIR="${SECONDARY_LIB_DIR}"
+fi
+
+mkdir -p ~/.synergy/plugins
+cd ~/.synergy
+cleanlinks
+
+mkdir -p ~/.synergy/plugins
+for plugin in $(find "${LIB_DIR}/synergy/plugins"  -maxdepth 1 -type f -printf '%f ') ; do
+  if [[ ! -e "plugins/${plugin}" ]] ; then
+    echo "Loading new plugin: ${plugin}"
+    ln -s "${LIB_DIR}/synergy/plugins/${plugin}" "plugins/${plugin}"
+  fi
+done
+
+exec "${LIB_DIR}/synergy/${SYN_BIN}" "$@"
+EOF
+chmod 0755 ${PKG}/usr/bin/${NAME} || exit 1
+
+for i in ${NAME}{c,d,s} u${NAME} syntool ;do
+  ln -sf ${NAME} ${PKG}/usr/bin/${i} || exit 1
+done
 
 mkdir -p ${PKG}/usr/man/man1
 for man in ${NAME}{c,s} ;do
