alsa-{lib,plugins,tools,utils}, pyalsa, autoconf-archive, bind, cabextract, curl, enlightenment, git, gnutls, gtk+3, calligra, libindi, libreoffice, mpg123, openscenegraph, sqlite, xz

diff --git a/sqlite/sqlite-compat32.SlackBuild b/sqlite/sqlite-compat32.SlackBuild
--- a/sqlite/sqlite-compat32.SlackBuild
+++ b/sqlite/sqlite-compat32.SlackBuild
@@ -45,8 +45,14 @@ PNAME=sqlite
 NAME=sqlite-compat32
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-3080802}
-OLDVER="$(echo ${VERSION} | cut -b 1 ).$(echo ${VERSION} | cut -b 2,3 | sed 's|^0||g').$(echo ${VERSION} | cut -b 4,5 | sed 's|^0||g').$(echo ${VERSION} | cut -b 6,7 | sed 's|^0||g')"
+# w.x.y.z / z=0 when not existent in tarball, eg. 3.8.8 will be 3.8.8.0
+VERSION=${VERSION:-3.8.8.3}
+#OLDVER="$(echo ${VERSION} | cut -b 1 ).$(echo ${VERSION} | cut -b 2,3 | sed 's|^0||g').$(echo ${VERSION} | cut -b 4,5 | sed 's|^0||g').$(echo ${VERSION} | cut -b 6,7 | sed 's|^0||g')"
+if [ -z "$( echo ${VERSION} | cut -d . -f 4 )" ] ;then
+  echo "Missing sublevel in VERSION: ${VERSION}.?!"
+  exit 1
+fi
+RVER=${VERSION//./0}
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH32=${ARCH32:-$(linux32 uname -m)}
 else
@@ -65,7 +71,7 @@ SB_ICU=${SB_ICU:-NO}
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
-SRCDIR=${PNAME}-src-${VERSION}
+SRCDIR=${PNAME}-src-${RVER}
 SRCARCHIVE=${SRCDIR}.zip
 
 DL_PROG=${DL_PROG:-wget}
@@ -107,7 +113,7 @@ if [ -r ${CWD}/apply-patches.sh ]; then
   . ${CWD}/apply-patches.sh
 fi
 
-echo "${OLDVER}"
+echo "${RVER}"
 
 autoreconf -ivf || exit 1
 
diff --git a/sqlite/sqlite.SlackBuild b/sqlite/sqlite.SlackBuild
--- a/sqlite/sqlite.SlackBuild
+++ b/sqlite/sqlite.SlackBuild
@@ -44,8 +44,14 @@ fi
 NAME=sqlite
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-3080802}
-OLDVER="$(echo ${VERSION} | cut -b 1 ).$(echo ${VERSION} | cut -b 2,3 | sed 's|^0||g').$(echo ${VERSION} | cut -b 4,5 | sed 's|^0||g').$(echo ${VERSION} | cut -b 6,7 | sed 's|^0||g')"
+# w.x.y.z / z=0 when not existent in tarball, eg. 3.8.8 will be 3.8.8.0
+VERSION=${VERSION:-3.8.8.3}
+#OLDVER="$(echo ${VERSION} | cut -b 1 ).$(echo ${VERSION} | cut -b 2,3 | sed 's|^0||g').$(echo ${VERSION} | cut -b 4,5 | sed 's|^0||g').$(echo ${VERSION} | cut -b 6,7 | sed 's|^0||g')"
+if [ -z "$( echo ${VERSION} | cut -d . -f 4 )" ] ;then
+  echo "Missing sublevel in VERSION: ${VERSION}.?!"
+  exit 1
+fi
+RVER=${VERSION//./0}
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
 else
@@ -72,8 +78,8 @@ SB_ICU=${SB_ICU:-NO}
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
-SRCDIR=${NAME}-src-${VERSION}
-DSRCDIR=${NAME}-doc-${VERSION}
+SRCDIR=${NAME}-src-${RVER}
+DSRCDIR=${NAME}-doc-${RVER}
 SRCARCHIVE=${SRCDIR}.zip
 DSRCARCHIVE=${DSRCDIR}.zip
 
@@ -128,7 +134,7 @@ if [ -r ${CWD}/apply-patches.sh ]; then
   . ${CWD}/apply-patches.sh
 fi
 
-echo "${OLDVER}"
+echo "${RVER}"
 
 autoreconf -ivf || exit 1
 
