bash, cups-filters, emelfm2, freerdp, gnupg, gnutls, harfbuzz, KDE 4.9.5, krb5, libXcomposite, libXdamage, mc, mercurial, nasm, netpbm, qpdf, ristretto, soundtouch, spideroak, texlive, upower

diff --git a/spideroak/spideroak.SlackBuild b/spideroak/spideroak.SlackBuild
--- a/spideroak/spideroak.SlackBuild
+++ b/spideroak/spideroak.SlackBuild
@@ -3,7 +3,7 @@
 # Build script by Phantom X <megaphantomx at bol.com.br>
 # Suggested usage: $ spideroak.SlackBuild 2>&1 | tee build.log
 #--
-# Copyright 2008-2012 Phantom X, Goiania, Brazil.
+# Copyright 2008-2013 Phantom X, Goiania, Brazil.
 # Copyright 2006 Martijn Dekker, Groningen, Netherlands.
 # All rights reserved.
 #
@@ -42,7 +42,7 @@ PNAME=SpiderOak
 NAME=spideroak
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-9948}
+VERSION=${VERSION:-4.8.3}
 # x86 or x86_64
 ARCH=${ARCH:-x86_64}
 if [ "${ARCH}" = "x86_64" ] ;then
@@ -64,18 +64,30 @@ PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
 # Set what package type to download. deb or rpm.
 SB_PACK=${SB_PACK:-deb}
 
-# Do no blame SpiderOak devs if setting YES in this
-# Set to YES to use some system libs
-SB_SYSLIBS=${SB_SYSLIBS:-YES}
-# Set to YES if system ssl library is libssl.so.1.0.0 for SB_PACK=rpm or libssl.so.0.9.8 for SB_PACK=deb
-SB_SYSSSL=${SB_SYSSSL:-NO}
+# Do no blame SpiderOak devs if setting YES in these
+# Set to YES to use system libs
+# curl
+SB_CURL=${SB_CURL:-YES}
+# python
+SB_PY=${SB_PY:-YES}
+# python-imaging - pil
+SB_PIL=${SB_PIL:-YES}
+# pyopenssl
+SB_PYOSSL=${SB_PYOSSL:-YES}
+# Set to YES if to use system Qt and PyQt
+SB_QT=${SB_QT:-YES}
+
+PYSITEARCH=$(python -c 'from distutils import sysconfig; print sysconfig.get_python_lib(1)')
+PYSITELIB=$(python -c 'from distutils import sysconfig; print sysconfig.get_python_lib()')
+PYABI=$(python -c 'import sys; print (sys.version[:3])')
+PYVER=$(python -c 'import sys; print sys.version.split(" ")[0]')
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
 SRCDIR=${NAME}-${VERSION}
 if [ "${SB_PACK}" = "deb" ] ;then
   SRCARCHIVE=${NAME}_${VERSION}_${PARCH}.deb
-  DISTRO=ubuntulucid
+  DISTRO=ubuntu
 else
   SRCARCHIVE=${PNAME}-${VERSION}-1.${ARCH}.rpm
   DISTRO=suse
@@ -84,7 +96,7 @@ fi
 DL_PROG=${DL_PROG:-wget}
 DL_TO=${DL_TO:-5}
 DL_OPTS=${DL_OPTS:-"--timeout=${DL_TO}"}
-DL_URL="https://spideroak.com/directdownload?platform=${DISTRO}&arch=${ARCH}"
+DL_URL="https://spideroak.com/getbuild?platform=${DISTRO}&arch=${ARCH}"
 
 # if source is not present, download in source rootdir if possible
 test -r ${CWD}/${SRCARCHIVE} || ${DL_PROG} ${DL_OPTS} ${DL_URL} -O ${CWD}/${SRCARCHIVE} || exit 1
@@ -96,8 +108,9 @@ if ! test -s ${CWD}/${SRCARCHIVE} ;then
 fi
 
 if [ "${SB_PACK}" = "deb" ] ;then
-  RVER="$(ar p ${CWD}/${SRCARCHIVE} control.tar.gz 2> /dev/null | tar zxO ./control 2> /dev/null | grep ^Version | awk '{print $2}' | cut -d- -f1)"
-else
+  RVER="$(ar p ${CWD}/${SRCARCHIVE} control.tar.gz 2> /dev/null | tar zxO ./control 2> /dev/null | grep ^Version | awk '{print $2}' | cut -d- -f1 | cut -d\: -f2)"
+
+elif [ "${SB_PACK}" = "rpm" ] ;then
   RVER="$(rpm -qp --qf %{version} ${CWD}/${SRCARCHIVE} 2> /dev/null)"
 fi
 if [ "${RVER}" != "${VERSION}" ] ;then
@@ -135,29 +148,103 @@ if [ -r ${CWD}/apply-patches.sh ]; then
   . ${CWD}/apply-patches.sh || exit 1
 fi
 
+mv usr/share/pixmaps/${PNAME}.png usr/share/pixmaps/${NAME}.png
+mv usr/share/applications/${PNAME}.desktop usr/share/applications/${NAME}.desktop
+
 sed -i \
   -e "/^Icon=/s|=.*$|=${NAME}|g" \
   -e "/^Exec=/s|=.*$|=${PNAME}|g" \
   usr/share/applications/${NAME}.desktop || exit 1
 
-sed -i -e "s|/lib/|/lib${LIBDIRSUFFIX}/|g" usr/bin/${PNAME} || exit 1
+sed -i -e "s|/opt/${PNAME}/lib|/usr/lib${LIBDIRSUFFIX}/${PNAME}|g" usr/bin/${PNAME} || exit 1
 
 mkdir -p ${PKG}/usr/bin
 install -pm0755 usr/bin/${PNAME} ${PKG}/usr/bin/ || exit 1
 
-mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}/${PNAME}
-if [ "${SB_SYSSSL}" != "YES" ] ;then
-  mv usr/lib/${PNAME}/lib{crypto,ssl}.so.* ${PKG}/usr/lib${LIBDIRSUFFIX}/${PNAME}/ || exit 1
+PROGDIR=/usr/lib${LIBDIRSUFFIX}/${PNAME}
+mkdir -p ${PKG}/${PROGDIR}
+
+mv opt/${PNAME}/lib/* ${PKG}/${PROGDIR}/ || exit 1
+
+rm -f ${PKG}/${PROGDIR}/lib{gcc_s,stdc++,z}.so.*
+rm -f ${PKG}/${PROGDIR}/libgssapi_krb5.so.*
+rm -f ${PKG}/${PROGDIR}/libsepol.so.*
+rm -f ${PKG}/${PROGDIR}/*/*/*.exe
+
+abs2rel(){
+  perl -e 'use File::Spec; print File::Spec->abs2rel($ARGV[0], $ARGV[1])' "$1" "$2"
+}
+
+missing(){
+  if ! [ -e "$1" ] ;then
+    echo "File $1 is missing!"
+    exit 5
+  fi
+}
+
+# curl
+if [ "${SB_CURL}" = "YES" ] ;then
+  reldir=$(abs2rel ${PYSITELIB} ${PROGDIR})
+  missing ${PYSITELIB}/pycurl.so
+  rm -f ${PKG}/${PROGDIR}/pycurl.so
+  ln -sf ${reldir}/pycurl.so ${PKG}/${PROGDIR}/pycurl.so
+  rm -f ${PKG}/${PROGDIR}/libcurl.so.*
+  rm -f ${PKG}/${PROGDIR}/libssh2.so.*
 fi
 
-rm -f usr/lib/${PNAME}/lib{gcc_s,stdc++,z}.so.*
-rm -f usr/lib/${PNAME}/*/*/*.exe
-if [ "${SB_SYSLIBS}" = "YES" ] ;then
-  rm -f usr/lib/${PNAME}/py
-  rm -f usr/lib/${PNAME}/*.so.*
+# python
+if [ "${SB_PY}" = "YES" ] ;then
+  reldir=$(abs2rel /usr/lib${LIBDIRSUFFIX}/python${PYABI}/lib-dynload ${PROGDIR})
+  for file in \
+    _bisect _codecs_cn _codecs_hk _codecs_iso2022 _codecs_jp _codecs_kr _codecs_tw \
+    _collections _ctypes _functools _hashlib _heapq _hotshot _io _json _locale \
+    _lsprof _multibytecodec _random _socket _sqlite3 _ssl _struct array binascii \
+    cPickle cStringIO datetime fcntl grp itertools math mmap operator parser \
+    pyexpat resource select strop termios time unicodedata zlib
+    do
+    missing /usr/lib${LIBDIRSUFFIX}/python${PYABI}/lib-dynload/${file}.so
+    rm -f ${PKG}/${PROGDIR}/${file}.so
+    ln -sf ${reldir}/${file}.so ${PKG}/${PROGDIR}/${file}.so
+    rm -f ${PKG}/${PROGDIR}/py
+    rm -f ${PKG}/${PROGDIR}/libexpat.so.*
+    rm -f ${PKG}/${PROGDIR}/libsqlite3.so.*
+  done
 fi
 
-cp -a usr/lib/${PNAME}/* ${PKG}/usr/lib${LIBDIRSUFFIX}/${PNAME}/ || exit 1
+if [ "${SB_PIL}" = "YES" ] ;then
+  reldir=$(abs2rel ${PYSITELIB}/PIL ${PROGDIR})
+  missing ${PYSITELIB}/PIL/_imaging.so
+  rm -f ${PKG}/${PROGDIR}/PIL._imaging.so
+  ln -sf ${reldir}/_imaging.so ${PKG}/${PROGDIR}/PIL._imaging.so
+fi
+
+if [ "${SB_PYOSSL}" = "YES" ] ;then
+  reldir=$(abs2rel ${PYSITELIB}/OpenSSL ${PROGDIR})
+  for file in crypto rand SSL ;do
+    missing ${PYSITELIB}/OpenSSL/${file}.so
+    rm -f ${PKG}/${PROGDIR}/OpenSSL.${file}.so
+    ln -sf ${reldir}/${file}.so ${PKG}/${PROGDIR}/OpenSSL.${file}.so
+  done
+fi
+
+if [ "${SB_QT}" = "YES" ] ;then
+  reldir=$(abs2rel ${PYSITELIB} ${PROGDIR})
+
+  missing ${PYSITELIB}/sip.so
+  rm -f ${PKG}/${PROGDIR}/sip.so
+  ln -sf ${reldir}/sip.so ${PKG}/${PROGDIR}/sip.so
+
+  for file in Qt QtCore QtGui QtNetwork ;do
+    missing ${PYSITELIB}/PyQt4/${file}.so
+    rm -f ${PKG}/${PROGDIR}/PyQt4.${file}.so
+    ln -sf ${reldir}/PyQt4/${file}.so ${PKG}/${PROGDIR}/PyQt4.${file}.so
+  done
+  rm -f ${PKG}/${PROGDIR}/lib{Qt,png12}*.so.*
+fi
+
+if [ "${SB_CURL}" = "YES" ] && [ "${SB_PY}" = "YES" ] && [ "${SB_PYOSSL}" = "YES" ] ;then
+  rm -f ${PKG}/${PROGDIR}/lib{crypto,ssl}.so.*
+fi
 
 mkdir -p ${PKG}/etc/dbus-1/system.d
 install -pm0644 etc/dbus-1/system.d/*.conf ${PKG}/etc/dbus-1/system.d/ || exit 1
@@ -177,6 +264,8 @@ desktop-file-install --vendor="" \
   --dir ${PKG}/usr/share/applications \
   --remove-key="Encoding" \
   --remove-category="SpiderOak" \
+  --remove-category="Archiving" \
+  --remove-category="Utility" \
   --add-category="Qt" \
   usr/share/applications/${NAME}.desktop || exit 1
 
@@ -263,6 +352,7 @@ fi
 
 # Build package:
 set +o xtrace        # no longer print commands upon execution
+set -e
 
 ROOTCOMMANDS="set -o errexit -o xtrace ; cd ${PKG} ;
   /bin/chown --recursive root:root .  ;"
