akonadi, aspell, avidemux, bzr, compiz, ffmpeg, flash-player, firefox, getmail, imagemagick, iso-codes, kazehakase, libpipeline, libvpx, lvm2, man -> man-db, mkvtoolnix, mplayer*, mysql, nvidia-glx, oxygen-gtk, pbzip2, speech-dispatcher, stunnel, system-config-printer, systemd, vim, vimpaer, virtualbox, vlc, xulrunner

diff --git a/ntp/ntp.SlackBuild b/ntp/ntp.SlackBuild
--- a/ntp/ntp.SlackBuild
+++ b/ntp/ntp.SlackBuild
@@ -57,7 +57,7 @@ else
   SLKTARGET=${SLKTARGET:-i486}
 fi
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-2}
+BUILD=${BUILD:-3}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -200,14 +200,26 @@ chmod 600 ${PKG}/etc/ntp/crypto/pw.new
 
 mkdir -p ${PKG}/etc/rc.d
 cat ${CWD}/rc.ntpd > ${PKG}/etc/rc.d/rc.ntpd.new
+install -pm0755 ${CWD}/rc.ntpdate ${PKG}/etc/rc.d/rc.ntpdate.new || exit 1
 
 mkdir -p ${PKG}/lib/systemd/system
-install -pm0644 ${CWD}/ntpd.service ${PKG}/lib/systemd/system/ || exit 1
+install -pm0644 ${CWD}/systemd/ntpd*.service ${PKG}/lib/systemd/system/ || exit 1
 
 mkdir -p ${PKG}/etc/default
 cat > ${PKG}/etc/default/ntpd.new <<'EOF'
 # Command line options for ntpd
 NTPD_OPTIONS="-g"
+EOF
+
+cat > ${PKG}/etc/default/ntpdate.new <<'EOF'
+# Options for ntpdate
+NTPDATE_OPTIONS="-p 2"
+
+# Number of retries before giving up
+RETRIES=2
+
+# Set to 'yes' to sync hw clock after successful ntpdate
+SYNC_HWCLOCK=no
 EOF
 
 rmdir ${PKG}/usr/lib
@@ -326,6 +338,9 @@ config() {
 if [ -r etc/rc.d/rc.ntpd -a -r etc/rc.d/rc.ntpd.new ]; then
   chmod --reference=etc/rc.d/rc.ntpd etc/rc.d/rc.ntpd.new
 fi
+if [ -r etc/rc.d/rc.ntpdate -a -r etc/rc.d/rc.ntpdate.new ]; then
+  chmod --reference=etc/rc.d/rc.ntpdate etc/rc.d/rc.ntpdate.new
+fi
 
 ## List of conf files to check.  The conf files in your package should end in .new
 EOF
@@ -355,14 +370,16 @@ sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
 
 if [ "${SB_REP}" = "YES" ] ;then
   # Replicate slackbuild and patches
-  mkdir -p ${SBDIR}/patches
+  mkdir -p ${SBDIR}/{patches,systemd}
   install -m0644 ${CWD}/slack-desc ${CWD}/slack-required ${CWD}/ChangeLog.SB \
-    ${CWD}/apply-patches.sh ${CWD}/ntp.conf ${CWD}/rc.ntp ${CWD}/ntpd.service \
+    ${CWD}/apply-patches.sh ${CWD}/ntp.conf ${CWD}/rc.ntp* ${CWD}/ntpd.service \
     ${CWD}/${SRCARCHIVE2} ${CWD}/timepps.h ${SBDIR}/
   install -m0755 ${CWD}/${NAME}.SlackBuild \
      ${SBDIR}/${NAME}.SlackBuild
   install -m0644 ${CWD}/patches/*.* \
     ${SBDIR}/patches/
+  install -m0644 ${CWD}/systemd/*.* \
+    ${SBDIR}/systemd/
   rmdir ${SBDIR}/patches
 fi
 
