asio, dhcp, gnuplot, kdesvn, kernel-custom, libindi, libwebp, lilypond, nasm, netatalk, ompload, parole, pkg-config, sdlmame

diff --git a/gcc/gcc.SlackBuild b/gcc/gcc.SlackBuild
--- a/gcc/gcc.SlackBuild
+++ b/gcc/gcc.SlackBuild
@@ -385,6 +385,15 @@ tar -xvf ${CWD}/${SRCARCHIVE} || exit 1
 # build gcc
 ( mkdir gcc.build.lnx;
   cd gcc.build.lnx;
+  rm -f errortest
+
+  set +e
+
+  trap errortest ERR
+  errortest() {
+    local exit_status=${1:-$?}
+    echo ${exit_status} > ./errortest
+  }
 
   # If enough people need "treelang" support for it may be considered.
   #  --enable-languages=ada,c,c++,fortran,java,objc,treelang
@@ -442,12 +451,12 @@ tar -xvf ${CWD}/${SRCARCHIVE} || exit 1
      ${GCC_ARCHOPTS} \
      --build=${TARGET} \
      --target=${TARGET} \
-     --host=${TARGET} || exit 1
+     --host=${TARGET}
 
   # Start the build:
 
   # Include all debugging info (for now):
-  make -j${NJOBS} bootstrap || exit 1
+  make -j${NJOBS} bootstrap
 
   ( cd gcc
     make -j${NJOBS} gnatlib GNATLIBCFLAGS="${SLKCFLAGS}"
@@ -458,18 +467,26 @@ tar -xvf ${CWD}/${SRCARCHIVE} || exit 1
     CXXFLAGS="${SLKCFLAGS}" \
     make -j${NJOBS} gnattools
   )
-  make -j${NJOBS} info
+  make -j${NJOBS} info || true
 
   # Set SB_TEST=YES to run the tests
   if [ "${SB_TEST}" = "YES" ] ;then 
     echo '====================TESTING========================='
-    make -j${NJOBS} check
+    make -j${NJOBS} check || true
     echo '====================TESTING END====================='
   fi
 
-  make install DESTDIR=${PKG1} || exit 1
+  make install DESTDIR=${PKG1}
 
-) 2>&1 | tee ${TMP}/gcc.build.log || exit 1
+) 2>&1 | tee ${TMP}/gcc.build.log
+
+if [ -f gcc.build.lnx/errortest ] ;then
+  error=$(tail -n1 gcc.build.lnx/errortest)
+  echo
+  echo
+  echo "Exit with error ${error}. See ${TMP}/gcc.build.log"
+  exit ${error}
+fi
 
 ( cd gcc.build.lnx || exit 1
 
