dolphin-wmu, gnutls, graphicsmagick, kernel-custom, nvidia-{cg,cuda}-toolkit, pcsx2, ruby, seamonkey, smartmontools, sparsehash, tmux, waf, wine-mono, wine, wine_gecko

diff --git a/claws-mail/claws-mail.SlackBuild b/claws-mail/claws-mail.SlackBuild
--- a/claws-mail/claws-mail.SlackBuild
+++ b/claws-mail/claws-mail.SlackBuild
@@ -44,6 +44,9 @@ NAME=claws-mail
 PKG=${PKG:-${TMP}/package-${NAME}}
 
 VERSION=${VERSION:-3.8.1}
+# Put patchsets, eg.: 20 50 102 (0 or "" to disable)
+PVER=${PVER:-"93 94 95 96 99"}
+[ "${PVER}" = "" ] && PVER=0
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
 else
@@ -55,7 +58,7 @@ else
   SLKTARGET=${SLKTARGET:-i486}
 fi
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -70,6 +73,8 @@ SB_NM=${SB_NM:-YES}
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
+DOWNDIR=${CWD}/patches/updates
+
 SRCDIR=${NAME}-${VERSION}
 SRCARCHIVE=${SRCDIR}.tar.bz2
 
@@ -78,9 +83,23 @@ DL_TO=${DL_TO:-5}
 DL_OPTS=${DL_OPTS:-"--timeout=${DL_TO}"}
 SF_MIRROR=${SF_MIRROR:-http://prdownloads.sourceforge.net}
 DL_URL="${SF_MIRROR}/sylpheed-claws/${SRCARCHIVE}"
+PDL_URL="http://www.claws-mail.org/tracker/getpatchset.php?ver=${VERSION}cvs"
 
 # if source is not present, download in source rootdir if possible
 test -r ${CWD}/${SRCARCHIVE} || ${DL_PROG} ${DL_OPTS} ${DL_URL} || exit 1
+
+if [ "${PVER}" != "0" ] ;then
+  mkdir -p ${DOWNDIR}
+  for i in ${PVER} ; do
+    file=${NAME}-${VERSION}-cvs${i}.patch
+    test -r ${DOWNDIR}/${file} || ${DL_PROG} ${DL_OPTS} ${PDL_URL}${i} -O ${DOWNDIR}/${file} || exit 1
+    if grep -q "Can't generate the patch" ${DOWNDIR}/${file} ;then
+      echo "${file} failed! Patchset ${VERSION}cvs${i} nonexistent"
+      echo "See http://www.claws-mail.org/cvstrak-gtk2.php?section=projects"
+      exit 1
+    fi
+  done
+fi
 
 if [ "${SB_NATIVE}" = "YES" ] ;then
   SLKCFLAGS="-O2 -march=native -mtune=native -pipe"
@@ -263,6 +282,24 @@ fi
 mkdir -p ${PKG}/install
 cat ${CWD}/slack-desc > ${PKG}/install/slack-desc
 cat ${CWD}/slack-required > ${PKG}/install/slack-required
+
+cat > ${PKG}/install/doinst.sh <<EOF
+#!/bin/sh
+# Figure out our root directory
+ROOTDIR=\$(pwd)
+unset CHROOT
+if test "\${ROOTDIR}" != "/"; then
+  CHROOT="chroot \${ROOTDIR} "
+  ROOTDIR="\${ROOTDIR}/"
+fi
+if [ -x usr/bin/update-desktop-database ]; then
+  \${CHROOT} /usr/bin/update-desktop-database /usr/share/applications >/dev/null 2>&1
+fi
+if [ -x usr/bin/gtk-update-icon-cache ]; then
+  \${CHROOT} /usr/bin/touch --no-create /usr/share/icons/hicolor >/dev/null 2>&1
+  \${CHROOT} /usr/bin/gtk-update-icon-cache /usr/share/icons/hicolor >/dev/null 2>&1
+fi
+EOF
 
 sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
        ${PKG}/install/slack-desc
