ffmpegthumbnailer, libbs2b, lxpanel, lxsession, lxterminal

diff --git a/libbs2b/libbs2b.SlackBuild b/libbs2b/libbs2b.SlackBuild
--- a/libbs2b/libbs2b.SlackBuild
+++ b/libbs2b/libbs2b.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/sh
-#-- webkit for Slackware --
+#-- libbs2b for Slackware --
 # Build script by Phantom X <megaphantomx@bol.com.br>
-# Suggested usage: $ webkit.SlackBuild 2>&1 | tee build.log
+# Suggested usage: $ libbs2b.SlackBuild 2>&1 | tee build.log
 #--
 # Copyright 2008, 2009 Phantom X, Goiania, Brazil.
 # Copyright 2006 Martijn Dekker, Groningen, Netherlands.
@@ -23,8 +23,7 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# http://webkit.org/
-# http://webkitgtk.org/
+# http://bs2b.sourceforge.net/
 
 PACKAGER_ID=${PACKAGER_ID:-$USER}
 PACKAGER=${PACKAGER:-$USER@$HOSTNAME}
@@ -41,17 +40,10 @@ if [ ! -d ${TMP} ]; then
   mkdir -p ${TMP}
 fi
 
-SNAPBUILD=${SNAPBUILD:-YES}
-
-PNAME=WebKit
-NAME=webkit
+NAME=libbs2b
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-if [ "${SNAPBUILD}" = "YES" ] ;then
-  VERSION=${VERSION:-r44078}
-else
-  VERSION=${VERSION:-1.1.7}
-fi
+VERSION=${VERSION:-3.0.0}
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
 else
@@ -71,23 +63,15 @@ PKGDEST=${PKGDEST:-${CWD}}
 PKGFORMAT=${PKGFORMAT:-txz}
 PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
 
-# Set to YES to enable pango support for gtk build (broken for now)
-SB_PANGO=${SB_PANGO:-NO}
-
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
-if [ "${SNAPBUILD}" = "YES" ] ;then
-  SRCDIR=${PNAME}-${VERSION}
-  SRCARCHIVE=${SRCDIR}.tar.bz2
-  DL_URL="http://nightly.webkit.org/files/trunk/src/${SRCARCHIVE}"
-else
-  SRCDIR=${NAME}-${VERSION}
-  SRCARCHIVE=${SRCDIR}.tar.gz
-  DL_URL="http://webkitgtk.org/${SRCARCHIVE}"
-fi
+SRCDIR=${NAME}-${VERSION}
+SRCARCHIVE=${SRCDIR}.tar.lzma
 
 DL_TO=${DL_TO:-5}
 DL_OPTS=${DL_OPTS:-"--timeout=${DL_TO}"}
+SF_MIRROR=${SF_MIRROR:-http://prdownloads.sourceforge.net}
+DL_URL="${SF_MIRROR}/bs2b/${SRCARCHIVE}"
 
 # if source is not present, download in source rootdir if possible, or in /tmp
 if ! test -r ${SRCARCHIVE}; then
@@ -112,11 +96,36 @@ else
   LIBDIRSUFFIX=""
 fi
 
+if [ -d ${PKG} ]; then
+  # Clean up a previous build
+  rm -rf ${PKG}
+fi
+mkdir -p ${PKG}
+
 cd ${TMP}
+rm -rf ${SRCDIR}
+tar -xJvf ${CWD}/${SRCARCHIVE} || exit 1
 cd ${SRCDIR} || exit 1
 
-install -m 755 Programs/GtkLauncher \
-               ${PKG}/usr/libexec/${PNAME}/ || exit 1
+chmod -R u+w,go+r-w,a-s .
+
+# zcat ${CWD}/${NAME}.patch.gz | patch -p0 -E --backup --verbose || exit 1
+
+CFLAGS="${SLKCFLAGS}" \
+CXXFLAGS="${SLKCFLAGS}" \
+./configure \
+  --prefix=/usr \
+  --libdir=/usr/lib${LIBDIRSUFFIX} \
+  --sysconfdir=/etc \
+  --localstatedir=/var/lib \
+  --infodir=/usr/info \
+  --mandir=/usr/man \
+  --docdir=/usr/doc/${NAME}-${VERSION} \
+  --disable-static \
+  --build=${SLKTARGET}-${SLKDTARGET}-linux || exit 1
+
+make -j${NJOBS} || make || exit 1
+make install DESTDIR=${PKG} || exit 1
 
 rm -f ${PKG}/usr/lib${LIBDIRSUFFIX}/*.la
 
@@ -128,18 +137,15 @@ rm -f ${PKG}/usr/lib${LIBDIRSUFFIX}/*.la
 # Add a documentation directory:
 mkdir -p ${DOCDIR}
 cp -a \
-  ${CWD}/ChangeLog.SB \
+  AUTHORS COPYING ChangeLog README ${CWD}/ChangeLog.SB \
   ${DOCDIR}/
-for doc in JavaScriptCore/{AUTHORS,COPYING.LIB,THANKS,icu/{LICENSE,README},pcre/AUTHORS} WebKit/LICENSE WebCore/{LICENSE-APPLE,LICENSE-LGPL-2.1,icu/{LICENSE,README}} ;do
-  cp ${doc} ${DOCDIR}/$(echo "${doc}" | sed -e 's!/!.!g')
-done
 find ${DOCDIR}/ -type d -print0 | xargs -0 chmod 0755
 find ${DOCDIR}/ -type f -print0 | xargs -0 chmod 0644
 
 # Compress and link manpages, if any:
 if [ -d ${PKG}/usr/share/man ]; then
   mv ${PKG}/usr/share/man ${PKG}/usr/man
-  rmdir -p ${PKG}/usr/share
+  rmdir ${PKG}/usr/share
 fi
 if [ -d ${PKG}/usr/man ]; then
   ( cd ${PKG}/usr/man
