bash, cdrtools, emalfm2, gnome-chemistry-tools, kde-plasma-nm, libthumbs, net-snmp, readline, irpf214, receitanet, tumbler

diff --git a/rfb/irpf2014/irpf2014.SlackBuild b/rfb/irpf2014/irpf2014.SlackBuild
--- a/rfb/irpf2014/irpf2014.SlackBuild
+++ b/rfb/irpf2014/irpf2014.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/sh
-#-- receitanet for Slackware --
+#-- irpf2014 for Slackware --
 # Build script by Phantom X <megaphantomx at bol.com.br>
-# Suggested usage: $ receitanet.SlackBuild 2>&1 | tee build.log
+# Suggested usage: $ irpf2014.SlackBuild 2>&1 | tee build.log
 #--
 # Copyright 2008-2014 Phantom X, Goiania, Brazil.
 # Copyright 2006 Martijn Dekker, Groningen, Netherlands.
@@ -24,7 +24,7 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# http://www.receita.fazenda.gov.br
+# http://www.receita.fazenda.gov.br/irpf2014/
 
 PACKAGER_ID=${PACKAGER_ID:-$USER}
 PACKAGER=${PACKAGER:-$USER@$HOSTNAME}
@@ -38,10 +38,10 @@ if [ ! -d ${TMP} ]; then
   mkdir -p ${TMP}
 fi
 
-NAME=receitanet
+NAME=irpf2014
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-1.04-1}
+VERSION=${VERSION:-1.0-1}
 ARCH=noarch
 SLKTARGET=${SLKTARGET:-x86_64}
 SLKDTARGET=${SLKDTARGET:-slackware}
@@ -61,7 +61,7 @@ SRCARCHIVE=${SRCDIR}.noarch.rpm
 DL_PROG=${DL_PROG:-wget}
 DL_TO=${DL_TO:-5}
 DL_OPTS=${DL_OPTS:-"--timeout=${DL_TO}"}
-DL_URL="http://www.receita.fazenda.gov.br/Publico/programas/${NAME}/${SRCARCHIVE}"
+DL_URL="http://www28.receita.fazenda.gov.br/publico/programas/IRPF/2014/PGDIRPF2014/Java/Linux/${SRCARCHIVE}"
 
 # if source is not present, download in source rootdir if possible
 test -r ${CWD}/${SRCARCHIVE} || ${DL_PROG} ${DL_OPTS} ${DL_URL} || exit 1
@@ -85,7 +85,9 @@ if [ -r ${CWD}/apply-patches.sh ]; then
 fi
 
 mkdir -p ${PKG}/usr/share/ProgramasRFB/${NAME}
-cp -a "opt/Programas RFB/Receitanet"/* ${PKG}/usr/share/ProgramasRFB/${NAME}/ || exit $?
+cp -a opt/ProgramasRFB/IRPF2014/* ${PKG}/usr/share/ProgramasRFB/${NAME}/ || exit $?
+
+rmdir -p ${PKG}/usr/share/ProgramasRFB/${NAME}/*
 
 find ${PKG}/usr/share/ProgramasRFB/${NAME} -type d | xargs chmod 0755 2> /dev/null
 
@@ -123,74 +125,83 @@ JAVA_HOME=${JAVA_HOME:-${PRIMARY_LIB_DIR}/java}
 JAVABIN="${JAVA_HOME}/bin/java"
 
 if [ -x "${JAVABIN}" ] ;then
-  exec "${JAVABIN}" -jar /usr/share/ProgramasRFB/receitanet/receitanet.jar "${@}"
+  exec "${JAVABIN}" -Xms128M -Xmx512M -jar /usr/share/ProgramasRFB/irpf2014/irpf.jar "${@}"
 fi
-echo "Couldn't run Receitanet. Is PRIMARY_LIB_DIR set? JAVA_HOME/bin/java is missing?"
+echo "Couldn't run IRPF2014. Is PRIMARY_LIB_DIR set? JAVA_HOME/bin/java is missing?"
 exit 1
 EOF
 chmod 0755 ${PKG}/usr/bin/${NAME} || exit 1
 
+rename RFB rfb usr/share/applications/*.desktop
 mkdir -p ${PKG}/usr/share/applications
 
 SB_DFI(){
 desktop-file-install \
   --vendor="rfb" --mode 0644 \
   --dir ${PKG}/usr/share/applications \
-  --add-category "Office" \
-  --add-category "X-rfb" \
-  --add-category "X-receitanet" "$@"
+  --remove-key="Name[pt_BR]" \
+  --add-category="Office" \
+  --add-category="X-rfb" \
+  --add-category="X-irpf2014" \
+  --set-icon="${NAME}" \
+  "$@"
 }
 
+sed -i \
+  -e '/^Comment=/d' \
+  -e 's|^Name=|Comment=|g' \
+  usr/share/applications/rfb-${NAME}_program.desktop
+
 SB_DFI \
-  --set-name="Receitanet" \
+  --set-name="IRPF2014" \
   --set-key="Exec" \
   --set-value="${NAME}" \
-  --set-icon="${NAME}" \
-  usr/share/applications/rfb-${NAME}.desktop || exit 1
+  usr/share/applications/rfb-${NAME}_program.desktop || exit 1
 
 SB_DFI \
   --set-key="Exec" \
-  --set-value="${NAME} -ajuda" \
-  --set-icon="${NAME}_ajuda" \
-  --remove-key="Comment" \
-  usr/share/applications/rfb-${NAME}-ajuda.desktop || exit 1
+  --set-value="${NAME} -h" \
+  usr/share/applications/rfb-${NAME}_help.desktop || exit 1
+
+SB_DFI \
+  --set-key="Exec" \
+  --set-value="xdg-open /usr/share/ProgramasRFB/${NAME}/Leia_me.htm" \
+  usr/share/applications/rfb-${NAME}_leiame.desktop || exit 1
 
 mkdir -p ${PKG}/etc/xdg/menus/applications-merged
-install -pm0644 ${CWD}/rfb.menu \
-  ${PKG}/etc/xdg/menus/applications-merged/rfb.menu || exit 1
+install -pm0644 ${CWD}/${NAME}.menu \
+  ${PKG}/etc/xdg/menus/applications-merged/rfb-${NAME}.menu || exit 1
 
 mkdir -p ${PKG}/usr/share/desktop-directories
-cp usr/share/desktop-directories/rfb-ProgramasRFB.directory \
-  ${PKG}/usr/share/desktop-directories/rfb-programas.directory || exit 1
+cp usr/share/desktop-directories/RFB-ProgramasRFB2014.directory \
+  ${PKG}/usr/share/desktop-directories/rfb-${NAME}.directory || exit 1
 desktop-file-install --delete-original --vendor="rfb" \
    --dir ${PKG}/usr/share/desktop-directories \
-   --remove-key="Encoding" \
-   --remove-key="Categories" \
-   --set-icon="${NAME}" \
-   ${PKG}/usr/share/desktop-directories/rfb-programas.directory || exit 1
+   --remove-key="Name[pt_BR]" \
+   --remove-key="Comment[pt_BR]" \
+   --set-icon="irpf2014" \
+   ${PKG}/usr/share/desktop-directories/rfb-${NAME}.directory || exit 1
 
 mkdir -p ${PKG}/usr/share/icons/hicolor/32x32/apps
-convert "opt/Programas RFB/Receitanet/imagens/Receitanet.xpm" \
+install -pm0644 opt/ProgramasRFB/IRPF2014/RFB.png \
   ${PKG}/usr/share/icons/hicolor/32x32/apps/${NAME}.png || exit 1
-
-convert "opt/Programas RFB/Receitanet/imagens/Ajuda.xpm" \
-  ${PKG}/usr/share/icons/hicolor/32x32/apps/${NAME}_ajuda.png || exit 1
 
 for res in 16 20 22 24 ;do
   dir=${PKG}/usr/share/icons/hicolor/${res}x${res}/apps
   mkdir -p ${dir}
-  convert "opt/Programas RFB/Receitanet/imagens/Receitanet.xpm" -filter Lanczos -resize ${res}x${res} \
+  convert opt/ProgramasRFB/IRPF2014/RFB.png -filter Lanczos -resize ${res}x${res} \
     -depth 8 ${dir}/${NAME}.png || exit 1
-  convert "opt/Programas RFB/Receitanet/imagens/Receitanet.xpm" -filter Lanczos -resize ${res}x${res} \
-    -depth 8 ${dir}/${NAME}_ajuda.png || exit 1
 done
+
+gunzip usr/share/doc/*/changelog.gz
+cp usr/share/doc/*/changelog .
 
 # Add a documentation directory:
 mkdir -p ${DOCDIR}
 cp -a \
-  ${CWD}/ChangeLog.SB \
+  usr/share/doc/*/copyright ${CWD}/ChangeLog.SB \
   ${DOCDIR}/
-[ -r ChangeLog ] && head -n 1000 ChangeLog > ${DOCDIR}/ChangeLog
+[ -r changelog ] && head -n 1000 changeLog > ${DOCDIR}/changeLog
 find ${DOCDIR}/ -type d -print0 | xargs -0 chmod 0755
 find ${DOCDIR}/ -type f -print0 | xargs -0 chmod 0644
 find ${DOCDIR}/ -type f -size 0 -print0 | xargs -0 rm -f
@@ -245,7 +256,7 @@ if [ "${SB_REP}" = "YES" ] ;then
   # Replicate slackbuild and patches
   mkdir -p ${SBDIR}/patches
   install -pm0644 ${CWD}/slack-desc ${CWD}/slack-required ${CWD}/ChangeLog.SB \
-    ${CWD}/apply-patches.sh ${CWD}/rfb.menu ${SBDIR}/
+    ${CWD}/apply-patches.sh ${CWD}/${NAME}.menu ${SBDIR}/
   install -pm0755 ${CWD}/${NAME}.SlackBuild \
     ${SBDIR}/${NAME}.SlackBuild
   install -pm0644 ${CWD}/patches/*.* \
