bash, dropbox, emacs, gnumeric, goffice, graphicsmagick, iproute2, iptables, kde-gtk-config, kid3, perl, soundkonverter, xchm, zoneinfo

diff --git a/dropbox/dropbox.SlackBuild b/dropbox/dropbox.SlackBuild
--- a/dropbox/dropbox.SlackBuild
+++ b/dropbox/dropbox.SlackBuild
@@ -40,9 +40,9 @@ fi
 NAME=dropbox
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-1.6.2}
+VERSION=${VERSION:-2.0.0}
 # x86 or x86_64
-ARCH=${ARCH:-x86}
+ARCH=${ARCH:-x86_64}
 [ "${ARCH}" = "x86_64" ] || ARCH=x86
 SLKDTARGET=${SLKDTARGET:-slackware}
 BUILD=${BUILD:-1}
@@ -52,6 +52,13 @@ SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
 PKGDEST=${PKGDEST:-${CWD}}
 PKGFORMAT=${PKGFORMAT:-txz}
 PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
+
+# Do no blame Dropbox devs if setting YES in these
+# Set to YES to use system libs
+# bzip2
+SB_BZ2=${SB_BZ2:-YES}
+# popt
+SB_POPT=${SB_POPT:-YES}
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
@@ -104,10 +111,44 @@ chmod -R u+w,go+r-w,a-s .
 
 # zcat ${CWD}/${NAME}.patch.gz | patch -p0 -E --backup --verbose || exit 1
 
-rm -f ${NAME}/lib{bz2,dbus*,stdc++,z}.so*
+rm -f ${NAME}/lib{dbus*,stdc++,z}.so*
 
 mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}
 cp -a ${NAME}/* ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/ || exit 1
+
+
+xtcsoname(){
+  objdump -p "${1}" | grep SONAME | awk '{print $2}'
+}
+
+missing(){
+  if ! [ -e "$1" ] ;then
+    echo "File $1 is missing!"
+    return 5
+  fi
+}
+
+# bzip2
+if [ "${SB_BZ2}" = "YES" ] ;then
+  ( cd ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME} || exit 1
+    for file in libbz2*.so* ;do
+      SONAME=${file}
+      missing /usr/lib${LIBDIRSUFFIX}/${SONAME} || missing /lib${LIBDIRSUFFIX}/${SONAME} || exit $?
+      rm -fv ${file}
+    done
+  ) || exit $?
+fi
+
+# popt
+if [ "${SB_POPT}" = "YES" ] ;then
+  ( cd ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME} || exit 1
+    for file in libpopt*.so*  ;do
+      SONAME=$(xtcsoname ${file})
+      missing /usr/lib${LIBDIRSUFFIX}/${SONAME} || missing /lib${LIBDIRSUFFIX}/${SONAME} || exit $?
+      rm -fv ${file}
+    done
+  ) || exit $?
+fi
 
 mkdir -p ${PKG}/etc/prelink.conf.d
 cat > ${PKG}/etc/prelink.conf.d/${NAME}-${ARCH}.conf <<EOF
