bashdb, boost, espeak, fotoxx, kernel-custom, libgadu, memtest86+, mysql, perf, php, qbittorrent, skrooge, strace, ulatencyd, vala, xlockmore, zoneinfo

diff --git a/boost/boost.SlackBuild b/boost/boost.SlackBuild
--- a/boost/boost.SlackBuild
+++ b/boost/boost.SlackBuild
@@ -43,8 +43,9 @@ fi
 NAME=boost
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-1.46.0}
-SONAMEVER=${VERSION}
+VERSION=${VERSION:-1.46.1}
+SVER=$(echo ${VERSION} | cut -d. -f1-2)
+SONAMEVER=${SVER}
 PVER=$(echo ${VERSION} | tr . _ )
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
@@ -220,16 +221,17 @@ for i in $( find stage -type f -name \*.so ); do
   if [ -x /usr/bin/chrpath ] ;then
     chrpath --delete ${VNAME}
   fi
-  
-  if [ "${SONAMEVER}" != "${VERSION}" ] ;then
-    ln -s ${VNAMEbase} ${SONAME} || echo "error" >> soinstall-error
+
+  install -p -m 755 ${VNAME} \
+    ${PKG}/usr/lib${LIBDIRSUFFIX}/${VNAMEbase} || echo "error" >> soinstall-error
+
+  if [ "${SONAMEVER}" = "${VERSION}" ] ;then
+    ln -s ${VNAMEbase} ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAMELbase} || echo "error" >> soinstall-error
+  else
+    ln -s ${VNAMEbase} ${PKG}/usr/lib${LIBDIRSUFFIX}/${SONAMEbase} || echo "error" >> soinstall-error
+    ln -s ${SONAMEbase} ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAMELbase} || echo "error" >> soinstall-error
   fi
-  ln -s ${VNAMEbase} ${NAMEL} || echo "error" >> soinstall-error
-  install -p -m 755 ${VNAME} ${PKG}/usr/lib${LIBDIRSUFFIX}/${VNAMEbase} || echo "error" >> soinstall-error
-  if [ "${SONAMEVER}" != "${VERSION}" ] ;then
-    mv ${SONAME} ${PKG}/usr/lib${LIBDIRSUFFIX}/${SONAMEbase} || echo "error" >> soinstall-error
-  fi
-  mv ${NAMEL} ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAMELbase} || echo "error" >> soinstall-error
+
 done
 if [ -f soinstall-error ] ;then
   exit 1
