akonadi, boost, kernel-custom, libisoburn, libquicktime, openarena, promoe, pdfedit, smc, xmms2

diff --git a/boost/boost.SlackBuild b/boost/boost.SlackBuild
--- a/boost/boost.SlackBuild
+++ b/boost/boost.SlackBuild
@@ -43,8 +43,8 @@ fi
 NAME=boost
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-1.41.0}
-SONAMEVER=6
+VERSION=${VERSION:-1.42.0}
+SONAMEVER=${VERSION}
 PVER=$(echo ${VERSION} | tr . _ )
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
@@ -210,11 +210,15 @@ for i in $( find stage -type f -name \*.so ); do
   if which chrpath &>/dev/null ;then
     chrpath --delete ${VNAME}
   fi
-
-  ln -s ${VNAMEbase} ${SONAME} || echo "error" >> soinstall-error
+  
+  if [ "${SONAMEVER}" != "${VERSION}" ] ;then
+    ln -s ${VNAMEbase} ${SONAME} || echo "error" >> soinstall-error
+  fi
   ln -s ${VNAMEbase} ${NAMEL} || echo "error" >> soinstall-error
   install -p -m 755 ${VNAME} ${PKG}/usr/lib${LIBDIRSUFFIX}/${VNAMEbase} || echo "error" >> soinstall-error
-  mv ${SONAME} ${PKG}/usr/lib${LIBDIRSUFFIX}/${SONAMEbase} || echo "error" >> soinstall-error
+  if [ "${SONAMEVER}" != "${VERSION}" ] ;then
+    mv ${SONAME} ${PKG}/usr/lib${LIBDIRSUFFIX}/${SONAMEbase} || echo "error" >> soinstall-error
+  fi
   mv ${NAMEL} ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAMELbase} || echo "error" >> soinstall-error
 done
 if [ -f soinstall-error ] ;then
diff --git a/xmms2/xmms2.SlackBuild b/xmms2/xmms2.SlackBuild
--- a/xmms2/xmms2.SlackBuild
+++ b/xmms2/xmms2.SlackBuild
@@ -43,8 +43,8 @@ fi
 NAME=xmms2
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-0.6}
-CODE=${CODE:-DrMattDestruction}
+VERSION=${VERSION:-0.7}
+CODE=${CODE:-DrNo}
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
 else
@@ -56,7 +56,7 @@ else
   SLKTARGET=${SLKTARGET:-i486}
 fi
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-3}
+BUILD=${BUILD:-1}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -64,8 +64,12 @@ PKGDEST=${PKGDEST:-${CWD}}
 PKGFORMAT=${PKGFORMAT:-txz}
 PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
 
+# Set to YES to set pulse as default
+SB_PA=${SB_PA:-NO}
+
 PERLVENDORARCH=$(eval "$(perl -V:vendorarch)"; echo ${vendorarch})
 RUBYVER=$(ruby -r rbconfig -e 'print Config::CONFIG["ruby_version"]')
+RUBYSITEARCH=$(ruby -rrbconfig -e 'puts Config::CONFIG["sitearchdir"]')
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
@@ -113,32 +117,34 @@ cd ${SRCDIR} || exit 1
 chmod -R u+w,go+r-w,a-s .
 
 # zcat ${CWD}/${NAME}.patch.gz | patch -p0 -E --backup --verbose || exit 1
-zcat ${CWD}/${NAME}-build-fix.patch.gz | patch -p1 -E --backup --verbose || exit 1
-if [ "$(echo ${RUBYVER} | cut -d. -f1)" -ge 1 ] && [ "$(echo ${RUBYVER} | cut -d. -f2)" -ge 9 ] ;then
-  zcat ${CWD}/xmms2-ruby1.9.patch.gz | patch -p0 -E --backup --verbose || exit 1
+if [ -r ${CWD}/apply-patches.sh ]; then
+  . ${CWD}/apply-patches.sh || exit 1
 fi
 
-if [ "${ARCH}" = "x86_64" ] ;then
-  sed -i \
-    -e "s|for name, lib|for name, lib${LIBDIRSUFFIX}|g" \
-    -e "s|'LIB': lib|'LIB': lib${LIBDIRSUFFIX}|g" \
-    -e "s|\"lib\"|\"lib${LIBDIRSUFFIX}\"|g" \
-    -e "s|\${PREFIX}/lib|\${PREFIX}/lib${LIBDIRSUFFIX}|g" \
-    wscript || exit 1
-  sed -i -e "s|'lib'|'lib${LIBDIRSUFFIX}'|g" src/include/xmms/wscript || exit 1
-  sed -i -e "/boost_libpath/s|lib'|lib${LIBDIRSUFFIX}'|g" wafadmin/Tools/boost.py || exit 1
-fi
+# Clean up paths in wafadmin
+WAFADMIN_FILES=$(find wafadmin/ -type f)
+for i in ${WAFADMIN_FILES}; do
+  sed -i "s|/usr/lib|/usr/lib${LIBDIRSUFFIX}|g" $i
+done
+sed -i "s|\"lib\"|\"/lib${LIBDIRSUFFIX}\"|g" wscript
+
+export LIBDIR="/usr/lib${LIBDIRSUFFIX}"
 
 CFLAGS="${SLKCFLAGS}" \
 CXXFLAGS="${SLKCFLAGS}" \
 LINKFLAGS="${LDFLAGS}" \
 ./waf configure \
   --prefix=/usr \
-  --conf-prefix=/etc \
-  --with-libdir=/usr/lib${LIBDIRSUFFIX} \
-  --with-mandir=/usr/man \
+  --libdir=/usr/lib${LIBDIRSUFFIX} \
+  --sysconfdir=/etc \
+  --localstatedir=/var \
+  --infodir=/usr/info \
+  --mandir=/usr/man \
+  --docdir=/usr/doc/${NAME}-${VERSION} \
   --with-pixmap-dir=/usr/share/pixmaps/${NAME} \
+  --with-pkgconfigdir=/usr/lib${LIBDIRSUFFIX}/pkgconfig \
   --with-perl-archdir=${PERLVENDORARCH} \
+  --with-ruby-libdir=${RUBYSITEARCH} \
   --with-custom-version=${BUILD}${PACKAGER_ID} \
   || exit 1
 
@@ -148,10 +154,10 @@ LINKFLAGS="${LDFLAGS}" \
 chmod 0755 ${PKG}/usr/lib*/*.so.* || exit 1
 chmod 0755 ${PKG}/usr/lib*/${NAME}/*.so || exit 1
 
-if [ "${ARCH}" = "x86_64" ] && [ -d ${PKG}/usr/lib ] ;then
-  mv ${PKG}/usr/lib/* ${PKG}/usr/lib${LIBDIRSUFFIX}/ || exit 1
-  rmdir -p ${PKG}/usr/lib
-fi
+find ${PKG}/usr/lib* -name '*.so*' -exec chmod 0755 {} ';'
+
+install -pm0755 ${CWD}/xmms2-client-launcher.sh \
+  ${PKG}/usr/bin/ || exit 1
 
 mkdir -p ${PKG}/etc/${NAME}
 
@@ -206,11 +212,13 @@ sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
 
 if [ "${SB_REP}" = "YES" ] ;then
   # Replicate slackbuild and patches
-  mkdir -p ${SBDIR}
+  mkdir -p ${SBDIR}/patches
   install -m0644 ${CWD}/slack-desc ${CWD}/slack-required ${CWD}/ChangeLog.SB \
-                 ${CWD}/${NAME}-*.patch.gz ${SBDIR}/
+                 ${CWD}/apply-patches.sh ${CWD}/*-launcher.sh ${SBDIR}/
   install -m0755 ${CWD}/${NAME}.SlackBuild \
                  ${SBDIR}/${NAME}.SlackBuild
+  install -m0644 ${CWD}/patches/*.gz \
+                 ${SBDIR}/patches/
 fi
 
 # Build package:
