bzr, chmlib, liferea, midori, shadow, webkit

diff --git a/boost/boost.SlackBuild b/boost/boost.SlackBuild
--- a/boost/boost.SlackBuild
+++ b/boost/boost.SlackBuild
@@ -51,7 +51,11 @@ if [ "${SB_NATIVE}" = "YES" ] ;then
 else
   ARCH=${ARCH:-i686}
 fi
-SLKTARGET=${SLKTARGET:-i486}
+if [ "${ARCH}" = "x86_64" ] ;then
+  SLKTARGET=${SLKTARGET:-x86_64}
+else
+  SLKTARGET=${SLKTARGET:-i486}
+fi
 SLKDTARGET=${SLKDTARGET:-slackware}
 BUILD=${BUILD:-1}
 NJOBS=${NJOBS:-2}
@@ -90,6 +94,11 @@ else
     x86_64)      SLKCFLAGS="-O2 -fPIC"
                  ;;
   esac
+fi
+if [ "${ARCH}" = "x86_64" ] ;then
+  LIBDIRSUFFIX="64"
+else
+  LIBDIRSUFFIX=""
 fi
 
 if [ -d ${PKG} ]; then
@@ -179,10 +188,10 @@ fi
 
 # install
 # install lib
-mkdir -p ${PKG}/usr/lib
+mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}
 for i in $( find stage -type f -name \*.a ); do
   NAMEL=$( basename ${i} );
-  install -p -m 0644 ${i} ${PKG}/usr/lib/${NAMEL} || echo "error" >> soinstall-error
+  install -p -m 0644 ${i} ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAMEL} || echo "error" >> soinstall-error
 done
 for i in $( find stage -type f -name \*.so ); do
   NAMEL=${i};
@@ -201,9 +210,9 @@ for i in $( find stage -type f -name \*.so ); do
 
   ln -s ${VNAMEbase} ${SONAME} || echo "error" >> soinstall-error
   ln -s ${VNAMEbase} ${NAMEL} || echo "error" >> soinstall-error
-  install -p -m 755 ${VNAME} ${PKG}/usr/lib/${VNAMEbase} || echo "error" >> soinstall-error
-  mv ${SONAME} ${PKG}/usr/lib/${SONAMEbase} || echo "error" >> soinstall-error
-  mv ${NAMEL} ${PKG}/usr/lib/${NAMELbase} || echo "error" >> soinstall-error
+  install -p -m 755 ${VNAME} ${PKG}/usr/lib${LIBDIRSUFFIX}/${VNAMEbase} || echo "error" >> soinstall-error
+  mv ${SONAME} ${PKG}/usr/lib${LIBDIRSUFFIX}/${SONAMEbase} || echo "error" >> soinstall-error
+  mv ${NAMEL} ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAMELbase} || echo "error" >> soinstall-error
 done
 if [ -f soinstall-error ] ;then
   exit 1
