bitlbee, rarian, squid, xarchiver

diff --git a/boost/boost.SlackBuild b/boost/boost.SlackBuild
--- a/boost/boost.SlackBuild
+++ b/boost/boost.SlackBuild
@@ -44,6 +44,7 @@ NAME=boost
 PKG=${PKG:-${TMP}/package-${NAME}}
 
 VERSION=${VERSION:-1.35.0}
+SONAMEVER=3
 PVER=$(echo ${VERSION} | tr . _ )
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
@@ -68,9 +69,8 @@ SRCARCHIVE=${SRCDIR}.tar.bz2
 
 DL_TO=${DL_TO:-5}
 DL_OPTS=${DL_OPTS:-"--timeout=${DL_TO}"}
-#DL_URL="http://dl.sf.net/sourceforge/${NAME}/${SRCARCHIVE}"
-DL_URL="http://prdownloads.sourceforge.net/${NAME}/${SRCARCHIVE}"
-#DL_URL="http://download.sf.net/${NAME}/${SRCARCHIVE}"
+SF_MIRROR=${SF_MIRROR:-http://prdownloads.sourceforge.net}
+DL_URL="${SF_MIRROR}/${NAME}/${SRCARCHIVE}"
 
 # if source is not present, download in source rootdir if possible, or in /tmp
 if ! test -r ${SRCARCHIVE}; then
@@ -136,7 +136,7 @@ PYTHON_FLAGS="--with-python-root=/usr --with-python-version=$PYTHON_VERSION"
 REGEX_FLAGS="--with-icu"
 ./configure --prefix=/usr ${BUILD_FLAGS} ${PYTHON_FLAGS} ${REGEX_FLAGS} || exit 1
 
-make all LIBS=${LDFLAGS} || exit 1
+make all || exit 1
 
 # build docs, requires a network connection for docbook XSLT stylesheets
 #cd ./doc
@@ -146,7 +146,7 @@ make all LIBS=${LDFLAGS} || exit 1
 #cd ..
 
 if [ "${SB_TEST}" = "YES" ] ;then
-  echo ====================TESTING=========================
+  echo '====================TESTING========================='
   echo "<p>" $(uname -a) "</p>" > status/regression_comment.html
   echo "" >> status/regression_comment.html
   echo "<p>" $(g++ --version) "</p>" >> status/regression_comment.html
@@ -171,33 +171,32 @@ if [ "${SB_TEST}" = "YES" ] ;then
     echo "error sending results"
     exit 1
   fi
-  echo ====================TESTING END=====================
+  echo '====================TESTING END====================='
 fi
 
 # install
 # install lib
 mkdir -p ${PKG}/usr/lib
-RETVAL=0
 for i in $( find stage -type f -name \*.a ); do
   NAMEL=$( basename ${i} );
-  install -p -m 0644 ${i} ${PKG}/usr/lib/${NAMEL} || RETVAL=1
+  install -p -m 0644 ${i} ${PKG}/usr/lib/${NAMEL} || echo "error" >> soinstall-error
 done
 for i in $( find stage -type f -name \*.so ); do
   NAMEL=${i};
-  SONAME=${i}.3;
+  SONAME=${i}.${SONAMEVER};
   VNAME=${i}.${VERSION};
   base=$(basename $i);
   NAMELbase=${base};
-  SONAMEbase=${base}.3;
+  SONAMEbase=${base}.${SONAMEVER};
   VNAMEbase=${base}.${VERSION};
-  mv ${i} ${VNAME} || RETVAL=1
-  ln -s ${VNAMEbase} ${SONAME} || RETVAL=1
-  ln -s ${VNAMEbase} ${NAMEL} || RETVAL=1
-  install -p -m 755 ${VNAME} ${PKG}/usr/lib/${VNAMEbase} || RETVAL=1
-  mv ${SONAME} ${PKG}/usr/lib/${SONAMEbase} || RETVAL=1
-  mv ${NAMEL} ${PKG}/usr/lib/${NAMELbase} || RETVAL=1
+  mv ${i} ${VNAME} || echo "error" >> soinstall-error
+  ln -s ${VNAMEbase} ${SONAME} || echo "error" >> soinstall-error
+  ln -s ${VNAMEbase} ${NAMEL} || echo "error" >> soinstall-error
+  install -p -m 755 ${VNAME} ${PKG}/usr/lib/${VNAMEbase} || echo "error" >> soinstall-error
+  mv ${SONAME} ${PKG}/usr/lib/${SONAMEbase} || echo "error" >> soinstall-error
+  mv ${NAMEL} ${PKG}/usr/lib/${NAMELbase} || echo "error" >> soinstall-error
 done
-if [ ${RETVAL} -eq 1 ] ;then
+if [ -f soinstall-error ] ;then
   exit 1
 fi
 
