brltty, desktop-effects, gjs, gnome-shell, mutter, kernel-custom 2.6.31, some xorg related packs.

diff --git a/gxine/gxine.SlackBuild b/gxine/gxine.SlackBuild
--- a/gxine/gxine.SlackBuild
+++ b/gxine/gxine.SlackBuild
@@ -58,7 +58,7 @@ else
   SLKTARGET=${SLKTARGET:-i486}
 fi
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 NJOBS=${NJOBS:-2}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -80,10 +80,8 @@ DL_OPTS=${DL_OPTS:-"--timeout=${DL_TO}"}
 SF_MIRROR=${SF_MIRROR:-http://prdownloads.sourceforge.net}
 DL_URL="${SF_MIRROR}/xine/${SRCARCHIVE}"
 
-# if source is not present, download in source rootdir if possible, or in /tmp
-if ! test -r ${SRCARCHIVE}; then
-  test -r ${CWD}/${SRCARCHIVE} || wget ${DL_OPTS} ${DL_URL} || exit 1
-fi
+# if source is not present, download in source rootdir if possible
+test -r ${CWD}/${SRCARCHIVE} || wget ${DL_OPTS} ${DL_URL} || exit 1
 
 if [ "${SB_NATIVE}" = "YES" ] ;then
   SLKCFLAGS="-O2 -march=native -mtune=native ${SB_ECFLAGS} -pipe"
@@ -97,20 +95,22 @@ else
                  ;;
   esac
 fi
-
-if [ -d ${PKGF} ]; then
-  # Clean up a previous build
-  rm -rf ${PKGF}
+if [ "${ARCH}" = "x86_64" ] ;then
+  LIBDIRSUFFIX="64"
+  SLKCFLAGS="${SLKCFLAGS} -fPIC"
+else
+  LIBDIRSUFFIX=""
 fi
-mkdir -p ${PKG} ${PKG2}
+
+if [ -d ${PKG} ]; then
+  # Clean up a previous build
+  rm -rf ${PKG}
+fi
+mkdir -p ${PKG}
 
 cd ${TMP}
 rm -rf ${SRCDIR}
-if $(file -L ${CWD}/${SRCARCHIVE} | grep -q ": bzip2"); then
-  tar -xjvf ${CWD}/${SRCARCHIVE} || exit 1
-elif $(file -L ${CWD}/${SRCARCHIVE} | grep -q ": gzip"); then
-  tar -xzvf ${CWD}/${SRCARCHIVE} || exit 1
-fi
+tar -xvf ${CWD}/${SRCARCHIVE} || exit 1
 cd ${SRCDIR} || exit 1
 
 chmod -R u+w,go+r-w,a-s .
@@ -128,6 +128,7 @@ CFLAGS="${SLKCFLAGS}" \
 CXXFLAGS="${SLKCFLAGS}" \
 ./configure \
   --prefix=/usr \
+  --libdir=/usr/lib${LIBDIRSUFFIX} \
   --sysconfdir=/etc \
   --localstatedir=/var/lib \
   --infodir=/usr/info \
@@ -136,7 +137,7 @@ CXXFLAGS="${SLKCFLAGS}" \
   --disable-rpath \
   --disable-static \
   --with-browser-plugin \
-  --with-spidermonkey=/usr/lib \
+  --with-spidermonkey=/usr/lib${LIBDIRSUFFIX} \
   --disable-mozjs \
   --disable-ffjs \
   --disable-seajs \
@@ -154,19 +155,19 @@ make -j${NJOBS} || make || exit 1
 make install DESTDIR=${PKG} || exit 1
 
 # Remove .las
-rm -f ${PKG}/usr/lib/gxine/*.la
+rm -f ${PKG}/usr/lib*/gxine/*.la
 
 find ${PKG} | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 
-if [ -f ${PKG}/usr/lib/${NAME}/${NAME}plugin.so ] ;then
-  mkdir -p ${PKG2}/usr/lib/${NAME}
-  mv ${PKG}/usr/lib/${NAME}/${NAME}plugin.so \
-     ${PKG2}/usr/lib/${NAME}/ || exit 1
-  rmdir -p ${PKG}/usr/lib/${NAME}
-  mkdir -p ${PKG2}/usr/lib/mozilla/plugins
-  ( cd ${PKG2}/usr/lib/mozilla/plugins
-    ln -sf /usr/lib/gxine/gxineplugin.so . || exit 1
+if [ -f ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/${NAME}plugin.so ] ;then
+  mkdir -p ${PKG2}/usr/lib${LIBDIRSUFFIX}/${NAME}
+  mv ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}/${NAME}plugin.so \
+     ${PKG2}/usr/lib${LIBDIRSUFFIX}/${NAME}/ || exit 1
+  rmdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}/${NAME}
+  mkdir -p ${PKG2}/usr/lib${LIBDIRSUFFIX}/mozilla/plugins
+  ( cd ${PKG2}/usr/lib${LIBDIRSUFFIX}/mozilla/plugins
+    ln -sf /usr/lib${LIBDIRSUFFIX}/gxine/gxineplugin.so . || exit 1
   ) || exit 1
 fi
 
