culmus-fonts, freetype, fvwm-crystal, graphite2, libdiscid, libreoffice, libtdb, winetricks

diff --git a/texlive/texlive.SlackBuild b/texlive/texlive.SlackBuild
--- a/texlive/texlive.SlackBuild
+++ b/texlive/texlive.SlackBuild
@@ -60,7 +60,7 @@ else
   SLKTARGET=${SLKTARGET:-i486}
 fi
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -68,6 +68,10 @@ PKGDEST=${PKGDEST:-${CWD}}
 PKGFORMAT=${PKGFORMAT:-txz}
 PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
 DPKGNAME=${DNAME}-$(echo ${VERSION} | tr - . )-noarch-${BUILD}${PACKAGER_ID}
+
+# Set to YES to check sources md5sum (recommended, but slow)
+# Build log suggested above is recommended too
+SB_MD5=${SB_MD5:-NO}
 
 # Set to YES to package docs (big)
 SB_DOCS=${SB_DOCS:-NO}
@@ -97,10 +101,34 @@ test -r ${CWD}/${SRCARCHIVE} || sh ${CWD}/${FEDORADIST} ${NAME} ${FEDORABRANCH} 
 test -r ${CWD}/${SRCARCHIVE2} || sh ${CWD}/${FEDORADIST} ${NAME} ${FEDORABRANCH} ${SRCARCHIVE2} || exit 1
 mkdir -p ${DOWNDIR}
 ( cd ${DOWNDIR} || exit 1
-  for file in $(<${CWD}/sourcelist1) $(<${CWD}/sourcelist2) $(<${CWD}/sourcelist3);do
+  for source in $(sed -e 's/  /__/' ${CWD}/sourcelist1 ${CWD}/sourcelist2 ${CWD}/sourcelist3) ; do
+    file="$(echo ${source} | awk -F'__' '{print $2}')"
     test -r ${file} || ${DL_PROG} ${DL_OPTS} ${DL_URL}/${file} || exit 1
   done
 ) || exit $?
+
+# Test md5sum and list not matching
+if [ "${SB_MD5}" = "YES" ] ;then
+  ( cd ${DOWNDIR} || exit 1
+    MD5BAD=0
+    for source in $(sed -e 's/  /__/' ${CWD}/sourcelist3) ; do
+      file="$(echo ${source} | awk -F'__' '{print $2}')"
+      md5="$(echo ${source} | awk -F'__' '{print $1}')"
+      localmd5="$(md5sum ${file} | awk '{print $1}' )"
+      if [ "${localmd5}" != "${md5}" ] ;then
+        echo "md5 error: ${file}"
+        echo "${localmd5} != ${md5}"
+        echo
+        MD5BAD=1
+      fi
+    done
+    if [ "${MD5BAD}" -ne 0 ] ;then
+      echo "md5sum from some files differ"
+      echo "Delete them and try again."
+      exit 1
+    fi
+  ) || exit $?
+fi
 
 if [ "${SB_NATIVE}" = "YES" ] ;then
   SLKCFLAGS="-O2 -march=native -mtune=native -pipe"
@@ -216,13 +244,16 @@ mkdir -p ${PKG}/${SB_TEXDIR}/texmf-config/web2c
 mkdir -p ${PKG}/${SB_TEXMF_VAR}
 mkdir -p ${PKG}/${SB_TEXDIR}/texmf-dist
 
-for file in $(<${CWD}/sourcelist1) ; do
+for source in $(sed -e 's/  /__/' ${CWD}/sourcelist1) ; do
+  file="$(echo ${source} | awk -F'__' '{print $2}')"
   tar xvf ${DOWNDIR}/${file} -C ${PKG}/${SB_TEXDIR}/texmf-dist || exit 1
 done
-for file in $(<${CWD}/sourcelist2) ; do
+for source in $(sed -e 's/  /__/' ${CWD}/sourcelist2) ; do
+  file="$(echo ${source} | awk -F'__' '{print $2}')"
   tar xvf ${DOWNDIR}/${file} -C ${PKG}/${SB_TEXDIR} || exit 1
 done
-for file in $(<${CWD}/sourcelist3) ; do
+for source in $(sed -e 's/  /__/' ${CWD}/sourcelist3) ; do
+  file="$(echo ${source} | awk -F'__' '{print $2}')"
   tar xvf ${DOWNDIR}/${file} -C ${PKG} || exit 1
 done
 
