alsamixergui, mixmos, pcsx-df, totem
Two mixers as gifts for Gerson! :)

diff --git a/pcsx-df/pcsx-df.SlackBuild b/pcsx-df/pcsx-df.SlackBuild
--- a/pcsx-df/pcsx-df.SlackBuild
+++ b/pcsx-df/pcsx-df.SlackBuild
@@ -23,6 +23,7 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+# http://pcsx-df.sourceforge.net
 # http://aboenterprises.ca/pcsx-df/
 
 PACKAGER_ID=${PACKAGER_ID:-$USER}
@@ -43,19 +44,24 @@ fi
 NAME=pcsx-df
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-1.818}
+VERSION=${VERSION:-1.9}
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
 else
   ARCH=${ARCH:-i686}
 fi
 SLKTARGET=${SLKTARGET:-i486}
-BUILD=${BUILD:-2}
+BUILD=${BUILD:-1}
 NJOBS=${NJOBS:-2}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
 PKGDEST=${PKGDEST:-${CWD}}
 PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
+
+# Set to YES do enable nautilusburn support
+SB_NB=${SB_NB:-NO}
+# Set to YES to enable dfbinimage plugin (build may fail)
+SB_DFBI=${SB_DFBI:-YES}
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
@@ -64,8 +70,10 @@ SRCARCHIVE=${SRCDIR}.tar.gz
 
 DL_TO=${DL_TO:-5}
 DL_OPTS=${DL_OPTS:-"--timeout=${DL_TO}"}
-DL_URL="http://aboenterprises.ca/${NAME}/files/${SRCARCHIVE}"
-
+#DL_URL="http://dl.sf.net/sourceforge/${NAME}/${SRCARCHIVE}"
+DL_URL="http://prdownloads.sourceforge.net/${NAME}/${SRCARCHIVE}"
+#DL_URL="http://download.sf.net/${NAME}/${SRCARCHIVE}"
+#DL_URL="http://aboenterprises.ca/${NAME}/files/${SRCARCHIVE}"
 
 # if source is not present, download in source rootdir if possible, or in /tmp
 if ! test -r ${SRCARCHIVE}; then
@@ -102,6 +110,12 @@ chmod -R u+w,go+r-w,a-s .
 
 sed -i -e "/^Icon=/s|\.png||g" data/pcsx.desktop || exit 1
 
+sed -i -e '/^pcsx_LDADD/s|=|= -lpthread|g' gui/Makefile.* || exit 1
+
+[ "${SB_NB}" = "YES" ] || SB_NBOPTS="--disable-nautilusburn"
+# Set to YES to enable dfbinimage plugin (build may fail)
+[ "${SB_DFBI}" = "YES" ] && SB_DFBIOPTS="--enable-dfbinimage"
+
 CFLAGS="${SLKCFLAGS}" \
 CXXFLAGS="${SLKCFLAGS}" \
 ./configure \
@@ -114,9 +128,9 @@ CXXFLAGS="${SLKCFLAGS}" \
   --disable-dependency-tracking \
   --disable-rpath \
   --disable-static \
-  --enable-alsa \
+  --enable-alsa ${SB_NBOPTS} ${SB_DFBIOPTS} \
   --build=${SLKTARGET}-slackware-linux || exit 1
-
+-lpthread
 make -j${NJOBS} || exit 1
 make install DESTDIR=${PKG} || exit 1
 
@@ -146,7 +160,8 @@ find ${DOCDIR}/ -type f -print0 | xargs -0 chmod 0644
 
 # Compress and link manpages, if any:
 if [ -d ${PKG}/usr/share/man ]; then
-    mv ${PKG}/usr/share/man ${PKG}/usr/man
+  mv ${PKG}/usr/share/man ${PKG}/usr/man
+  rmdir ${PKG}/usr/share
 fi
 if [ -d ${PKG}/usr/man ]; then
   ( cd ${PKG}/usr/man
@@ -167,8 +182,8 @@ fi
 # Compress info pages, if any:
 if [ -d ${PKG}/usr/info ]; then
   ( cd ${PKG}/usr/info
-      rm -f dir
-      gzip -9 *
+    rm -f dir
+    gzip -9 *
   )
 fi
 
