amarok, audacious, binutils, ccache, cmake, cups-filters, cups, doxygen, ethtool, gdisk->gptfdisk, ghostscript, gnome-chemistry-utils, gv, imagemagick, jbig2dec, kde-plasma-veromix, libcap-ng, libgee, mount-gtk, mpd, mupdf, parole, partionmonitor, p11-kit, phonon-backend-gstreamer, poppler, pycurl, qpdfview, qtcurve-kde4, scons, vim

diff --git a/dcron/run-parts b/dcron/run-parts
--- a/dcron/run-parts
+++ b/dcron/run-parts
@@ -39,10 +39,7 @@ for SCRIPT in $1/* ; do
   fi
   # If we've made it this far, then run the script if it's executable:
   if [ -x $SCRIPT ]; then
-    echo "$SCRIPT:"
-    echo
-    $SCRIPT 2>&1
-    echo
+    $SCRIPT 1>&2 || echo "$SCRIPT failed."
   fi
 done
 
