cdrtools, chromaprint, firefox, gdk-pixbuf2, getmail, gtk+2, gtk-xfce-engine, hplip, os-prober, taglib, virtualbox, xulrunner

diff --git a/dcron/run-parts b/dcron/run-parts
--- a/dcron/run-parts
+++ b/dcron/run-parts
@@ -39,7 +39,7 @@ for SCRIPT in $1/* ; do
   fi
   # If we've made it this far, then run the script if it's executable:
   if [ -x $SCRIPT ]; then
-    $SCRIPT 1>&2 || echo "$SCRIPT failed."
+    $SCRIPT || echo "$SCRIPT failed."
   fi
 done
 
