dbus, enet, fpc, gdb, git, gnumeric, goffice, gstreamer1, kdevelop, kernel-custom, mcomix, nettle, pcsx2, pcsxr, rekonq, squid, steam, wine, xterm, yptools

diff --git a/fpc/fpc.SlackBuild b/fpc/fpc.SlackBuild
--- a/fpc/fpc.SlackBuild
+++ b/fpc/fpc.SlackBuild
@@ -3,7 +3,7 @@
 # Build script by Phantom X <megaphantomx at bol.com.br>
 # Suggested usage: $ fpc.SlackBuild 2>&1 | tee build.log
 #--
-# Copyright 2008-2012 Phantom X, Goiania, Brazil.
+# Copyright 2008-2013 Phantom X, Goiania, Brazil.
 # Copyright 2006 Martijn Dekker, Groningen, Netherlands.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -25,8 +25,6 @@
 
 # http://www.freepascal.org/
 
-# Needs fpc installed to compile.
-
 PACKAGER_ID=${PACKAGER_ID:-$USER}
 PACKAGER=${PACKAGER:-$USER@$HOSTNAME}
 
@@ -46,7 +44,7 @@ PNAME=fpcbuild
 NAME=fpc
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-2.6.2rc1}
+VERSION=${VERSION:-2.6.2}
 SVER="$(echo ${VERSION} | cut -d _ -f1 | cut -d r -f1)"
 unset RCV
 echo ${VERSION} | grep -q rc && RCV="r$(echo ${VERSION} | cut -d r -f2)"
@@ -85,6 +83,15 @@ DL_URLC="ftp://ftp.freepascal.org/pub/fpc/beta/${SVER}-${RCV}/source/${SRCARCHIV
 # if source is not present, download in source rootdir if possible
 test -r ${CWD}/${SRCARCHIVE} || ${DL_PROG} ${DL_OPTS} ${DL_URL} \
   || ${DL_PROG} ${DL_OPTS} ${DL_URLB} || ${DL_PROG} ${DL_OPTS} ${DL_URLC} || exit 1
+
+if ! [ $(which fpc 2>/dev/null) ]; then
+  echo "fpc os missing."
+  echo
+  echo "Needs fpc installed to compile."
+  echo "Try upstream binary rpm."
+  echo
+  exit 1
+fi
 
 case "${ARCH}" in
   i[3-6]86)    SLKPPCNAME="ppc386"
