at-spi, brasero, farsight2, glade3, gnome 2.24.3, groff, icu, kernel-custom, mkvtoolnix, pyopengl, qdvdauthor, some telepathy modules, xine-lib

diff --git a/telepathy/telepathy-farsight/telepathy-farsight.SlackBuild b/telepathy/telepathy-farsight/telepathy-farsight.SlackBuild
--- a/telepathy/telepathy-farsight/telepathy-farsight.SlackBuild
+++ b/telepathy/telepathy-farsight/telepathy-farsight.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/sh
-#-- python for Slackware --
+#-- telepathy-farsight for Slackware --
 # Build script by Phantom X <megaphantomx@bol.com.br>
-# Suggested usage: $ python.SlackBuild 2>&1 | tee build.log
+# Suggested usage: $ telepathy-farsight.SlackBuild 2>&1 | tee build.log
 #--
 # Copyright 2008 Phantom X, Goiania, Brazil.
 # Copyright 2006 Martijn Dekker, Groningen, Netherlands.
@@ -23,7 +23,7 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# http://www.python.org/
+# http://telepathy.freedesktop.org/wiki/FrontPage
 
 PACKAGER_ID=${PACKAGER_ID:-$USER}
 PACKAGER=${PACKAGER:-$USER@$HOSTNAME}
@@ -40,13 +40,10 @@ if [ ! -d ${TMP} ]; then
   mkdir -p ${TMP}
 fi
 
-PNAME=Python
-NAME=python
+NAME=telepathy-farsight
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-2.6.1}
-SVER=$(echo ${VERSION} | cut -d. -f1-2)
-PVER=${PVER:-r1}
+VERSION=${VERSION:-0.0.4}
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
 else
@@ -56,104 +53,80 @@ SLKTARGET=${SLKTARGET:-i486}
 BUILD=${BUILD:-1}
 NJOBS=${NJOBS:-2}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
-SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
+SBDIR=${PKG}/usr/src/slackbuilds/telepathy/${NAME}
 PKGDEST=${PKGDEST:-${CWD}}
 PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
-# Location for Python site-packages:
-SITEPK=${PKG}/usr/lib/python${SVER}/site-packages
-TOOLSDIR=../lib/python${SVER}/site-packages
-
-SRCDIR=${PNAME}-${VERSION}
-SRCARCHIVE=${SRCDIR}.tar.bz2
-DSRCARCHIVE=${NAME}-docs-html.tar.bz2
-PSRCARCHIVE=${NAME}-gentoo-patches-${SVER}-${PVER}.tar.bz2
+SRCDIR=${NAME}-${VERSION}
+SRCARCHIVE=${SRCDIR}.tar.gz
 
 DL_TO=${DL_TO:-5}
 DL_OPTS=${DL_OPTS:-"--timeout=${DL_TO}"}
-SF_MIRROR=${SF_MIRROR:-http://prdownloads.sourceforge.net}
-DL_URL="${SF_MIRROR}/${NAME}/${SRCARCHIVE}"
-DL_URL="http://www.python.org/ftp/python/${VERSION}/${SRCARCHIVE}"
-DDL_URL="http://www.python.org/ftp/python/doc/${VERSION}/${DSRCARCHIVE}"
-GENTOO_MIRROR=${GENTOO_MIRROR:-ftp://ftp.ussg.iu.edu/pub/linux/gentoo}
-PDL_URL="${GENTOO_MIRROR}/distfiles/${PSRCARCHIVE}"
+DL_URL="http://telepathy.freedesktop.org/releases/${NAME}/${SRCARCHIVE}"
 
 # if source is not present, download in source rootdir if possible, or in /tmp
 if ! test -r ${SRCARCHIVE}; then
   test -r ${CWD}/${SRCARCHIVE} || wget ${DL_OPTS} ${DL_URL} || exit 1
 fi
-if ! test -r ${DSRCARCHIVE}; then
-  test -r ${CWD}/${DSRCARCHIVE} || wget ${DL_OPTS} ${DDL_URL} || exit 1
-fi
-if ! test -r ${PSRCARCHIVE}; then
-  test -r ${CWD}/${PSRCARCHIVE} || wget ${DL_OPTS} ${PDL_URL} || exit 1
-fi
 
 if [ "${SB_NATIVE}" = "YES" ] ;then
-  SLKCFLAGS="-O3 -march=native -mtune=native ${SB_ECFLAGS} -pipe"
+  SLKCFLAGS="-O2 -march=native -mtune=native ${SB_ECFLAGS} -pipe"
 else
   case "${ARCH}" in
-    i[3-6]86)    SLKCFLAGS="-O3 -march=${ARCH} -mtune=i686"
+    i[3-6]86)    SLKCFLAGS="-O2 -march=${ARCH} -mtune=i686"
                  ;;
-    s390)        SLKCFLAGS="-O3"
+    s390)        SLKCFLAGS="-O2"
                  ;;
-    x86_64)      SLKCFLAGS="-O3 -fPIC"
+    x86_64)      SLKCFLAGS="-O2 -fPIC"
                  ;;
   esac
 fi
 
+if [ -d ${PKG} ]; then
+  # Clean up a previous build
+  rm -rf ${PKG}
+fi
+mkdir -p ${PKG}
+
 cd ${TMP}
+rm -rf ${SRCDIR}
+if $(file -L ${CWD}/${SRCARCHIVE} | grep -q ": bzip2"); then
+  tar -xjvf ${CWD}/${SRCARCHIVE} || exit 1
+elif $(file -L ${CWD}/${SRCARCHIVE} | grep -q ": gzip"); then
+  tar -xzvf ${CWD}/${SRCARCHIVE} || exit 1
+fi
 cd ${SRCDIR} || exit 1
-# Junk, no point in putting in -test sub-pkg
-rm -f ${PKG}/usr/lib/python${SVER}/idlelib/testcode.py*
 
-rm -f ${PKG}/usr/lib/python${SVER}/email/test/data/audiotest.au ${PKG}/usr/lib/python${SVER}/test/audiotest.au
+chmod -R u+w,go+r-w,a-s .
 
-# Remove SLKCFLAGS from modules build Makefile.
-# This fix some possible problems.
-sed -e "/^OPT=/s|${SLKCFLAGS}||g" \
-    -i ${PKG}/usr/lib/python${SVER}/config/Makefile || exit 1
+# zcat ${CWD}/${NAME}.patch.gz | patch -p0 -E --backup --verbose || exit 1
+
+CFLAGS="${SLKCFLAGS}" \
+CXXFLAGS="${SLKCFLAGS}" \
+./configure \
+  --prefix=/usr \
+  --sysconfdir=/etc \
+  --localstatedir=/var/lib \
+  --infodir=/usr/info \
+  --mandir=/usr/man \
+  --docdir=/usr/doc/${NAME}-${VERSION} \
+  --build=${SLKTARGET}-slackware-linux || exit 1
+
+make -j${NJOBS} || exit 1
+make install DESTDIR=${PKG} || exit 1
 
 ( cd ${PKG}
   find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
   find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 )
 
-( cd ${PKG}/usr/bin || exit 1
-  rm -f python python-config
-  ln -sf python${SVER} python
-  ln -sf python${SVER}-config python-config
-)
-
-# We'll install the python-tools under site-packages:
-mkdir -p ${SITEPK}
-( cd Tools ; cp -a * ${SITEPK} )
-
-# Make a few useful symlinks:
-mkdir -p ${PKG}/usr/bin
-( cd ${PKG}/usr/bin
-  ln -sf ${TOOLSDIR}/modulator/modulator.py modulator
-  ln -sf ${TOOLSDIR}/pynche/pynche pynche
-  ln -sf ${TOOLSDIR}/i18n/msgfmt.py .
-  ln -sf ${TOOLSDIR}/i18n/pygettext.py .
-)
-
-rm -f ${SITEPK}/pynche/pynche.pyw
-
-mv Tools/modulator/README Tools/modulator/README.modulator
-mv Tools/pynche/README Tools/pynche/README.pynche
-
 # Add a documentation directory:
 mkdir -p ${DOCDIR}
 cp -a \
-  README Misc Demo html ${CWD}/ChangeLog.SB \
+  COPYING ChangeLog ${CWD}/ChangeLog.SB \
   ${DOCDIR}/
-mv ${SITEPK}/README ${DOCDIR}/README.python-tools
-( cd ${DOCDIR}
-  ln -sf ../${TOOLSDIR} Tools
-)
 find ${DOCDIR}/ -type d -print0 | xargs -0 chmod 0755
 find ${DOCDIR}/ -type f -print0 | xargs -0 chmod 0644
 
@@ -187,13 +160,11 @@ sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
 
 if [ "${SB_REP}" = "YES" ] ;then
   # Replicate slackbuild and patches
-  mkdir -p ${SBDIR}/patches
+  mkdir -p ${SBDIR}
   install -m0644 ${CWD}/slack-desc ${CWD}/slack-required ${CWD}/ChangeLog.SB \
-                 ${CWD}/apply-patches.sh ${SBDIR}/
+                 ${SBDIR}/
   install -m0755 ${CWD}/${NAME}.SlackBuild \
                  ${SBDIR}/${NAME}.SlackBuild
-  install -m0644 ${CWD}/patches/*.gz \
-                 ${SBDIR}/patches/
   sed -i "/^VERSION=/s/:-.*}/:-$VERSION}/
           /^BUILD=/s/:-.*}/:-$BUILD}/
           /^  ARCH=/s/:-.*}/:-$ARCH}/
