graphicsmagick, libvorbis, lrzip, mariadb, irpf2015, ruby, virtualbox, waf, xfce4-pulseaudio-plugin, xterm

diff --git a/rfb/irpf2015/irpf2015.SlackBuild b/rfb/irpf2015/irpf2015.SlackBuild
--- a/rfb/irpf2015/irpf2015.SlackBuild
+++ b/rfb/irpf2015/irpf2015.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/sh
-#-- xfce4-weather-plugin for Slackware --
+#-- irpf2015 for Slackware --
 # Build script by Phantom X <megaphantomx at bol.com.br>
-# Suggested usage: $ xfce4-weather-plugin.SlackBuild 2>&1 | tee build.log
+# Suggested usage: $ irpf2015.SlackBuild 2>&1 | tee build.log
 #--
 # Copyright 2008-2015 Phantom X, Goiania, Brazil.
 # Copyright 2006 Martijn Dekker, Groningen, Netherlands.
@@ -24,13 +24,10 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# http://goodies.xfce.org/projects/panel-plugins/xfce4-weather-plugin
+# http://www.receita.fazenda.gov.br/irpf2015/
 
 PACKAGER_ID=${PACKAGER_ID:-$USER}
 PACKAGER=${PACKAGER:-$USER@$HOSTNAME}
-
-# Set YES for native build with gcc >= 4.2
-SB_NATIVE=${SB_NATIVE:-NO}
 
 # Set to YES to replicate slackbuild and patches
 SB_REP=${SB_REP:-YES}
@@ -41,63 +38,40 @@ if [ ! -d ${TMP} ]; then
   mkdir -p ${TMP}
 fi
 
-NAME=xfce4-weather-plugin
+PNAME=IRPF2015
+NAME=irpf2015
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-0.8.5}
-SVER="$(echo ${VERSION} | cut -d. -f1-2)"
-if [ "${SB_NATIVE}" = "YES" ] ;then
-  ARCH=${ARCH:-$(uname -m)}
-else
-  ARCH=${ARCH:-x86_64}
-fi
-if [ "${ARCH}" = "x86_64" ] ;then
-  SLKTARGET=${SLKTARGET:-x86_64}
-else
-  SLKTARGET=${SLKTARGET:-i486}
-fi
+VERSION=${VERSION:-1.0a}
+ARCH=noarch
+SLKTARGET=${SLKTARGET:-x86_64}
 SLKDTARGET=${SLKDTARGET:-slackware}
 BUILD=${BUILD:-1}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
-SBDIR=${PKG}/usr/src/slackbuilds/xfce-goodies/${NAME}
+SBDIR=${PKG}/usr/src/slackbuilds/rfb/${NAME}
 PKGDEST=${PKGDEST:-${CWD}}
 PKGFORMAT=${PKGFORMAT:-txz}
 PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
-SRCDIR=${NAME}-${VERSION}
-SRCARCHIVE=${SRCDIR}.tar.bz2
+SRCDIR=${PNAME}
+SRCARCHIVE=${SRCDIR}-${VERSION}.zip
 
 DL_PROG=${DL_PROG:-wget}
 DL_TO=${DL_TO:-5}
 DL_OPTS=${DL_OPTS:-"--timeout=${DL_TO}"}
-DL_URL="http://archive.xfce.org/src/panel-plugins/${NAME}/${SVER}/${SRCARCHIVE}"
+DL_URL="http://www28.receita.fazenda.gov.br/publico/programas/IRPF/2015/PGDIRPF2015/Java/zip/${SRCARCHIVE}"
 
 # if source is not present, download in source rootdir if possible
 test -r ${CWD}/${SRCARCHIVE} || ${DL_PROG} ${DL_OPTS} ${DL_URL} || exit 1
 
-if [ "${SB_NATIVE}" = "YES" ] ;then
-  SLKCFLAGS="-O2 -march=native -mtune=native -pipe"
-  [ "${SB_ECFLAGS}" ] && SLKCFLAGS="${SLKCFLAGS} ${SB_ECFLAGS}"
-else
-  case "${ARCH}" in
-    i[3-6]86)    SLKCFLAGS="-O2 -march=${ARCH} -mtune=i686"
-                 ;;
-    x86_64)      SLKCFLAGS="-O2 -fPIC"
-                 ;;
-    s390|*)      SLKCFLAGS="-O2"
-                 ;;
-  esac
-fi
-if [ "${ARCH}" = "x86_64" ] ;then
-  LIBDIRSUFFIX="64"
-  SLKCFLAGS="${SLKCFLAGS} -fPIC"
-else
-  LIBDIRSUFFIX=""
-fi
+[ "$1" = "--dlsrc" ] && exit 0
 
+if [ ! -d ${TMP} ]; then
+  mkdir -p ${TMP}
+fi
 if [ -d ${PKG} ]; then
   # Clean up a previous build
   rm -rf ${PKG}
@@ -106,7 +80,7 @@ mkdir -p ${PKG}
 
 cd ${TMP}
 rm -rf ${SRCDIR}
-tar -xvf ${CWD}/${SRCARCHIVE} || exit 1
+unzip ${CWD}/${SRCARCHIVE} || exit 1
 cd ${SRCDIR} || exit 1
 
 chmod -R u+w,go+r-w,a-s .
@@ -115,34 +89,123 @@ if [ -r ${CWD}/apply-patches.sh ]; then
   . ${CWD}/apply-patches.sh
 fi
 
-CFLAGS="${SLKCFLAGS}" \
-CXXFLAGS="${SLKCFLAGS}" \
-./configure \
-  --prefix=/usr \
-  --libdir=/usr/lib${LIBDIRSUFFIX} \
-  --sysconfdir=/etc \
-  --localstatedir=/var/lib \
-  --infodir=/usr/info \
-  --mandir=/usr/man \
-  --docdir=/usr/doc/${NAME}-${VERSION} \
-  --disable-silent-rules \
-  --disable-static \
-  --build=${SLKTARGET}-${SLKDTARGET}-linux || exit $?
+unzip irpf.jar icones/RFB.png IRPF-Licenses.txt || exit 1
+mv icones/RFB.png .
 
-make -j${NJOBS} || make || exit $?
-make install DESTDIR=${PKG} || exit $?
+rm -rf exec.{bat,sh} Execute.txt icones
 
-find ${PKG} -name '*.la' -delete
+mkdir -p ${PKG}/usr/share/ProgramasRFB/${NAME}
+cp -a * ${PKG}/usr/share/ProgramasRFB/${NAME}/ || exit $?
 
-find ${PKG} | xargs file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+rmdir -p ${PKG}/usr/share/ProgramasRFB/${NAME}/*
+
+find ${PKG}/usr/share/ProgramasRFB/${NAME} -type d | xargs chmod 0755 2> /dev/null
+
+mkdir -p ${PKG}/usr/bin
+cat > ${PKG}/usr/bin/${NAME} <<'EOF'
+#!/bin/sh
+
+RFB_ARCH=$(uname -m)
+case ${RFB_ARCH} in
+  x86_64 | ia64 | s390 )
+    PRIMARY_LIB_DIR="/usr/lib64"
+    SECONDARY_LIB_DIR="/usr/lib"
+    ;;
+  * )
+    PRIMARY_LIB_DIR="/usr/lib"
+    SECONDARY_LIB_DIR="/usr/lib64"
+    ;;
+esac
+
+if [ -z "${JAVA_HOME}" ] ;then
+  if [ ! -d ${PRIMARY_LIB_DIR}/java ]; then
+    if [ ! -x ${SECONDARY_LIB_DIR}/java ]; then
+      echo "Error: ${PRIMARY_LIB_DIR}/java not found"
+      if [ -d ${SECONDARY_LIB_DIR}/java ]; then
+        echo "       ${SECONDARY_LIB_DIR}/java not found"
+      fi
+      exit 1
+    fi
+    PRIMARY_LIB_DIR="${SECONDARY_LIB_DIR}"
+  fi
+fi
+
+JAVA_HOME=${JAVA_HOME:-${PRIMARY_LIB_DIR}/java}
+
+JAVABIN="${JAVA_HOME}/bin/java"
+
+if [ -x "${JAVABIN}" ] ;then
+  exec "${JAVABIN}" -Xms128M -Xmx512M -jar /usr/share/ProgramasRFB/irpf2015/irpf.jar "${@}"
+fi
+echo "Couldn't run IRPF2015. Is PRIMARY_LIB_DIR set? JAVA_HOME/bin/java is missing?"
+exit 1
+EOF
+chmod 0755 ${PKG}/usr/bin/${NAME} || exit 1
+
+mkdir -p ${PKG}/usr/share/applications
+cat > ${PKG}/usr/share/applications/rfb-${NAME}_program.desktop <<EOF
+[Desktop Entry]
+Version=1.0
+Type=Application
+Name=${PNAME}
+Comment=${PNAME} - Declaração de Ajuste Anual, Final de Espólio e Saída Definitiva do País
+Exec=${NAME}
+Icon=${NAME}
+Categories=Office;X-rfb;X-${NAME};
+EOF
+
+cat > ${PKG}/usr/share/applications/rfb-${NAME}_help.desktop <<EOF
+[Desktop Entry]
+Version=1.0
+Type=Application
+Name=Ajuda do ${PNAME}
+Exec=${NAME} -h
+Icon=${NAME}
+Categories=Office;X-rfb;X-${NAME};
+EOF
+
+cat > ${PKG}/usr/share/applications/rfb-${NAME}_leiame.desktop <<EOF
+[Desktop Entry]
+Version=1.0
+Type=Application
+Name=Leia-me do ${PNAME}
+Exec=xdg-open /usr/share/ProgramasRFB/${NAME}/Leia_me.htm
+Icon=${NAME}
+Categories=Office;X-rfb;X-${NAME};
+EOF
+
+mkdir -p ${PKG}/etc/xdg/menus/applications-merged
+install -pm0644 ${CWD}/${NAME}.menu \
+  ${PKG}/etc/xdg/menus/applications-merged/rfb-${NAME}.menu || exit 1
+
+mkdir -p ${PKG}/usr/share/desktop-directories
+cat > ${PKG}/usr/share/desktop-directories/rfb-${NAME}.directory  <<EOF
+[Desktop Entry]
+Version=1.0
+Type=Directory
+Name=Programas RFB2015
+Icon=${NAME}
+EOF
+
+mkdir -p ${PKG}/usr/share/icons/hicolor/512x512/apps
+ln -s ../../../../ProgramasRFB/${NAME}/RFB.png \
+  ${PKG}/usr/share/icons/hicolor/512x512/apps/${NAME}.png || exit 1
+
+for res in 16 20 22 24 32 36 48 64 72 96 128 192 256 ;do
+  dir=${PKG}/usr/share/icons/hicolor/${res}x${res}/apps
+  mkdir -p ${dir}
+  convert RFB.png -filter Lanczos -resize ${res}x${res} \
+    -depth 8 ${dir}/${NAME}.png || exit 1
+done
+
+rm -f ${PKG}/usr/share/ProgramasRFB/${NAME}/IRPF-Licenses.txt
 
 # Add a documentation directory:
 mkdir -p ${DOCDIR}
 cp -a \
-  AUTHORS COPYING README NEWS THANKS TODO ${CWD}/ChangeLog.SB \
+  IRPF-Licenses.txt ${CWD}/ChangeLog.SB \
   ${DOCDIR}/
-[ -r ChangeLog ] && head -n 1000 ChangeLog > ${DOCDIR}/ChangeLog
+[ -r changelog ] && head -n 1000 changeLog > ${DOCDIR}/changeLog
 find ${DOCDIR}/ -type d -print0 | xargs -0 chmod 0755
 find ${DOCDIR}/ -type f -print0 | xargs -0 chmod 0644
 find ${DOCDIR}/ -type f -size 0 -print0 | xargs -0 rm -f
@@ -181,9 +244,12 @@ if test "\${ROOTDIR}" != "/"; then
   CHROOT="chroot \${ROOTDIR} "
   ROOTDIR="\${ROOTDIR}/"
 fi
+if [ -x usr/bin/update-desktop-database ]; then
+  \${CHROOT} /usr/bin/update-desktop-database 1> /dev/null 2> /dev/null
+fi
 if [ -x usr/bin/gtk-update-icon-cache ]; then
   \${CHROOT} /usr/bin/touch --no-create /usr/share/icons/hicolor >/dev/null 2>&1
-  \${CHROOT} /usr/bin/gtk-update-icon-cache /usr/share/icons/hicolor >/dev/null 2>&1
+  \${CHROOT} /usr/bin/gtk-update-icon-cache -q /usr/share/icons/hicolor > /dev/null 2>&1
 fi
 EOF
 
@@ -193,17 +259,18 @@ sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
 if [ "${SB_REP}" = "YES" ] ;then
   # Replicate slackbuild and patches
   mkdir -p ${SBDIR}/patches
-  install -m0644 ${CWD}/slack-desc ${CWD}/slack-required ${CWD}/ChangeLog.SB \
-    ${CWD}/apply-patches.sh ${SBDIR}/
-  install -m0755 ${CWD}/${NAME}.SlackBuild \
+  install -pm0644 ${CWD}/slack-desc ${CWD}/slack-required ${CWD}/ChangeLog.SB \
+    ${CWD}/apply-patches.sh ${CWD}/${NAME}.menu ${SBDIR}/
+  install -pm0755 ${CWD}/${NAME}.SlackBuild \
     ${SBDIR}/${NAME}.SlackBuild
-  install -m0644 ${CWD}/patches/*.* \
+  install -pm0644 ${CWD}/patches/*.* \
     ${SBDIR}/patches/
   rmdir ${SBDIR}/patches
 fi
 
 # Build package:
 set +o xtrace        # no longer print commands upon execution
+set -e
 
 ROOTCOMMANDS="set -o errexit -o xtrace ; cd ${PKG} ;
   /bin/chown --recursive root:root .  ;"
