conky, fotoxx, freeimage, gtkimageview, lensfun, perl-image-exiftool, printoxx, qdvdauthor, sauerbraten, ufraw, unrar, xsane

diff --git a/freeimage/freeimage.SlackBuild b/freeimage/freeimage.SlackBuild
--- a/freeimage/freeimage.SlackBuild
+++ b/freeimage/freeimage.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/sh
-#-- unrar for Slackware --
+#-- freeimage for Slackware --
 # Build script by Phantom X <megaphantomx@bol.com.br>
-# Suggested usage: $ unrar.SlackBuild 2>&1 | tee build.log
+# Suggested usage: $ freeimage.SlackBuild 2>&1 | tee build.log
 #--
 # Copyright 2008 Phantom X, Goiania, Brazil.
 # Copyright 2006 Martijn Dekker, Groningen, Netherlands.
@@ -23,7 +23,7 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# http://www.rarlab.com/
+# http://freeimage.sourceforge.net/
 
 PACKAGER_ID=${PACKAGER_ID:-$USER}
 PACKAGER=${PACKAGER:-$USER@$HOSTNAME}
@@ -40,12 +40,12 @@ if [ ! -d ${TMP} ]; then
   mkdir -p ${TMP}
 fi
 
-NAME=unrar
+PNAME=FreeImage
+NAME=freeimage
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-3.9.1}
-SONAMEVER="$(echo ${VERSION} | cut -d. -f1)"
-SVER="$(echo ${VERSION} | cut -d. -f1-2)"
+VERSION=${VERSION:-3.12.0}
+SONAME="$(echo ${VERSION} | cut -d. -f1)"
 if [ "${SB_NATIVE}" = "YES" ] ;then
   ARCH=${ARCH:-$(uname -m)}
 else
@@ -63,12 +63,13 @@ PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
-SRCDIR=${NAME}
-SRCARCHIVE=${NAME}src-${VERSION}.tar.gz
+SRCDIR=${PNAME}
+SRCARCHIVE=${SRCDIR}${VERSION//.}.zip
 
 DL_TO=${DL_TO:-5}
 DL_OPTS=${DL_OPTS:-"--timeout=${DL_TO}"}
-DL_URL="http://www.rarlab.com/rar/${SRCARCHIVE}"
+SF_MIRROR=${SF_MIRROR:-http://prdownloads.sourceforge.net}
+DL_URL="${SF_MIRROR}/${NAME}/${SRCARCHIVE}"
 
 # if source is not present, download in source rootdir if possible, or in /tmp
 if ! test -r ${SRCARCHIVE}; then
@@ -92,45 +93,73 @@ if [ -d ${PKG} ]; then
   # Clean up a previous build
   rm -rf ${PKG}
 fi
-mkdir -p ${PKG}/usr/bin
+mkdir -p ${PKG}
 
 cd ${TMP}
 rm -rf ${SRCDIR}
-if $(file -L ${CWD}/${SRCARCHIVE} | grep -q ": bzip2"); then
-  tar -xjvf ${CWD}/${SRCARCHIVE} || exit 1
-elif $(file -L ${CWD}/${SRCARCHIVE} | grep -q ": gzip"); then
-  tar -xzvf ${CWD}/${SRCARCHIVE} || exit 1
-fi
+unzip ${CWD}/${SRCARCHIVE} || exit 1
 cd ${SRCDIR} || exit 1
 
 chmod -R u+w,go+r-w,a-s .
 
+find . -type f -name '*.cpp' -o -name '*.h' | xargs sed -e 's/\r//' -i
+sed -i -e 's/\r//' \
+  Makefile.gnu gensrclist.sh FreeImage.2003.vcproj Wrapper/FreeImagePlus/doc/FreeImagePlus.dox
+
 # zcat ${CWD}/${NAME}.patch.gz | patch -p0 -E --backup --verbose || exit 1
-zcat ${CWD}/${NAME}-3.9.1-fixes.patch.gz | patch -p1 -E --backup --verbose || exit 1
+zcat ${CWD}/${PNAME}-3.12.0-syslibs.patch.gz | patch -p1 -E --backup --verbose || exit 1
+zcat ${CWD}/${PNAME}-3.12.0-doxygen.patch.gz | patch -p1 -E --backup --verbose || exit 1
 
-sed -i \
-  -e '/^CXX=/s|=.*|=g++|g' \
-  -e "/^CXXFLAGS=/s|=.*|=${SLKCFLAGS} -fPIC -DPIC|g" \
-  -e 's|^STRIP=.*|STRIP=true|g' \
-  -e "/LINK/s|-o libunrar.so|-Wl,-soname,libunrar.so.${SONAMEVER} -o libunrar.so.${SVER}|g" \
-  makefile.unix || exit 1
+touch -r Source/FreeImage.h.syslibs Source/FreeImage.h
 
-mv -f makefile.unix Makefile || exit 1
-make -j${NJOBS} lib || exit 1
-make clean || exit 1
-ln -sf lib${NAME}.so.${SVER} lib${NAME}.so || exit 1
+# remove all included libs to make sure these don't get used during compile
+rm -r Source/Lib* Source/ZLib Source/OpenEXR
+
+# some encoding / line ending cleanups
+iconv -f ISO-8859-1 -t UTF-8 Whatsnew.txt > Whatsnew.txt.tmp
+touch -r Whatsnew.txt Whatsnew.txt.tmp
+mv Whatsnew.txt.tmp Whatsnew.txt
+sed -i 's/\r//g' Whatsnew.txt license-*.txt gensrclist.sh \
+  Wrapper/FreeImagePlus/WhatsNew_FIP.txt
+
+sed -i -e "s|-O3|${SLKCFLAGS}|g" Makefile.gnu || exit 1
+
+sh ./gensrclist.sh || exit 1
+
 make -j${NJOBS} || exit 1
 
-install -m0755 ${NAME} ${PKG}/usr/bin/ || exit 1
+# build libfreeimageplus DIY, as the provided makefile makes libfreeimageplus
+# contain a private copy of libfreeimage <sigh>
+FIP_OBJS=
+for i in Wrapper/FreeImagePlus/src/fip*.cpp; do
+  gcc -o ${i}.o ${SLKCFLAGS} -fPIC -fvisibility=hidden \
+    -ISource -IWrapper/FreeImagePlus -c ${i} ${LDFLAGS} || exit 1
+  FIP_OBJS="${FIP_OBJS} ${i}.o"
+done
+gcc -shared -LDist -o Dist/lib${NAME}plus-${VERSION}.so \
+  -Wl,-soname,lib${NAME}plus.so.${SONAME} ${FIP_OBJS} -lfreeimage-${VERSION} ${LDFLAGS} || exit 1
 
-mkdir -p ${PKG}/usr/lib ${PKG}/usr/include/unrar
-install -pm 755 lib${NAME}.so.${SVER} ${PKG}/usr/lib/ || exit 1
-ln -sf lib${NAME}.so.${SVER} ${PKG}/usr/lib/lib${NAME}.so.${SONAMEVER} || exit 1
-ln -sf lib${NAME}.so.${SONAMEVER} ${PKG}/usr/lib/lib${NAME}.so || exit 1
-install -pm 644 dll.hpp ${PKG}/usr/include/${NAME}/dll.hpp || exit 1
+( cd Wrapper/FreeImagePlus/doc || exit 1
+  doxygen FreeImagePlus.dox || exit 1
+) || exit 1
 
-mkdir -p ${PKG}/usr/man/man1
-install -m0644 ${CWD}/${NAME}.1.gz ${PKG}/usr/man/man1/ || exit 1
+mkdir -p ${PKG}/usr/lib
+
+
+install -m 755 Dist/lib${NAME}-${VERSION}.so ${PKG}/usr/lib/ || exit 1
+ln -s lib${NAME}-${VERSION}.so ${PKG}/usr/lib/lib${NAME}.so.${SONAME} || exit 1
+ln -s lib${NAME}-${VERSION}.so ${PKG}/usr/lib/lib${NAME}.so || exit 1
+
+install -m 755 Dist/lib${NAME}plus-${VERSION}.so ${PKG}/usr/lib/ || exit 1
+ln -s lib${NAME}plus-${VERSION}.so \
+  ${PKG}/usr/lib/lib${NAME}plus.so.${SONAME} || exit 1
+ln -s lib${NAME}plus-${VERSION}.so \
+  ${PKG}/usr/lib/lib${NAME}plus.so || exit 1
+
+mkdir -p ${PKG}/usr/include
+install -p -m 644 Source/FreeImage.h ${PKG}/usr/include/ || exit 1
+install -p -m 644 Wrapper/FreeImagePlus/FreeImagePlus.h \
+  ${PKG}/usr/include/ || exit 1
 
 ( cd ${PKG}
   find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
@@ -140,8 +169,8 @@ install -m0644 ${CWD}/${NAME}.1.gz ${PKG}/usr/man/man1/ || exit 1
 # Add a documentation directory:
 mkdir -p ${DOCDIR}
 cp -a \
-  *.txt ${CWD}/ChangeLog.SB \
-  ${DOCDIR}/
+  Whatsnew.txt license-*.txt Wrapper/FreeImagePlus/WhatsNew_FIP.txt ${CWD}/ChangeLog.SB \
+  Wrapper/FreeImagePlus/doc/html ${DOCDIR}/
 find ${DOCDIR}/ -type d -print0 | xargs -0 chmod 0755
 find ${DOCDIR}/ -type f -print0 | xargs -0 chmod 0644
 
@@ -177,7 +206,7 @@ if [ "${SB_REP}" = "YES" ] ;then
   # Replicate slackbuild and patches
   mkdir -p ${SBDIR}
   install -m0644 ${CWD}/slack-desc ${CWD}/slack-required ${CWD}/ChangeLog.SB \
-                 ${CWD}/${NAME}-*.patch.gz  ${CWD}/${NAME}.1.gz ${SBDIR}/
+                 ${CWD}/${PNAME}-*.patch.gz ${SBDIR}/
   install -m0755 ${CWD}/${NAME}.SlackBuild \
                  ${SBDIR}/${NAME}.SlackBuild
   sed -i "/^VERSION=/s/:-.*}/:-$VERSION}/
