coreutils, deluge, emesene, file, gst-plugins-good, gtksourceview, hunspell-{en,pt}, kmess, libdc1394, libtorrent-rasterbar, libusb1, qbittorrent, sane, totem, totem-pl-parser, xf86-video-nouveau

diff --git a/lame/lame.SlackBuild b/lame/lame.SlackBuild
--- a/lame/lame.SlackBuild
+++ b/lame/lame.SlackBuild
@@ -51,7 +51,7 @@ else
 fi
 SLKTARGET=${SLKTARGET:-i486}
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-2}
+BUILD=${BUILD:-3}
 NJOBS=${NJOBS:-2}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -105,6 +105,14 @@ cd ${SRCDIR} || exit 1
 chmod -R u+w,go+r-w,a-s .
 
 # zcat ${CWD}/${NAME}.patch.gz | patch -p0 -E --backup --verbose || exit 1
+if [ -r ${CWD}/apply-patches.sh ]; then
+  . ${CWD}/apply-patches.sh || exit 1
+fi
+
+# It fails parallel make otherwise when enabling nasm...
+mkdir libmp3lame/i386/.libs
+
+autoreconf -if || exit 1
 
 sed -i -e 's/^\(\s*hardcode_libdir_flag_spec\s*=\).*/\1/' configure || exit 1
 
@@ -146,9 +154,8 @@ fi
 rmdir -p ${PKG}/usr/share
 mkdir -p ${DOCDIR}/html
 cp -a \
-  COPYING ChangeLog README TODO USAGE LICENSE doc/html/*.html doc/html/*.css \
-  API HACKING STYLEGUIDE ${CWD}/ChangeLog.SB \
-  ${DOCDIR}/
+  COPYING ChangeLog README TODO USAGE LICENSE API HACKING STYLEGUIDE \
+  ${CWD}/ChangeLog.SB ${DOCDIR}/
 cp -a \
   doc/html/*.html doc/html/*.css \
   ${DOCDIR}/html/
@@ -186,11 +193,13 @@ sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
 
 if [ "${SB_REP}" = "YES" ] ;then
   # Replicate slackbuild and patches
-  mkdir -p ${SBDIR}
+  mkdir -p ${SBDIR}/patches
   install -m0644 ${CWD}/slack-desc ${CWD}/slack-required ${CWD}/ChangeLog.SB \
-                 ${SBDIR}/
+                 ${CWD}/apply-patches.sh ${SBDIR}/
   install -m0755 ${CWD}/${NAME}.SlackBuild \
                  ${SBDIR}/${NAME}.SlackBuild
+  install -m0644 ${CWD}/patches/*.gz \
+                 ${SBDIR}/patches/
   sed -i "/^VERSION=/s/:-.*}/:-$VERSION}/
           /^BUILD=/s/:-.*}/:-$BUILD}/
           /^  ARCH=/s/:-.*}/:-$ARCH}/
