cpufreq-utils, libflashsupport, oss, schroedinger

diff --git a/kernel-kmod/kmod-oss-custom/kmod-oss-custom.SlackBuild b/kernel-kmod/kmod-oss-custom/kmod-oss-custom.SlackBuild
--- a/kernel-kmod/kmod-oss-custom/kmod-oss-custom.SlackBuild
+++ b/kernel-kmod/kmod-oss-custom/kmod-oss-custom.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/sh
-#-- cpufreq-utils for Slackware --
-# Build script by Phantom X <megaphantomx@bol.com.br>
-# Suggested usage: $ cpufreq-utils.SlackBuild 2>&1 | tee build.log
+#-- kmod-oss for Slackware --
+# Build script by Phantom X <megaphantomx@bol.com.brg>
+# Suggested usage: $ kmod-oss-custom.SlackBuild 2>&1 | tee build-custom.log
 #--
 # Copyright 2008 Phantom X, Goiania, Brazil.
 # Copyright 2006 Martijn Dekker, Groningen, Netherlands.
@@ -23,13 +23,10 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# http://www.kernel.org/pub/linux/utils/kernel/cpufreq/cpufrequtils.html
+# http://www.opensound.com/
 
 PACKAGER_ID=${PACKAGER_ID:-$USER}
 PACKAGER=${PACKAGER:-$USER@$HOSTNAME}
-
-# Set YES for native build with gcc >= 4.2
-SB_NATIVE=${SB_NATIVE:-NO}
 
 # Set to YES to replicate slackbuild and patches
 SB_REP=${SB_REP:-YES}
@@ -40,164 +37,147 @@ if [ ! -d ${TMP} ]; then
   mkdir -p ${TMP}
 fi
 
-PNAME=cpufrequtils
-NAME=cpufreq-utils
+KERNNAME=${KERNNAME:-custom}
+PNAME=oss
+NAME=kmod-${PNAME}-${KERNNAME}
+SB_NAME=$(echo ${NAME} | sed "s|${KERNNAME}$|custom|g")
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-005}
-if [ "${SB_NATIVE}" = "YES" ] ;then
-  ARCH=${ARCH:-$(uname -m)}
-else
-  ARCH=${ARCH:-i686}
-fi
-SLKTARGET=${SLKTARGET:-i486}
+VERSION=${VERSION:-4.1-080705}
+SVER="$(echo ${VERSION} | cut -d - -f1)"
+BVER="$(echo ${VERSION} | cut -d - -f2)"
+ARCH=${ARCH:-$(uname -m)}
 BUILD=${BUILD:-1}
-NJOBS=${NJOBS:-2}
-DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
-SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
+KVERSION=${KVERSION:-$(uname -r)}
+PKVERSION="$(echo ${KVERSION} | tr - _ )"
+KMODDIR=${PKG}/lib/modules/${KVERSION}/extra/$(echo ${NAME} |cut -d - -f2)
+SBDIR=${PKG}/usr/src/slackbuilds/kernel-kmod/${NAME}-${VERSION}_${KVERSION}
 PKGDEST=${PKGDEST:-${CWD}}
-PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )-${ARCH}-${BUILD}${PACKAGER_ID}
+PKGNAME=${NAME}-$(echo ${VERSION} | tr - . )_${PKVERSION}-${ARCH}-${BUILD}${PACKAGER_ID}
 
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
 SRCDIR=${PNAME}-${VERSION}
-SRCARCHIVE=${SRCDIR}.tar.bz2
+RSRCDIR=${PNAME}-v${SVER}-build${BVER}-src-gpl
+SRCARCHIVE=${RSRCDIR}.tar.bz2
 
 DL_TO=${DL_TO:-5}
 DL_OPTS=${DL_OPTS:-"--timeout=${DL_TO}"}
-DL_URL="http://www.kernel.org/pub/linux/utils/kernel/cpufreq/${SRCARCHIVE}"
+DL_URL="http://www.4front-tech.com/developer/sources/testing/gpl/${SRCARCHIVE}"
 
 # if source is not present, download in source rootdir if possible, or in /tmp
 if ! test -r ${SRCARCHIVE}; then
   test -r ${CWD}/${SRCARCHIVE} || wget ${DL_OPTS} ${DL_URL} || exit 1
 fi
 
-if [ "${SB_NATIVE}" = "YES" ] ;then
-  SLKCFLAGS="-O2 -march=native -mtune=native ${SB_ECFLAGS} -pipe"
-else
-  case "${ARCH}" in
-    i[3-6]86)    SLKCFLAGS="-O2 -march=${ARCH} -mtune=i686"
-                 ;;
-    s390)        SLKCFLAGS="-O2"
-                 ;;
-    x86_64)      SLKCFLAGS="-O2 -fPIC"
-                 ;;
-  esac
-fi
-
-case "${ARCH}" in
-  i[3-6]86)
-    SB_MAKEDIR=i386 || exit 1
-    ;;
-  x86_64)
-    SB_MAKEDIR=x86_64 || exit 1
-    ;;
-esac
+unset LDFLAGS CFLAGS CXXFLAGS CPPFLAGS OSFLAGS LIBRARIES
 
 if [ -d ${PKG} ]; then
   # Clean up a previous build
   rm -rf ${PKG}
 fi
-mkdir -p ${PKG}
+mkdir -p ${KMODDIR}
 
 cd ${TMP}
 rm -rf ${SRCDIR}
+mkdir -p ${SRCDIR}/build
+cd ${SRCDIR} || exit 1
 if $(file -L ${CWD}/${SRCARCHIVE} | grep -q ": bzip2"); then
   tar -xjvf ${CWD}/${SRCARCHIVE} || exit 1
 elif $(file -L ${CWD}/${SRCARCHIVE} | grep -q ": gzip"); then
   tar -xzvf ${CWD}/${SRCARCHIVE} || exit 1
 fi
-cd ${SRCDIR} || exit 1
 
 chmod -R u+w,go+r-w,a-s .
 
 # zcat ${CWD}/${NAME}.patch.gz | patch -p0 -E --backup --verbose || exit 1
-zcat ${CWD}/disable-gsic.patch.gz | patch -p1 -E --backup --verbose || exit 1
 
-make CFLAGS="${SLKCFLAGS}" || exit 1
-make CFLAGS="${SLKCFLAGS}" -C debug/${SB_MAKEDIR} || exit 1
+FSRCDIR="${TMP}/${SRCDIR}/${RSRCDIR}"
 
-make DESTDIR=${PKG} \
-     bindir=/usr/bin \
-     includedir=/usr/include \
-     libdir=/usr/lib \
-     mandir=/usr/man install || exit 1
+( cd build || exit 1
 
-rm -f ${PKG}/usr/lib/*.a
-rm -f ${PKG}/usr/lib/*.la
+  "${FSRCDIR}/configure" || exit 1
 
-if [ "${SB_MAKEDIR}" = "i386" ] ; then
-  install debug/i386/centrino-decode \
-          ${PKG}/usr/bin/centrino-decode || exit 1
-  install debug/i386/dump_psb \
-          ${PKG}/usr/bin/dump_psb || exit 1
-fi
-install debug/${SB_MAKEDIR}/powernow-k8-decode \
-        ${PKG}/usr/bin/powernow-k8-decode || exit 1
+  sed -i -e '/^SUBDIRS=/s|=.*$|=os_cmd kernel kernel/OS/Linux|g' Makefile || exit 1
+  sed -i -e '/^SUBDIRS=/s|=.*$|=ossvermagic|g' os_cmd/Linux/Makefile || exit 1
+  
+  make build || exit 1
+) || exit 1
 
-chmod -R a-s ${PKG}
+( cd build/prototype/usr/lib/oss/build || exit 1
 
-( cd ${PKG}
-  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
-  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
-  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs strip --strip-debug 2> /dev/null
-)
+  # Check if we should use REGPARM or non-REGPARM modules
+  if ../../../sbin/ossvermagic -r || /sbin/modinfo ext3|grep -q REGPARM ; then
+    rm -rf ../objects
+    ln -s objects.regparm ../objects
+    rm -rf ../modules
+    ln -s modules.regparm ../modules
+  else
+    rm -rf ../objects
+    ln -s objects.noregparm ../objects
+    rm -rf ../modules
+    ln -s modules.noregparm ../modules
+  fi
 
-# Add a documentation directory:
-mkdir -p ${DOCDIR}
-cp -a \
-  AUTHORS COPYING ChangeLog README NEWS THANKS TODO ${CWD}/ChangeLog.SB \
-  ${DOCDIR}/
-find ${DOCDIR}/ -type d -print0 | xargs -0 chmod 0755
-find ${DOCDIR}/ -type f -print0 | xargs -0 chmod 0644
+  mkdir kernel
 
-# Compress and link manpages, if any:
-if [ -d ${PKG}/usr/share/man ]; then
-  mv ${PKG}/usr/share/man ${PKG}/usr/man
-  rmdir ${PKG}/usr/share
-fi
-if [ -d ${PKG}/usr/man ]; then
-  ( cd ${PKG}/usr/man
-    for manpagedir in $(find . -type d -name "man*") ; do
-      ( cd ${manpagedir}
-        for eachpage in $( find . -type l -maxdepth 1) ; do
-          ln -s $( readlink ${eachpage} ).gz ${eachpage}.gz
-          rm -f ${eachpage}
-        done
-        gzip -9 *.?
-        # Prevent errors
-        rm -f *.gz.gz
-      )
-    done
-  )
-fi
+  cp -f ../objects/osscore.o osscore_mainline.o
+  ln -sf ../include/sys/*.h ../include/sys/ossddk .
 
-# Compress info pages, if any:
-if [ -d ${PKG}/usr/info ]; then
-  ( cd ${PKG}/usr/info
-    rm -f dir
-    gzip -9 *
-  )
-fi
+  rm -f Makefile
+  ln -s Makefile.osscore Makefile
+
+  make KERNELDIR=/lib/modules/${KVERSION}/build || exit 1
+  ld -r osscore.ko osscore_mainline.o -o kernel/osscore.ko || exit 1
+
+  for n in ../modules/*.o ; do
+    N=$(basename $n .o)
+    rm -f ${N}_mainline.o Makefile
+    sed "s/MODNAME/${N}/" Makefile.tmpl > Makefile
+    ln -s ${n} ${N}_mainline.o
+    make KERNELDIR=/lib/modules/${KVERSION}/build || echo "make ${N}" >> modbuild-error
+    ld -r ${N}.ko ${N}_mainline.o -o kernel/${N}.ko || echo "ld ${N}" >> modbuild-error
+    rm -f ${N}_mainline.o
+    make clean
+  done
+  if [ -f modbuild-error ] ;then
+    exit 1
+  fi
+
+) || exit 1
+
+install -m0644 build/prototype/usr/lib/oss/build/kernel/*.ko \
+               ${KMODDIR}/ || exit 1
 
 mkdir -p ${PKG}/install
 cat ${CWD}/slack-desc > ${PKG}/install/slack-desc
 cat ${CWD}/slack-required > ${PKG}/install/slack-required
+echo "kernel-${KERNNAME} = ${PKVERSION}-${ARCH}-$( echo ${PKVERSION} | cut -d _ -f2 )" >> \
+     ${PKG}/install/slack-required
 
-sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
+cat > ${PKG}/install/doinst.sh <<EOF
+# A good idea whenever kernel modules are added or changed:
+if [ -x sbin/depmod ]; then
+  chroot . /sbin/depmod -a ${KVERSION} 1> /dev/null 2> /dev/null
+fi
+EOF
+
+sed -i "s|_KERNNAME|${KERNNAME}|g;
+        s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
        ${PKG}/install/slack-desc
 
 if [ "${SB_REP}" = "YES" ] ;then
   # Replicate slackbuild and patches
   mkdir -p ${SBDIR}
   install -m0644 ${CWD}/slack-desc ${CWD}/slack-required ${CWD}/ChangeLog.SB \
-                 ${CWD}/*.patch.gz ${SBDIR}/
-  install -m0755 ${CWD}/${NAME}.SlackBuild \
-                 ${SBDIR}/${NAME}.SlackBuild
+                 ${SBDIR}/
+  install -m0755 ${CWD}/${SB_NAME}.SlackBuild \
+                 ${SBDIR}/${SB_NAME}.SlackBuild
   sed -i "/^VERSION=/s/:-.*}/:-$VERSION}/
           /^BUILD=/s/:-.*}/:-$BUILD}/
-          /^  ARCH=/s/:-.*}/:-$ARCH}/
-          " ${SBDIR}/${NAME}.SlackBuild
+          /^ARCH=/s/:-.*}/:-$ARCH}/
+          /^KVERSION=/s/:-.*}/:-$KVERSION}/
+          " ${SBDIR}/${NAME}-custom.SlackBuild
 fi
 
 # Build package:
