coreutils, cups-filters, djview4->djview, djvulibre, dracut, git,  grep, gssdp, gupnp, gupnp-av, harfbuzz, httpd, iproute2, libprojectm, mupdf, qpdf, swig, virtualbox, winetricks

diff --git a/wine/wine.SlackBuild b/wine/wine.SlackBuild
--- a/wine/wine.SlackBuild
+++ b/wine/wine.SlackBuild
@@ -61,7 +61,7 @@ else
 fi
 [ "${SLKTARGET}" = "x86_64" ] && SLKTARGET32=${SLKTARGET32:-i486}
 SLKDTARGET=${SLKDTARGET:-slackware}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 NJOBS=${NJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 DOCDIR=${PKG}/usr/doc/${NAME}-${VERSION}
 SBDIR=${PKG}/usr/src/slackbuilds/${NAME}
@@ -140,7 +140,7 @@ if [ -r ${CWD}/apply-patches.sh ]; then
   . ${CWD}/apply-patches.sh || exit 1
 fi
 
-SLKCFLAGS="$( echo ${SLKCFLAGS} | sed -e 's/ -._FORTIFY_SOURCE=.//' -e 's/ -fPIC//' -e 's/-fomit-frame-pointer//' ) -U_FORTIFY_SOURCE"
+SLKCFLAGS="$( echo ${SLKCFLAGS} | sed -e 's/ -._FORTIFY_SOURCE=.//' -e 's/ -fPIC//' -e 's/-fomit-frame-pointer//' ) -U_FORTIFY_SOURCE -Wno-error"
 
 unset SB_PAOPTS SB_MMOPTS
 [ "${SB_PA}" = "YES" ] || SB_PAOPTS="--without-pulse"
@@ -152,7 +152,7 @@ fi
 autoreconf -ivf || exit 1
 
 SB_CONFIGURE() {
-CFLAGS="${SLKCFLAGS} -Wno-error" \
+CFLAGS="${SLKCFLAGS}" \
 CXXFLAGS="${SLKCFLAGS}" \
 ../configure \
   --prefix=/usr \
@@ -168,12 +168,16 @@ CXXFLAGS="${SLKCFLAGS}" \
   --without-hal \
   --with-dbus \
   --without-cups \
+  ${SB_PAOPTS} \
   --build=${SLKTARGET}-${SLKDTARGET}-linux \
   $@ || return $?
 
-  make depend || return $?
-  make -j${NJOBS} || make
+}
 
+SB_MAKE32() {
+  SLKCFLAGS="${SLKCFLAGS} -mstackrealign -mincoming-stack-boundary=2"
+  make -j${NJOBS} CFLAGS="${SLKCFLAGS}" CXXFLAGS="${SLKCFLAGS}" \
+    || make CFLAGS="${SLKCFLAGS}" CXXFLAGS="${SLKCFLAGS}"
 }
 
 SB_INSTALL() {
@@ -195,17 +199,23 @@ if [ "${ARCH}" = "x86_64" ] ;then
       --x-libraries=/usr/lib${LIBDIRSUFFIX} \
       --enable-win64 ${SB_MMOPTS} \
       --build=${SLKTARGET}-${SLKDTARGET}-linux || exit $?
+
+    make -j${NJOBS} || make || exit $?
+
   ) || exit $?
 
 # 32-bit build
   ( unset ARCH
     cd build32 || exit $?
     export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:${PKG_CONFIG_PATH}"
-    SLKCFLAGS="${SLKCFLAGS} -fno-omit-frame-pointer -mstackrealign"
+    SLKCFLAGS="${SLKCFLAGS} -fno-omit-frame-pointer"
     SB_CONFIGURE \
       --libdir=/usr/lib \
       --x-libraries=/usr/lib \
       --with-wine64="${SB_SROOT}/build64" || exit $?
+
+    SB_MAKE32 || exit $?
+
     SB_INSTALL ${PKG32} || exit $?
   ) || exit $?
 
@@ -232,6 +242,9 @@ else
       --libdir=/usr/lib${LIBDIRSUFFIX} \
       --x-libraries=/usr/lib${LIBDIRSUFFIX} \
       --build=${SLKTARGET}-${SLKDTARGET}-linux || exit $?
+
+    SB_MAKE32 || exit $?
+
     SB_INSTALL ${PKG} || exit $?
   ) || exit $?
 fi
