bzr, cryptsetup, dialog, feh, foobillardplus, fotoxx, git, KDE 4.7.3, kid3, kmymoney, libdvbpsi, libmicrohttpd, libpng, libtalloc, mercurial, nss, nvidia-glx, pbzip2, postfix, pyqt4, qscintilla, sip, virtualbox, virtuoso-opensource, wine, xorg-server/

diff --git a/nvidia-glx/nvidia-glx.SlackBuild b/nvidia-glx/nvidia-glx.SlackBuild
--- a/nvidia-glx/nvidia-glx.SlackBuild
+++ b/nvidia-glx/nvidia-glx.SlackBuild
@@ -40,7 +40,7 @@ fi
 NAME=nvidia-glx
 PKG=${PKG:-${TMP}/package-${NAME}}
 
-VERSION=${VERSION:-290.03}
+VERSION=${VERSION:-290.06}
 CLSOVER=1.0.0
 LVER=$(echo ${VERSION} | tr - . )
 VIDEOGP="$(getent group video | cut -d ':' -f 3)"
@@ -98,6 +98,12 @@ sh ${CWD}/${SRCARCHIVE} -x --target ${SRCDIR} || exit 1
 cd ${SRCDIR} || exit 1
 
 chmod -R u+w,go+r-w,a-s .
+
+if ! [ -e libOpenCL.so.${CLSOVER} ] ;then
+  echo "libOpenCL.so.${CLSOVER} not found"
+  echo "Check CLSOVER"
+  exit 1
+fi
 
 # zcat ${CWD}/${NAME}.patch.gz | patch -p0 -E --backup --verbose || exit 1
 
